### ISSUE TITLE
Support for OIDC Authentication

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#101]
Use OpenID Connect within your workflows to authenticate with Azure.

Blocked by https://github.com/Azure/azure-sdk-for-go/issues/15615

doc: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
similar issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/16554

**Comment by ms-henglu** [comment]
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity doesn't support OIDC yet.

Roadmap: https://github.com/Azure/azure-sdk-for-go/issues/16728

**Comment by petr-stupka** [comment]
Helper already available via https://github.com/hashicorp/go-azure-helpers/pull/115

Terraform 1.2.0 introduced support for backend authentication OIDC as well

**Comment by LaurentLesle** [comment]
@ms-henglu can you check if you can progress with this issue? Looks like the dependency has been closed https://github.com/Azure/azure-sdk-for-go/issues/16728

**Comment by jamescrowley** [comment]
Just got blocked by this as we're using OIDC for GitHub Actions on a new project. We're setting the `ARM_USE_OIDC` environment variable, by the way, so if you can support that in addition to any properties on the provider itself that would be fab. Many thanks.

**Comment by ms-henglu** [comment]
@LaurentLesle - Thanks! I just checked again, it seems they're tracking this feature by https://github.com/Azure/azure-sdk-for-go/issues/15615 according to https://github.com/Azure/azure-sdk-for-go/issues/16728#issuecomment-1119759637.

**Comment by thomas-vercoutre-nzta** [comment]
Any news on that feature ?

**Comment by dschniepp** [comment]
Does it make sense to provide a temporarily solution based on the upcoming release, with the workaround described here https://github.com/Azure/azure-sdk-for-go/issues/15615#issuecomment-1211012677? @ms-henglu would you be interested in this as a contribution?

**Comment by ms-henglu** [comment]
Hi @dschniepp ,

Thanks for the suggestion! I'll give it a try when the azidentity v1.2.0 stable version released in the next week.

**Comment by dschniepp** [comment]
Thanks, @ms-henglu if you need support feel free to loop me in.

**Comment by AdamCoulterOz** [comment]
@grayzu was this planned for `1.1`? looks like it didn't make it?

**Comment by ms-henglu** [comment]
Hi all,

This feature has been released in v1.3.0. More details can be found here: https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/service_principal_oidc

I'll close this issue but feel free to reopen it if there's any further question.
