### ISSUE TITLE
Container App Environment - "Missing error information"

### ISSUE THREAD

**Issue by mmruesch12** [Azure/terraform-provider-azapi#103]
I've been attempting to create a Container App Environment with the following code:

`resource "azapi_resource" "container_app_environment" {
  name      = "test"
  location  = var.location
  parent_id = "/subscriptions/xxxx/resourceGroups/xxxx"
  type = "Microsoft.App/managedEnvironments@2022-01-01-preview"
  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.analytics.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.analytics.primary_shared_key
        }
      }
    }
  })
}`

And I get the following error:
`│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.App/managedEnvironments/test\" / Api Version \"2022-01-01-preview\")": missing error information
│
│   with azapi_resource.container_app_environment,
│   on demo-zombie-dice-api.tf line 112, in resource "azapi_resource" "container_app_environment":
│  112: resource "azapi_resource" "container_app_environment" {
`

The error says "missing error information" and I'm not sure where to go from there. Can anybody help me with this?

Thanks in advance!

**Comment by ms-henglu** [comment]
Hi @mmruesch12 ,

Thank you for taking time to report this issue.

I can create the `Microsoft.App/managedEnvironments` with the following config, would you please give it a try?

```hcl
resource "azurerm_resource_group" "test" {
  name     = "henglu510"
  location = "westeurope"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "henglu510"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azapi_resource" "container_app_environment" {
  type      = "Microsoft.App/managedEnvironments@2022-01-01-preview"
  name      = "henglu510"
  parent_id = azurerm_resource_group.test.id
  location  = azurerm_resource_group.test.location
  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.test.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.test.primary_shared_key
        }
      }
    }
  })

  // properties/appLogsConfiguration/logAnalyticsConfiguration/sharedKey contains credential which will not be returned,
  // using this property to suppress plan-diff
  ignore_missing_property = true
}
```
