### ISSUE TITLE
Provider doesn't honour ARM_CLIENT_ID for managed identity

### ISSUE THREAD

**Issue by Oechiih** [Azure/terraform-provider-azapi#108]
When using the AzAPI provider from an Azure VM with user assigned managed identity (for example a self-hosted Azure DevOps agent) it doesn't honour the ARM_CLIENT_ID environment variable to use a specific msi rather than a system-assigned identity. If no system-assigned msi is assigned the provider fails to get an access token. If there is a system-assigned msi the provider ignores the explicitly specified client_id and instead just uses the system-assigned one.
The regular azurerm provider supports user-assigned msi just fine.

Cheers
Jan

**Comment by ms-henglu** [comment]
Hi @Oechiih ,

Thank you for taking time to report this issue.

It has been fixed in azidentity v1.0.0, I've raised a PR to update the dependency.

**Comment by ms-henglu** [comment]
Hi @Oechiih ,

I just released the fix in https://github.com/Azure/terraform-provider-azapi/releases/tag/v0.2.1, would you please give it a try?

**Comment by LaurentLesle** [comment]
I had a similar issue. version 0.2.1 fixed it. Thanks

**Comment by ms-henglu** [comment]
Thanks @LaurentLesle , I'll close this issue.
