### ISSUE TITLE
cannot update storage account resourceAccessRules

### ISSUE THREAD

**Issue by fgarcia-cnb** [Azure/terraform-provider-azapi#115]
I'm trying to update a storage account's resourceAccessRules attribute:

```hcl
resource "azapi_update_resource" "synapse_dfs_msi_access" {
  count = var.resource_count

  resource_id = module.synapse_dfs_storage.ids[count.index]
  type        = "Microsoft.Storage/storageAccounts@2021-09-01"

  body = jsonencode({
    properties = {
      networkAcls = {
        resourceAccessRules = [
          {
            resourceId = azurerm_synapse_workspace.synapse_workspace[count.index].identity[0].principal_id
            tenantId   = data.azurerm_client_config.current.tenant_id
          }
        ]
      }
    }
  })
}
```

put i get the following error:

``
Error: creating/updating "Resource: (ResourceId \"/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Storage/storageAccounts/td04dgc96tgi00sa\" / Api Version \"2021-09-01\")": PUT https://management.azure.com/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/td04dgc96tgi00sa -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request ERROR CODE: InvalidValuesForRequestParameters -------------------------------------------------------------------------------- { "error": { "code": "InvalidValuesForRequestParameters", "message": "Values for request parameters are invalid: networkAcls.resourceAccessRules[*].resourceId. For more information, see - https://aka.ms/storagenetworkruleset" } }
``

Pretty sure my json is structured correctly. Why is it using PUT instead of PATCH?

**Comment by ms-henglu** [comment]
Hi @fgarcia-cnb , 

Thank you for taking time to report this issue!

In the `resourceAccessRules`, the `resourceId` should be the ARM id of a resource. For example, the ID of a user assigned identity, or the ID of synapse workspace.

> Why is it using PUT instead of PATCH?
Most of ARM resources support PUT method to update a resource.

Here's an example, it adds access rules for both synapse workspace and its user assigned identity. Hope this can help you!

```
data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "test" {
  name     = "henglu520-rg"
  location = "eastus"
}

resource "azurerm_storage_account" "test" {
  name                     = "henglu520synapsesa"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
}

resource "azurerm_storage_data_lake_gen2_filesystem" "test" {
  name               = "synapsefs"
  storage_account_id = azurerm_storage_account.test.id
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "synapseuai"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azapi_resource" "synapse" {
  type      = "Microsoft.Synapse/workspaces@2021-06-01"
  name      = "henglu520synapse"
  parent_id = azurerm_resource_group.test.id
  location  = azurerm_resource_group.test.location
  identity {
    type         = "SystemAssigned, UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.test.id]
  }
  body = jsonencode({
    properties = {
      defaultDataLakeStorage = {
        accountUrl = azurerm_storage_account.test.primary_dfs_endpoint
        filesystem = azurerm_storage_data_lake_gen2_filesystem.test.name
      }
      sqlAdministratorLogin         = "sqladminuser"
      sqlAdministratorLoginPassword = "H@Sh1CoR3!"
    }
  })

  // In the embedded schema, identity type's allowed value is "SystemAssigned,UserAssigned", add the following config to bypass the check
  schema_validation_enabled = false
  // sqlAdministratorLoginPassword conains crendential, it won't be returned from GET response
  ignore_missing_property = true
}

resource "azurerm_storage_account" "other" {
  name                     = "henglu520"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
}


resource "azapi_update_resource" "synapse_dfs_msi_access" {
  resource_id = azurerm_storage_account.other.id
  type        = "Microsoft.Storage/storageAccounts@2021-09-01"

  body = jsonencode({
    properties = {
      networkAcls = {
        resourceAccessRules = [
          {
            resourceId = azurerm_user_assigned_identity.test.id // The ID of a user assigned identity
            tenantId   = azurerm_user_assigned_identity.test.tenant_id
          },
          {
            resourceId = azapi_resource.synapse.id // The ID of a Synapse workspace
            tenantId   = data.azurerm_client_config.current.tenant_id
          }
        ]
      }
    }
  })
}

```

**Comment by fgarcia-cnb** [comment]
ah youre right, i was passing the managed identity instead of the workspace id. i shouldve caught that. i believe azurerm storage_account actually supports this attribute under a different name: private_link_access

side note... synapse workspaces require a storage account to be created before the workspace. but then i need to be able to pass the workspace id to the original storage account to set resourceAccessRules/private_link_access. this causes a cyclical dependency. So i need to ignore the attribute in the storage account resource, and then update it in an azapi_update resource.

does that make sense? or is there a better approach?

**Comment by ms-henglu** [comment]
Yes, it seems azurerm has a separate resource for access rules: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_network_rules

**Comment by fgarcia-cnb** [comment]
yea, unfortunately our storage account module uses the storage account resource to set network acls, and they mention how its not recommended to set network acls in both places. i think my approach will have to be the one we go with

**Comment by ms-henglu** [comment]
But this `azapi_update_resource` solution is also `set network acls in both places`, it might cause diff on the storage account resource.

**Comment by fgarcia-cnb** [comment]
right, but we only touch the resourceAccessRules attribute with azapi. we ignore that attribute in the azurerm resource. with the storage network resource, default action is required, so if someone accidentally changes the value on one side and not the other, it will conflict. with azapi its cleaner since we only touch the specific parameter we want

**Comment by ms-henglu** [comment]
Sounds good, and I think I can close this issue now.

**Comment by fgarcia-cnb** [comment]
yup. thank you for discussing it with me :)
