### ISSUE TITLE
`response_export_values` are calculated on every apply, causing dependent resources to be recreated

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#118]
Hi,

I have a configuration where I am deploying a new subscription, and then deploying a resource into that subscription.

To do this, I am using `response_export_values` and adding the newly created subscriptionId to the state, so that I can use it in the `parent_id` of a resource group resource that I create in the new subscription.

```terraform
resource "azapi_resource" "sub" {
  type      = "Microsoft.Subscription/aliases@2021-10-01"
  parent_id = "/"
  name      = "mytestsub12345"
  response_export_values = [
    "properties.subscriptionId",
  ]
  body = jsonencode({
    properties = {
      displayName  = "mytestsub12345"
      billingScope = "/providers/Microsoft.Billing/billingAccounts/xxxxxxx/enrollmentAccounts/yyyyyy"
      workload     = "DevTest"
    }
  })
}

resource "azapi_resource" "rg" {
  type      = "Microsoft.Resources/resourceGroups@2021-04-01"
  location  = "northeurope"
  name      = "TestRG"
  parent_id = "/subscriptions/${jsondecode(azapi_resource.sub.output).properties.subscriptionId}"
}
```

The first time this configuration is applied, it works fine. On subsequent applies, the output is recalculated, causing the dependent resource group to be deleted and re-created.

```text
  # azapi_resource.sub will be updated in-place
  ~ resource "azapi_resource" "sub" {
      ~ body                      = jsonencode(
          ~ {
              ~ properties = {
                  + billingScope = "/providers/Microsoft.Billing/billingAccounts/xxxxxxx/enrollmentAccounts/yyyyyy"
                  + displayName  = "mytestsub12345"
                  + workload     = "DevTest"
                }
            }
        )
        id                        = "/providers/Microsoft.Subscription/aliases/mytestsub12345"
        name                      = "mytestsub12345"
      ~ output                    = jsonencode(
            {
              - properties = {
                  - subscriptionId = "00000000-0000-0000-0000-000000000000"
                }
            }
        ) -> (known after apply)
```

Is there any way to prevent this from happening?

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thank you for taking time to report this issue, this is a good question! 

I can think of 2 options:
1. Add the following config to the resource group block
```
  lifecycle {
    ignore_changes = [parent_id]
  }
``` 

2. Run terraform plan/apply with `-target` option, like `terraform plan/apply -target azapi_resource.sub`, then terraform will only focus on this resource.
More information: https://www.terraform.io/cli/commands/plan#resource-targeting

**Comment by matt-FFFFFF** [comment]
Hi @ms-henglu,

Thanks for the response.

I have been debugging this and have found that the customizediff func does the following on **line 126** here:

https://github.com/Azure/terraform-provider-azapi/blob/0107dcefead8770bd3693bc6792aa0ce164080d8/internal/services/azapi_resource.go#L122-L129

As you can see the value of `old` is an empty interface. It is then comparing this to the value of `new`, which is the JSON body of the HTTP request. Because they are different, it sets the output to be computed, hence the resultant change to all dependent resources.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/16320656/170227101-12884011-a616-4ca4-a997-23d12c414bd2.png">

Since the value has not actually changed, is this a problem with the CutomizeDiff's `d.GetChange("body")` call?

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF , thank you for looking into this.

Sorry that I didn't understand this correctly. You didn't change the config, but when you run `terraform plan` again, it tells you `azapi_resource.sub will be updated in-place`, right?

That's because its properties are not returned in GET response, it's easy to fix it, by adding the following field to `azapi_resource.sub`.
```
ignore_missing_property = true
```

More info can be found [here](https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/frequently_asked_questions#after-applying-the-configuration-running-terraform-plan-found-theres-still-a-change)
