### ISSUE TITLE
Should `ignore_missing_property` default to `true`?

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#121]
`ignore_missing_property` is used to suppress plan-diff if there's a property contains secrets like credentials, and not returned from GET response.

The reason it defaults to false is: some APIs might have bugs and they don't recognize some properties, so the update failed silently and these properties are not stored in azure backend. Then if run `terraform plan` again, users can see there's diff between state and config, then users can realize something is not working properly.

However, it seems property missing caused by containing credentials is much more common than API bugs, so maybe we should change the default value to `true`?

**Comment by ms-henglu** [comment]
@grayzu

**Comment by grayzu** [comment]
Yes, I agree that we should set this to true by default.
