### ISSUE TITLE
Microsoft.RecoveryServices/vaults/backupResourceGuardProxies

### ISSUE THREAD

**Issue by mpjtaylor** [Azure/terraform-provider-azapi#122]
I am trying to use azapi_update_resource to set a backupResourceGuardProxies I managed to create the resource guards using azapi_resource but when trying to link to the resource guard I get

```hcl
resource "azapi_update_resource" "guard" {
  name      = "VaultProxy"
  type      = "Microsoft.RecoveryServices/vaults/backupResourceGuardProxies@2022-02-01"
  parent_id = azurerm_recovery_services_vault.sqlsupport.id
  body = jsonencode({
    properties = {
      resourceGuardResourceId = format("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.DataProtection/resourceGuards/%s", var.management_subscriptionid, var.guard_resource_group_name, var.resource_guard)
    }
  })
  depends_on = [azurerm_recovery_services_vault.sqlsupport]
}
```

```hcl
error: checking for presence of existing Resource: (ResourceId "/subscriptions/xxx/resourceGroups/xx/providers/Microsoft.RecoveryServices/vaults/x/backupResourceGuardProxies/VaultProxy" / Api Version "2022-02-01"): GET https://management.azure.com/subscriptions/xxx/resourceGroups/xx/providers/Microsoft.RecoveryServices/vaults/x/backupResourceGuardProxies/VaultProxy -------------------------------------------------------------------------------- RESPONSE 404: 404 Not Found ERROR CODE UNAVAILABLE
```

Has anyone got this to work

many Thanks
Marcus

**Comment by ms-henglu** [comment]
Hi @mpjtaylor ,

Thank you for taking time to report this issue.

It seems that you don't have a `backupResourceGuardProxies` called `VaultProxy` under `azurerm_recovery_services_vault.sqlsupport.id`, so the update resource couldn't find the target to update.

I made a full example, hope this can help you. I use `azapi_resource` to create a `backupResourceGuardProxies` because there's no existing `backupResourceGuardProxies`.
```
resource "azurerm_resource_group" "test" {
  name     = "henglu-recovery_vault"
  location = "West Europe"
}

resource "azurerm_recovery_services_vault" "vault" {
  name                = "henglu-recovery-vault"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"

  soft_delete_enabled = true
}

resource "azapi_resource" "guard" {
  type      = "Microsoft.DataProtection/resourceGuards@2022-03-01"
  name      = "henglu"
  parent_id = azurerm_resource_group.test.id
  location  = azurerm_resource_group.test.location
}

resource "azapi_resource" "proxy" {
  type      = "Microsoft.RecoveryServices/vaults/backupResourceGuardProxies@2022-01-01"
  name      = "default"
  parent_id = azurerm_recovery_services_vault.vault.id
  body = jsonencode({
    properties = {
      resourceGuardResourceId = azapi_resource.guard.id
    }
  })
  schema_validation_enabled = false
}

```

**Comment by mpjtaylor** [comment]
Thanks for your reply, think this is where i am stuck the guard is built in another subscription using a different pipeline, so going through your code I end up back with a different error using azapi_resource :
```hcl
resource "azapi_resource" "proxy" {
  name      = "default"
  type      = "Microsoft.RecoveryServices/vaults/backupResourceGuardProxies@2022-02-01"
  parent_id = azurerm_recovery_services_vault.sqlsupport.id
  body = jsonencode({
    properties = {
      resourceGuardResourceId = format("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.DataProtection/resourceGuards/%s", var.management_subscriptionid, var.guard_resource_group_name, var.resource_guard)
    }
  })
  depends_on = [azurerm_recovery_services_vault.sqlsupport]
}
```
but with the error:
Error: embedded schama validation failed: the `body` is invalid: `properties` is not expected here, it's read only You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block

**Comment by ms-henglu** [comment]
@mpjtaylor - I think you need to add `schema_validation_enabled = false` to the `azapi_resource .proxy` block to bypass the validation.

**Comment by mpjtaylor** [comment]
Thanks for your support adding that i still get the error 

Error: creating/updating "Resource: (ResourceId \"/subscriptions/xxx/resourceGroups/xx/providers/Microsoft.RecoveryServices/vaults/zagosupportdv05en1rsv20/backupResourceGuardProxies/xxx\" / Api Version \"2022-02-01\")": PUT https://management.azure.com/subscriptions/xxx/resourceGroups/z-xx/providers/Microsoft.RecoveryServices/vaults/x/backupResourceGuardProxies/default------------------------------------------------------------------

RESPONSE 400: 400 Bad Request ERROR CODE: BMSUserErrorResourceGuardResourceDoesntExist -------------------------------------------------------------------------------- { "error": { "code": "BMSUserErrorResourceGuardResourceDoesntExist", "message": "ResourceGuard resource doesn't exist.", "target": null, "details": null, "innerError": null }

**Comment by ms-henglu** [comment]
@mpjtaylor - I see. I think you might need to authenticate with credential that can access both subscriptions, for example, with azure cli.

**Comment by mpjtaylor** [comment]
I added the same SPN with relevant roles to both subscriptions so the permissions are there, reason I moved to azapi provider was to get away from AZ CLI

**Comment by ms-henglu** [comment]
Great! I'll close this issue as completed.
