### ISSUE TITLE
Validating azapi_resource 'body' against schema?

### ISSUE THREAD

**Issue by jamescrowley** [Azure/terraform-provider-azapi#127]
Is there any way to validate the contents of the body attribute of azapi_resource prior to applying the terraform? Not sure if this is a feature request or a documentation request!

**Comment by ms-henglu** [comment]
Hi @jamescrowley ,

Yes, azapi does support validation based on embedded schema. But this also has limitation that if the body contains property which is `known after apply`, then the whole body is `known after apply`, in this case, the body can't be validated during plan phase. To solve this, we have a [VSCode extension](https://marketplace.visualstudio.com/items?itemName=azapi-vscode.azapi) to help you author azapi config and it can provide diagnostics to indicate schema errors as you type.

**Comment by ms-henglu** [comment]
@jamescrowley - Yes, `terraform plan/apply` will do the validation, it will validate `api-version`, required property, property value's type, and property's allowed values if supported.

> currently when I do terraform plan/validate there does not appear to be validation for the body

It will throw error if not passed validation, for example, a required property is missing or declaring a not existing property. Please notice `schema_validation_enabled = false` in the resource block will disable the validation.
```
╷
│ Error: embedded schama validation failed: the `body` is invalid:
│ `properties.links.1.direction1` is not expected here. Do you mean `properties.links.1.direction`? 
│ `properties.links.1.direction` is required, but no definition was found
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
```
