### ISSUE TITLE
Language server validation error 

### ISSUE THREAD

**Issue by RAWRitsCloud** [Azure/terraform-provider-azapi#128]
Hey, so using the azapi_resource to add some IaaS workload policies into Azure Backup and it runs perfectly fine if you run the terraform however the language server or validation of the language seems to throw an error up with the API reference name as it’s “Microsoft.Backup/vaults/policy@version” and it doesn’t like the 2nd slash comes up with a key_id value error.

**Comment by ms-henglu** [comment]
Hi @RAWRitsCloud ,

Would you please provide more information like tf config? So I can help you diagnose. Thanks!

**Comment by ms-henglu** [comment]
I'll close this issue since there's no response, please feel free to reopen it, thanks!
