### ISSUE TITLE
Add support to Microsoft Graph API

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/terraform-provider-azapi#129]
https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

**Comment by ms-henglu** [comment]
Hi @LaurentLesle ,

Thank you for opening this issue.

The `azuread` provider has migrated to MS Graph API. I think you may need to file issues in this provider there's missing feature. And I think MS Graph is out of `azapi`'s targeting scope. 🤔 

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs
