### ISSUE TITLE
Schema problem w/ Microsoft.Web/connections - not sure if issue here or not?

### ISSUE THREAD

**Issue by jamescrowley** [Azure/terraform-provider-azapi#130]
I tried to create a 'Microsoft.Web/connections' resource following the instructions here for a managed identity: https://docs.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity?tabs=consumption#multi-authentication

However, azapi_resource reports that the '2018-07-01-preview' (as described in the docs) is not supported. When dropping back to an earlier version, it does not recognise the parameterValueSet attribute as valid. 

When adding schema_validation_enabled = false, the resource is created as expected, with the desired managed identity. 

Not sure if this is an issue with the azapi provider or something else?

```

resource "azapi_resource" "blob-connection" {
  type      = "Microsoft.Web/connections@2018-07-01-preview"
  name      = "${var.project}-blob"
  parent_id = azurerm_resource_group.onedriveimport.id
  location = azurerm_resource_group.onedriveimport.location
  schema_validation_enabled = false
  body = jsonencode({
    properties: {
      "api": {
          "displayName": "Azure Blob Storage",
          "id": "/subscriptions/${data.azurerm_subscription.current.subscription_id}/providers/Microsoft.Web/locations/${azurerm_resource_group.onedriveimport.location}/managedApis/azureblob",
      },
      "displayName": "Azure Storage",
      "parameterValueSet": {
          "name": "managedIdentityAuth",
          "values": {}
      },
    }
  })

}
```

**Comment by ms-henglu** [comment]
Hi @jamescrowley ,

Thanks for opening this issue.

As mentioned in https://github.com/Azure/terraform-provider-azapi/issues/127, azapi will validate the `api-version` based on its embedded schema. It seems that `2018-07-01-preview` is not available in its embedded schema nor https://github.com/Azure/azure-rest-api-specs/tree/main/specification/web/resource-manager/Microsoft.Web (source of the embedded schema). 

>When adding schema_validation_enabled = false, the resource is created as expected

Yes, `schema_validation_enabled = false` can bypass the validation.

I'll check whether the definition of `Microsoft.Web/connections@2018-07-01-preview` is missed in https://github.com/Azure/azure-rest-api-specs.

**Comment by jamescrowley** [comment]
Much appreciated @ms-henglu - if I find any issues like this in future I'll go there first!

**Comment by ms-henglu** [comment]
@jamescrowley - No problems! But I'd recommend this website: https://docs.microsoft.com/en-us/azure/templates/microsoft.web/connections?tabs=bicep which is also generated from same source, but much more readable.

**Comment by ms-henglu** [comment]
I'll close this issue. Feel free to reopen it if there's further question. :)
