### ISSUE TITLE
Could Partner ID be added to the provider

### ISSUE THREAD

**Issue by RAWRitsCloud** [Azure/terraform-provider-azapi#138]
Hey

The other Azure providers (AzureRM and AzureAD) allow us to place a partner ID in the provider to attribute the usage. Could we do the same thing with AzAPI?

Thanks
James

**Comment by ms-henglu** [comment]
Hi @RAWRitsCloud ,

Thank you for opening this issue! I'll add this feature in the next release.

**Comment by ms-henglu** [comment]
Hi @RAWRitsCloud ,

This feature has been released in v0.4.0, would you please give it a try? Thanks!

**Comment by RAWRitsCloud** [comment]
Hey @ms-henglu 

I've tested this afternoon and it accepts the variable, I will check with the team that can see the partner portal to see if it translated through OK.

Thanks
James
