### ISSUE TITLE
parent_id limitations in azapi_resource

### ISSUE THREAD

**Issue by daveneeley** [Azure/terraform-provider-azapi#143]
The `azapi_resource` documentation states that "For child level resources, the parent_id should be the ID of its parent resource, for example, subnet resource's parent_id is the ID of the vnet."

I attempted to provide the ID of an `azurerm_function_app_slot` resource, to retrieve [host-level function keys][1] by appending `/host/default/listkeys` to the resource ID.

```
data "azapi_resource" "staging_slot_default_keys" {
  name    = "/host/default/listkeys"
  depends_on = [azurerm_function_app_slot.staging]
  parent_id  = "azurerm_function_app_slot.staging.id
  type = "Microsoft.Web/sites@2021-02-01"
  response_export_values = ["functionKeys.default"]
}
```

The ID of the `azurerm_function_app_slot` resource already has the provider type in it, but the example above creates an invalid URL by appending the parsed resource type and the object name to the parent_id  (`parent_id/parsed resource type/name`). 

Related #134 

[1]: https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/list-host-keys-slot

**Comment by daveneeley** [comment]
The workaround is to set `parent_id` to the resource group id and build the name by hand.

data "azapi_resource" "backend_function_staging_default_keys" {
  name = "${azurerm_function_app.production.name}/slots/${azurerm_function_app_slot.staging.name}/host/default/listkeys"
  parent_id = data.azurerm_resource_group.this.id
  type      = "Microsoft.Web/sites@2021-02-01"
  response_export_values = ["functionKeys.default"]
}

**Comment by ms-henglu** [comment]
Hi @daveneeley ,

Thank you for opening this issue.

The `azapi_resource` data source is designed to read an existing resource instead of executing a resource function like `listKeys`. But we're working on this case, https://github.com/Azure/terraform-provider-azapi/issues/57, this feature will be released in next release.

**Comment by daveneeley** [comment]
Thank you for your fast response! How does one determine from the REST API documentation that the `type` should be `Microsoft.Web/sites/slots/host@2022-03-01`?

Could the example be more like this?

```
resource "azurerm_app_service_slot" "staging" {
  // ...details...
}

data "azapi_operation" "op" {
  resource_id = azurerm_app_service_slot.staging.id
  operation = "host/default/listkeys"
  api_version = "2022-03-01"
}
```

The provider is already present in the resource_id, only the api version is essential. The reference to `host/default` may be part of the actual resource but as a consumer of the module it's an implementation detail to me. If all we're doing is validating that we have a good resource id before we construct a URL, this seems like it would work and be simpler to write.

**Comment by ms-henglu** [comment]
Hi @daveneeley

This indeed is a tricky one, `Microsoft.Web/sites/slots/host@2022-03-01` is not a valid resource type like others which support CRUD. 

Based on azure resource type naming convention:
resource id follows this pattern: `{scope}/providers/{providerNamespace}/{type/name pairs}`

For example: `{scope}/providers/{providerNamespace}/{typeA}/{nameA}/{typeB}/{nameB}`

Then its Fully-Qualified Resource Type : `{providerNamespace}/{typeA}/{typeB}`


> The provider is already present in resource_id, only api_version would be needed. The reference to host/default may be part of the actual resource but as a consumer of the module it's an implementation detail to me. If all we're doing is validating that we have a good resource_id before we construct a URL, this seems like it would work and be simpler to write.

Thanks for the good suggestion! The reason we have a type like `azure_resource_type@api_version`, is to align with bicep and ARM templates. And with this type, it's able to provide rich language support like auto-complete for available operations. 

Another way to make it simpler is using data source `azapi_resource` to build the id.

```

resource "azurerm_app_service_slot" "staging" {
  // ...details...
}

data "azapi_resource" "host" {
  type = "Microsoft.Web/sites/slots/host@2022-03-01"
  parent_id = azurerm_app_service_slot.staging.id
  name = "default"
}

data "azapi_operation" "op" {
  type = "Microsoft.Web/sites/slots/host@2022-03-01"
  resource_id = data.azapi_resource.host.id
  operation = "listkeys"
}

```

**Comment by daveneeley** [comment]
Azure CLI has a similar concept, wherein an "action" and a list of ids can be provided.

https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-invoke-action

**Comment by ms-henglu** [comment]
Hi @daveneeley ,

The [azapi_resource_action](https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource_action) has been released in azapi 0.5.0, would you please give it a try? And there's an example:
https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_default_host_keys/main.tf

**Comment by daveneeley** [comment]
Thank you! I tried this out based on the example and received a couple "Error: `resource_id` and `type` are not matched" errors. I see a few recent reports of that error for different uses cases. I still don't quite grasp how ARM and Bicep use provider types in practice. Is there a debug flag I can turn on to see more detail?

```
data "azapi_resource_action" "function_app_staging_list_keys" {
  //type                   = "Microsoft.web/sites/slots@2022-03-01"
  type                   = "Microsoft.web/sites/slots/staging@2022-03-01"
  resource_id            = azurerm_function_app_slot.function_app_staging.id
  action                 = "host/default/listkeys"
  response_export_values = ["*"]
}

data "azapi_resource_action" "function_app_production_list_keys" {
  type                   = "Microsoft.web/sites@2022-03-01"
  resource_id            = azurerm_function_app.function_app_production.id
  action                 = "host/default/listkeys"
  response_export_values = ["*"]
}
```

**Comment by ms-henglu** [comment]
HI @daveneeley ,

This error is always about casing, please notice the type should be `Microsoft.Web/sites/slots@2022-03-01`. Now we have [reference document](https://review.docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/slots?branch=main&pivots=deployment-language-terraform) to help you input a correct type. And the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=azapi-vscode.azapi) can also help.

I'll improve the error message in the next release, it's kind of misleading.

Thanks!

**Comment by daveneeley** [comment]
Thank you! That was exactly the issue. This is working great now.
