### ISSUE TITLE
Feature request: Allow appending properties from existing resource

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#145]
Hi,

In the use case of deploying virtual networks using AzAPI, but not deploying subnets. Any existing subnet resources are deleted when updating the virtual network, e.g. updating the tags.

This is not specifically an AzAPI problem, it is more the behaviour of the Azure network resource provider.

```terraform
resource "azapi_resource" "vnet" {
  parent_id = "/subscriptions/00000000-0000-0000-000000000000/resourceGroups/azapitest"
  type = "Microsoft.Network/virtualNetworks@2021-08-01"
  name = "vnet"
  location = "northeurope"
    body = jsonencode({
    properties = {
      addressSpace = {
        addressPrefixes = [
          "10.0.0.0/16"
        ]
      }
    }
  })
  tags = {
    deployedBy = "azapitest2"
  }
}
```

What I would like to do is propose a feature that takes a JSON path from the existing resource, if it exists, then appends it to the body of the PUT request.

Could be implemented in a similar way to `response_export_values`, in that a list of JSON keys can be provided for appending to the PUT request.

The order of events would be:

- If resource exists...
- Perform a GET
- for each of the supplied JSON paths, extract the values from the GET request body
- Append said values to the prepared PUT body, if they do not already exist.

I see that much of the JSON path logic is already present in `json.go`. I would be prepared to give this a go with a PR if you think it's a good idea?

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thanks for opening this issue!

If I understands this correctly, this can be done with `azapi_update_resource`, more info can be found [here](https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_update_resource).

Here's a full example:
```hcl
resource "azurerm_resource_group" "test" {
  name     = "henglu75vnet"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "henglu75vnet"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.2.0/24"
  }

  lifecycle {
    // azapi_update_resource.test adds tags on this resource, so we must ignore the diff
    ignore_changes = [tags]
  }
}

resource "azapi_update_resource" "test" {
  type        = "Microsoft.Network/virtualNetworks@2022-01-01"
  resource_id = azurerm_virtual_network.test.id
  body = jsonencode({
    tags = {
      label = "prod"
    }
  })
}

```

**Comment by matt-FFFFFF** [comment]
Hi @ms-henglu 

I don't think I explained myself clearly, sorry.

In this scenario, a team A is deploying an azure virtual network using AzAPI.

After the virtual network is deployed, team B deploys the subnets to the same vnet. Team B is not using AzAPI, they are using another deployment method (it is not important which one).

The issue we then face is that team A needs to update the virtual network, e.g. the tags. When they do this all of the subnets are deleted because they are not defined in the AzAPI body. This is a well known behaviour with the Azure network resource provider.

In the AzureRM provider, they get the existing subnets and append the properties to the request:

https://github.com/hashicorp/terraform-provider-azurerm/blob/a30edf1fc34c5474a4a870c1599c2e0dee180dcb/internal/services/network/virtual_network_resource.go#L342

When I am proposing is similar, add the ability to append the PUT body with specific JSON values stored in ARM. E.g. in this example I would specify something like this:

```terraform
resource "azapi_resource" "vnet" {
  parent_id = "/subscriptions/00000000-0000-0000-000000000000/resourceGroups/azapitest"
  type = "Microsoft.Network/virtualNetworks@2021-08-01"
  name = "vnet"
  location = "northeurope"
    body = jsonencode({
    properties = {
      addressSpace = {
        addressPrefixes = [
          "10.0.0.0/16"
        ]
      }
    }
  })
  # This would perform a GET request on the resource
  append_existing_values = [
    "properties.subnets"
  ]
}
```

**Comment by matt-FFFFFF** [comment]
This issue can be simulated like this:

1. Apply the below configuration
2. Change the tag of the virtual network and run apply again
3. You will find that the subnet has been deleted.

Note: this is not explicitly about changing the tag property, it is about a situation where different teams manage the virtual network and the subnet resources.

```terraform
resource "azapi_resource" "vnet" {
  parent_id = "/subscriptions/00000000-0000-0000-000000000000/resourceGroups/azapitest"
  type = "Microsoft.Network/virtualNetworks@2021-08-01"
  name = "vnet"
  location = "northeurope"
    body = jsonencode({
    properties = {
      addressSpace = {
        addressPrefixes = [
          "10.0.0.0/16"
        ]
      }
    }
  })
  tags = {
    deployedBy = "azapitest"
  }
}

resource "azapi_resource" "vnet_subnet" {
  parent_id = azapi_resource.vnet.id
  type = "Microsoft.Network/virtualNetworks/subnets@2021-08-01"
  name = "vnet-subnet"

  body = jsonencode({
    properties = {
      addressPrefix = "10.0.1.0/24"

    }
  })
}
```

**Comment by matt-FFFFFF** [comment]
Hi @ms-henglu,

Thanks for the suggestion - in this case we cannot use AzureRM because we are deploying a resource to a newly created subscription. Something that AzureRM cannot do because of its dependency on having a provider declaration with a subscription id.

We are creating the subscription and the virtual network in the same apply, hence using AzAPI to create the virtual network.

**Comment by ms-henglu** [comment]
@matt-FFFFFF - Got it! I have a hacky workaround for this case 😆 

TeamA can use `azapi_resource` to create vnet and add `ignore_changes = [body]`, then it will only be responsible for creating the vnet, then use `azapi_update_resource` to update it.

**Comment by matt-FFFFFF** [comment]
@ms-henglu I have raised a draft PR, it can be improved but shows an implementation...

**Comment by matt-FFFFFF** [comment]
> @matt-FFFFFF - Got it! I have a hacky workaround for this case 😆
> 
> TeamA can use `azapi_resource` to create vnet and add `ignore_changes = [body]`, then it will only be responsible for creating the vnet, then use `azapi_update_resource` to update it.

Hi @ms-henglu,

I tried this and it works for changes in the body, thank you for your recommendation.

It doesn't work for changes to tags as `azapi_update_resource` does not support tags. So updating the tags in the original `azapi_resource` ends up deleting the subnets that have been created.

Would you be supportive of adding tags support to `azapi_update_resource`?

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF 

> It doesn't work for changes to tags as azapi_update_resource does not support tags. So updating the tags in the original azapi_resource ends up deleting the subnets that have been created.

How about using `ignore_changes = [body, tags]` on the `azapi_resource` to suppress the diff. And you can use `azapi_update_resource` to add tags like the following config:

```hcl
resource "azapi_update_resource" "test" {
  type        = "Microsoft.Network/virtualNetworks@2022-01-01"
  resource_id = azurerm_virtual_network.test.id
  body = jsonencode({
    tags = {
      label = "prod"
    }
  })
}
```
