### ISSUE TITLE
Container App Environment - Failing with vnetConfiguration

### ISSUE THREAD

**Issue by andrewPoland** [Azure/terraform-provider-azapi#152]
I'm attempting to create a Container App Environment with the code below based on the example but with `vnetConfiguration` defined.

```terraform
resource "azapi_resource" "api_managed_environment" {
  name      = local.app_environment_name
  parent_id = data.azurerm_resource_group.environment_resource_group.id
  type      = "Microsoft.App/managedEnvironments@2022-03-01"
  location  = local.location

  body = jsonencode({
    properties = {
      vnetConfiguration = {
        internal               = true
        infrastructureSubnetId = local.subnet_id
      }
      zoneRedundant = false
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.environment_logs.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.environment_logs.primary_shared_key
        }
      }
    }
  })

  ignore_missing_property = true

}
```

When running `terraform apply` the process never completes and eventually times out after 30 minutes.

```
module.module_name.azapi_resource.api_managed_environment: Still creating... [29m31s elapsed]
module.module_name.azapi_resource.api_managed_environment: Still creating... [29m41s elapsed]
module.module_name.azapi_resource.api_managed_environment: Still creating... [29m51s elapsed]
╷
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/000000000-0000-0000-0000-00000000/resourceGroups/rg-name/providers/Microsoft.App/managedEnvironments/cae-name\" / Api Version \"2022-03-01\")": context deadline exceeded
│ 
│   with module.module_name.azapi_resource.api_managed_environment,
│   on modules\container-app\main.tf line 38, in resource "azapi_resource" "api_managed_environment":
│   38: resource "azapi_resource" "api_managed_environment" {
│ 
╵
```

Looking in the azure portal the resource gets created successfully despite the error. It seems like the call to create the resource succeeds but the process for polling is failing to recognize the container app environment was created when it's behind a vnet. 
 
I was also able to import the state of the generated environment and the configuration in the state file matched my expectations. Any subsequent update to the resource resulted in a similar experience but with the slightly updated text 

```
module.module_name.azapi_resource.api_managed_environment: Still modifying... [id=/subscriptions/00000000-0000-0000-0000-...edEnvironments/cae-name, 7m30s elapsed]
```

I also confirmed that by removing the vnet configuration I was able to generate the container app environment with the resource taking ~1 minute to create. 

Is there something I'm missing or is this a current limitation with the API?

**Comment by andrewPoland** [comment]
Further investigation shows this is unrelated to azapi.

https://github.com/microsoft/azure-container-apps/issues/267

Calling the GET method on azure rest api shows the container app environment is in a `Waiting` state despite appearing like it completed in the portal. 

```json

{
...
 "properties": {
    "provisioningState": "Waiting",
    ...
 }
}        
```

**Comment by ms-henglu** [comment]
Hi @andrewPoland,

Thank you for opening this issue and the investigation!

Yes, the `azapi` will wait until the `provisioningState` becomes `Succeeded`.

**Comment by andrewPoland** [comment]
In my specific case the creation was failing due to the subnet being associated with a custom route table with a defined route of 0.0.0.0. The linked issue links to issue 227 that mentions this as a known issue that they are actively looking to resolve.  

Removing the association between the subnet and the route table allowed me to successfully finish creating the environment within the vnet.

**Comment by ms-henglu** [comment]
Since this is not an issue with azapi provider, I'll close this issue, but feel free to reopen it.
