### ISSUE TITLE
Add docs on usage in a module

### ISSUE THREAD

**Issue by vermegi** [Azure/terraform-provider-azapi#156]
When using the azapi provider inside a local module you need in the main.tf file: 

terraform {
  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = "0.4.0"
    }
  }
}

provider "azapi" {
}

And in the used module as well: 

terraform {
  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = "0.4.0"
    }
  }
}

I this is not indicated Terraform gives an error message on hashicorp/azapi provider.

**Comment by ms-henglu** [comment]
Hi @vermegi ,

Thank you for opening this issue!

Yes, this block is required, because `azapi` is not an **official** provider which means it's not owned by HashiCorp.

**Comment by ms-henglu** [comment]
I'll close this issue, but feel free to reopen it.
