### ISSUE TITLE
Add property that will contain a list of properties that will force delete and recreate.

### ISSUE THREAD

**Issue by grayzu** [Azure/terraform-provider-azapi#161]

**Comment by grayzu** [comment]
Document using the builtin Terraform lifecycle property:

https://www.terraform.io/language/meta-arguments/lifecycle#replace_triggered_by

**Comment by grayzu** [comment]
@ms-henglu Can we get this information from the schema or type information and streamline this instead of requiring the use of the Terraform Lifecycle property?

**Comment by ms-henglu** [comment]
@grayzu  - Technically yes, to achieve this, we need to export this information based on swagger's `x-ms-mutablity` annotations into bicep types. But not all of the force-new-property have correct `x-ms-mutablity`.

**Comment by rikunarhi-cloud2** [comment]
What is the status of this? This is needed with the image templates.
