### ISSUE TITLE
Unable to list publishing credentials for Microsoft.Web/sites/config

### ISSUE THREAD

**Issue by maurice-freitag** [Azure/terraform-provider-azapi#175]
Hi everyone,

I'm trying to list the scm uri of a function app to use it as a container registry web hook. I got this working with the CLI, now I'm trying to move it to my terraform deployment. 

In the CLI this would translate to 
```
az functionapp deployment container config `
        -g $resourceGroupName `
        -n $functionAppName `
        --enable-cd `
        --query CI_CD_URL `
        -o tsv
```

The corresponding REST method:
```
https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Web/sites/{{functionAppName}}/config/publishingcredentials/list?api-version=2022-03-01
```
which produces an output like this:
```json
{
    "id": "xxx",
    "name": "xxx",
    "type": "Microsoft.Web/sites/publishingcredentials",
    "location": "xxx",
    "properties": {
        "name": null,
        "publishingUserName": "xxx",
        "publishingPassword": "xxx",
        "publishingPasswordHash": null,
        "publishingPasswordHashSalt": null,
        "metadata": null,
        "isDeleted": false,
        "scmUri": "https://{{functionAppName}}:{{password}}@{{functionAppName}}.scm.azurewebsites.net" <- what I want
    }
}
```

What I'm targeting is the type "Microsoft.Web/sites/config/publishingcredentials" which as far as I can tell is currently not directly supported by azapi. 

I tried setting up my resource like this 
```
resource "azapi_resource_action" "scm-uri" {
  type = "Microsoft.Web/sites/config@2022-03-01"
  method = "POST"
  action = "publishingcredentials/list"
  response_export_values = ["*"]
  resource_id = "/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Web/sites/{{functionAppName}}"
}
```
However it produces this error:
```
azapi_resource_action.scm-uri: Creating...
╷
│ Error: `resource_id` and `type` are not matched
│
│   with azapi_resource_action.scm-uri,
│   on main.tf line 33, in resource "azapi_resource_action" "scm-uri":
│   33: resource "azapi_resource_action" "scm-uri" {
│
╵
```

What am I missing here? Is this currently not supported?

**Comment by ms-henglu** [comment]
Hi @maurice-freitag ,

Thank you for taking time to open this issue! And the details are useful.

The `resource_id` needs to be matched with the `type`, hope the following config helps :)

```hcl
resource "azapi_resource_action" "scm-uri" {
  type = "Microsoft.Web/sites/config@2022-03-01"
  method = "POST"
  action = "list"
  response_export_values = ["*"]
  resource_id = "/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Web/sites/{{functionAppName}}/config/publishingcredentials"
}

```

**Comment by maurice-freitag** [comment]
> Hi @maurice-freitag ,
> 
> Thank you for taking time to open this issue! And the details are useful.
> 
> The `resource_id` needs to be matched with the `type`, hope the following config helps :)
> 
> ```terraform
> resource "azapi_resource_action" "scm-uri" {
>   type = "Microsoft.Web/sites/config@2022-03-01"
>   method = "POST"
>   action = "list"
>   response_export_values = ["*"]
>   resource_id = "/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Web/sites/{{functionAppName}}/config/publishingcredentials"
> }
> ```

Thanks for the quick reply! Makes total sense and seems to be working now. One of those 'extremely obvious in hindsight' issues 😅 Thank you!

**Comment by ms-henglu** [comment]
Hi @maurice-freitag - Sorry I forgot to mention, if you want to perform action that only reads information from existing resource, it's better to use `azapi_resource_action` data source, because it will always load the latest data.

```hcl
data "azapi_resource_action" "scm-uri" {
  type = "Microsoft.Web/sites/config@2022-03-01"
  method = "POST"
  action = "list"
  response_export_values = ["*"]
  resource_id = "/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Web/sites/{{functionAppName}}/config/publishingcredentials"
}
```
