### ISSUE TITLE
feature request: support locks for r/azapi_resource_action

### ISSUE THREAD

**Issue by t3mi** [Azure/terraform-provider-azapi#178]
This is a feature request to add locks support for the `azapi_resource_action` resource so that multiple actions could be handled successfully against single resource.

**Comment by ms-henglu** [comment]
Hi @t3mi ,

Thank you for taking time to report this issue!

I'll add this feature in the next release. Would you please share me more details about your case? Thanks!

**Comment by t3mi** [comment]
I'm trying to automatically approve private endpoint connection but its creation is done in the Azure backend and sometimes results in creation of only one endpoint for multiple "creation" calls. So current behavior without the locks results in the error for second approval command:
```hcl
Operation PutPrivateEndpointConnectionOperation (<GUID>) was canceled and superseded by operation PutPrivateEndpointConnectionOperation (<GUID>).
```
