### ISSUE TITLE
Error: resource_id and type are not matched - case of type validated

### ISSUE THREAD

**Issue by ggomes-agc** [Azure/terraform-provider-azapi#185]
Having an issue deploying the following code with azapi v 0.5.0  and terraform 0.14.7( also tried 1.2.9). 
I have installed the azapi extensions for vscode and verified case sensitivity for type. 
This code does successfully deploy the role assignment at the proper scope.  However, it errors out with the below error message, and taints the resource in the terraform state file.

Error: `resource_id` and `type` are not matched
│
│   with azapi_resource.api-group,
│   on cbs.tf line 96, in resource "azapi_resource" "api-group":
│   96: resource "azapi_resource" "api-group" {

resource "azapi_resource" "api-group" {
  name                      = "e50f7f08-1197-1234-a3ef-123c0520da31"
  parent_id                 = "providers/Microsoft.Marketplace"
  type                      = "Microsoft.Authorization/roleAssignments@2015-07-01"
  body = jsonencode({
    properties = {
      roleDefinitionId = "/providers/Microsoft.Authorization/roleDefinitions/dd920d6d-f481-47f1-b461-f338c46b2d9f",
      principalId = "omitted UUID of SPN object"
      }
  })
}

Note: If I use the Azure API explorer at https://docs.microsoft.com/en-us/rest/api/authorization/role-assignments/create-by-id?tabs=HTTP#code-try-0 i can implement with these values and it is successful. 

Any ideas on how to resolve this issue ?

**Comment by ms-henglu** [comment]
Hi @ggomes-agc ,

Thank you for taking time to report this issue!

I guess the `parent_id` should be `/providers/Microsoft.Marketplace`. Would you please give it a try?

And this resource is also supported in `azurerm` provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment

**Comment by ggomes-agc** [comment]
That worked ! Thanks very much. 

Just an FYI on the azurerm solution. I had problems with that ( https://github.com/hashicorp/terraform-provider-azurerm/issues/18387) so decided to use azapi. 

resource "azapi_resource" "api-group" {
  name                      = "e50f7f08-1197-1234-a3ef-123c0520da32"
  parent_id                 = "/providers/Microsoft.Marketplace"
  type                      = "Microsoft.Authorization/roleAssignments@2015-07-01"

  body = jsonencode({
    properties = {
      roleDefinitionId = "/providers/Microsoft.Authorization/roleDefinitions/dd920d6d-f481-47f1-b461-f338c46b2d9f",
      principalId = azuread_service_principal.spn.id
      }
  })

}
