### ISSUE TITLE
Can't use client_certificate_password

### ISSUE THREAD

**Issue by MichalSino** [Azure/terraform-provider-azapi#187]
I wanted to use azapi 0.5.0 provider with config:
provider "azapi" {
  subscription_id                   = var.subscription
  client_id                              = var.acredentials_clientid
  client_certificate_path         = "cert_file"
  client_certificate_password = "certificate_password"
  tenant_id                             = var.tenant
}

but I get:

Error: Unsupported argument

  on providers.tf line 46, in provider "azapi":
  46:   client_certificate_password = "credentials_password"

An argument named "client_certificate_password" is not expected here.

Is it possible to add it?

**Comment by ms-henglu** [comment]
Hi @MichalSino ,

Thank you for taking time to report this issue!

This feature has been supported in the sdk, we'll add it in the next release.

**Comment by MichalSino** [comment]
Hi @ms-henglu ,
ok. Thanks for reply. Do you know the time of releasing new version?

**Comment by ms-henglu** [comment]
Hi @MichalSino - I believe it should be around the end of September.

**Comment by MichalSino** [comment]
ok, thanks

**Comment by ms-henglu** [comment]
Hi @MichalSino - Sorry that I just noticed this feature is in a pre-release, sadly we have to wait until it's officially supported in azidentity v1.2.0.

refs: https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fazidentity%2Fv1.2.0-beta.1

**Comment by MichalSino** [comment]
@ms-henglu do we have any new notice? I think https://github.com/Azure/azure-sdk-for-go/pull/18329 is already merged, so can you implement it in AzAPI

**Comment by gavhooper** [comment]
Is there any update on this? I am facing the same issue
