### ISSUE TITLE
Root resource was present, but now absent for Microsoft.Web/sites/virtualNetworkConnections@2022-03-01

### ISSUE THREAD

**Issue by lovebikso** [Azure/terraform-provider-azapi#188]
Hi team, 

Hope you're doing well. 
Within using of azapi deployment, I want to add Vnet integration for my web apps. To do that, I'm using the resource Microsoft.Web/sites/virtualNetworkConnections@2022-03-01 and I'm always getting the error: 

`│ When applying changes to
│ module.AppServiceFront.azapi_resource.AzureAppServiceUiVnetConnection,
│ provider "provider[\"registry.terraform.io/azure/azapi\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.`

My terraform code: 
`resource "azapi_resource" "AzureAppServiceUiVnetConnection" {
  type = "Microsoft.Web/sites/virtualNetworkConnections@2021-03-01"
  name = "test"
  parent_id = azapi_resource.appService.id
  body = jsonencode({
    properties = {
      vnetResourceId = var.vnetResourceId
      isSwift = true
    }
  })
  depends_on = [
    azapi_resource.appService
  ]
}`

Could you take a look at this issue, please?

**Comment by ms-henglu** [comment]
Hi @lovebikso ,

Thank you for taking time to report this issue!

This looks like a bug on the API side, I'll create an issue to track it: https://github.com/Azure/azure-rest-api-specs/issues/20765

And I found some similar asks about this questions:
https://stackoverflow.com/questions/54534924/arm-template-for-to-configure-app-services-with-new-vnet-integration-feature
https://github.com/MicrosoftDocs/azure-docs/issues/20348

It seems the following configuration works, hope it can help you.
```hcl
resource "azapi_update_resource" "test" {
  type      = "Microsoft.Web/sites/config@2022-03-01"
  parent_id = azurerm_linux_function_app.example.id
  name      = "virtualNetwork"
  body = jsonencode({
    properties = {
      subnetResourceId = azurerm_subnet.example.id
      swiftSupported   = true
    }
  })
}
```

**Comment by ms-henglu** [comment]
I'll close this issue since there's no response, please feel free to reopen it, thanks!
