### ISSUE TITLE
Allow to set custom http headers

### ISSUE THREAD

**Issue by hmettler** [Azure/terraform-provider-azapi#192]
Some Azure API calls require to set custom http headers.
One example is https://learn.microsoft.com/en-us/rest/api/storagerp/blob-containers/lock-immutability-policy?tabs=HTTP
This API call requires to set a header called "If-Match" that is set to the eTag of the existing policy that should be updated.
It would be great if you could allow to set these additional http headers.

**Comment by gofinch** [comment]
Another example of API calls which requires arguments in http headers: 
- https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/create
- https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update

**Comment by ms-henglu** [comment]
Hi all,

Apologize for late update, this feature has been supported in the v2.0.0-beta, all azapi resources/data sources support custom http headers. Please give it a try. Thanks.

refs: https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/2.0-upgrade-guide#headers-and-query-parameters-support
