### ISSUE TITLE
Issues with Container App

### ISSUE THREAD

**Issue by jedi0606** [Azure/terraform-provider-azapi#193]
Hello. I'm trying to deploy container app environment with vnet configuration and storage, but it works strangely. 
Here is my code:
`resource "azurerm_resource_group" "rg" {
  name     = "${var.aca_name}-rg"
  location = var.location
}

resource "azurerm_log_analytics_workspace" "loganalytics" {
  name                = "${var.aca_name}-la"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_storage_account" "aci_storage" {
  name                     = "fdllkjhgdhhder"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = "West Europe"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
}
resource "azurerm_storage_share" "container_share" {
  name                 = "aci-data"
  storage_account_name = azurerm_storage_account.aci_storage.name
  quota                = 100
  depends_on = [
    azurerm_storage_account.aci_storage
  ]
}

resource "azurerm_virtual_network" "virtual_network" {
  name                = "${var.aca_name}-vnet"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  address_space       = [var.network_address_space]
}

resource "azurerm_subnet" "aca_subnet" {
  name                 = var.aca_subnet_address_name
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.virtual_network.name
  address_prefixes     = [var.aca_subnet_address_prefix]
}

resource "azapi_resource" "containerapp_environment" {
  type      = "Microsoft.App/managedEnvironments@2022-03-01"
  name      = "${var.aca_name}acae"
  parent_id = azurerm_resource_group.rg.id
  location  = azurerm_resource_group.rg.location

  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.loganalytics.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.loganalytics.primary_shared_key
        }
      }
      vnetConfiguration = {
        internal               = true
        infrastructureSubnetId = azurerm_subnet.aca_subnet.id
        dockerBridgeCidr       = "10.2.0.1/16"
        platformReservedCidr   = "10.1.0.0/16"
        platformReservedDnsIP  = "10.1.0.2"
      }
    }
  })
  depends_on = [
    azurerm_virtual_network.virtual_network, azurerm_storage_account.aci_storage
  ]
  ignore_missing_property = true
  ignore_casing = true
  schema_validation_enabled = false
}

resource "azapi_resource" "symbolicname" {
  type = "Microsoft.App/managedEnvironments/storages@2022-03-01"
  name = "string"
  parent_id = azapi_resource.containerapp_environment.id
  body = jsonencode({
    properties = {
      azureFile = {
        accountName = azurerm_storage_account.aci_storage.name
        shareName = azurerm_storage_share.container_share.name
      }
    }
  })
}

resource "azapi_resource" "containerapp" {
  type      = "Microsoft.App/containerapps@2022-03-01"
  name      = "app01acae"
  parent_id = azurerm_resource_group.rg.id
  location  = azurerm_resource_group.rg.location

  body = jsonencode({
    properties = {
      managedEnvironmentId = azapi_resource.containerapp_environment.id
      configuration = {
        ingress = {
          external : true,
          targetPort : 80
        },

      }
      template = {
        containers = [
          {
            image = "docker.io/cloudflare:cloudflared"
            name  = "simple-hello-world-container"
            resources = {
              cpu    = 0.25
              memory = "0.5Gi"
            }
          }
        ]
        scale = {
          minReplicas = 1,
          maxReplicas = 3
        }
      }
    }

  })
  ignore_missing_property = true
  depends_on = [
    azapi_resource.containerapp_environment
  ]
}

`

The message during terraform apply is:
`Error: creating/updating "Resource: (ResourceId \"/subscriptions/10071b3d-8531-45e2-bc9c-699f6331a09b/resourceGroups/conttestfinal-rg/providers/Microsoft.App/managedEnvironments/conttestfinalacae\" / Api Version \"2022-03-01\")": GET https://management.azure.com/subscriptions/10071b3d-8531-45e2-bc9c-699f6331a09b/providers/Microsoft.App/locations/uksouth/managedEnvironmentOperationStatuses/e00196be-9113-4684-9117-52738ca9fd2b
│ --------------------------------------------------------------------------------
│ RESPONSE 200: 200 OK
│ ERROR CODE: OperationFailed
│ --------------------------------------------------------------------------------
│ {
│   "id": "/subscriptions/10071b3d-8531-45e2-bc9c-699f6331a09b/providers/Microsoft.App/locations/uksouth/managedEnvironmentOperationStatuses/e00196be-9113-4684-9117-52738ca9fd2b",
│   "name": "e00196be-9113-4684-9117-52738ca9fd2b",
│   "status": "Failed",
│   "error": {
│     "code": "OperationFailed",
│     "message": "ErrorCode: ManagedEnvironmentResourceDisallowedByPolicy, Message: Fail to create managed environment because creation of required resources was disallowed by policy, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail."
│   },
│   "startTime": "2022-09-28T18:21:31.6995104"
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with azapi_resource.containerapp_environment,
│   on main.tf line 45, in resource "azapi_resource" "containerapp_environment":
│   45: resource "azapi_resource" "containerapp_environment" {`

But, the Container App environment itself is created, with vnet configuration, but without storage, and consequently container app is not created.
If I run "terraform plan" again it says that the resource containerapp_environment is already created and is not managed by Terraform. Can you please advise something?

**Comment by epomatti** [comment]
@jedi0606 in my case I reached my limit due to Azure being a pain as always and not being able to delete a Container App for some unknown reason. For another dumb reason AzApi is incapable of returning the proper error message. It's one error on top of another.

Try calling directly the [REST API](https://learn.microsoft.com/en-us/rest/api/containerapps/managed-environments/create-or-update?tabs=HTTP) and see what error the API returns:

In my case it was this message:

```json
{
  "code": "MaxNumberOfRegionalEnvironmentsInSubExceeded",
  "message": "The subscription '00000000-0000-0000-0000-000000000000' cannot have more than 1 environments in East US."
}
```

This is my original error issue for reference: https://github.com/microsoft/azure-container-apps/issues/429

Also try formatting your issue properly.
