### ISSUE TITLE
azapi_resource for container_apps is not idempotent regarding order of identities

### ISSUE THREAD

**Issue by BeTheFlow95** [Azure/terraform-provider-azapi#196]
When multiple user assigned managed identities are given to the container_app, the order matters.
When you initially add the identities in an arbitrary order they will be added without a problem.
If azure stores them internally in a different order terraform will change the order in the next `terraform apply` run.
(Which will then be reversed by azure again)

In our case this leads to a problem in an application_gateway from the azurerm provider since there is also
a bug in the provider regarding the ordering of its arguments.

We avoided this problem by passing the identities to the container_app as a list instead of a map and by
recreating the same order of the identities in this list.
![tf-example](https://user-images.githubusercontent.com/47504883/194315511-f801d031-9896-4fe1-a6ab-81c9b66ca3b9.png)

**Comment by ms-henglu** [comment]
Hi @BeTheFlow95 ,

Thank you for taking time to open this issue!

I think it makes sense, that the order of the keys in a map is not fixed, but the list's is. I guess that's why azure doesn't store the identities in a correct order if uses a map.

**Comment by BeTheFlow95** [comment]
Yes, I can get why terraform works as it does regarding maps/lists, but I don't get why terraform can't figure out that the identities are still the same and only the order changed. I would expect that if I apply a second time without changing anything, that the result would be: `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Finishing: Terraform Apply` which it doesn't

**Comment by ms-henglu** [comment]
I'll close this issue, but feel free to reopen it if there's any question.
