### ISSUE TITLE
Container apps : missing ingress property "Limited to Vnet"

### ISSUE THREAD

**Issue by MonsieurTib** [Azure/terraform-provider-azapi#198]
I'm trying to create a container app limited to Vnet only. 
[Ingress property](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-03-01/containerapps?pivots=deployment-language-terraform#ingress-2) does not expose a property "Limited To Vnet". 
When "External" property is set to false, the container ingress is "Limited to Container Apps environement" which can not be reached from my Azure Application Gateway.

**Comment by ms-henglu** [comment]
Hi @MonsieurTib ,

Thank you for taking time to report this issue, and apologize for late response.

It seems this feature is not exposed by its public API.  So it could not be supported by azapi provider.

**Comment by ms-henglu** [comment]
Hi @MonsieurTib ,

Sorry for late response, I guess it could be configured by https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-03-01/containerapps?pivots=deployment-language-terraform#ingress-2.

refs: https://github.com/microsoft/azure-container-apps/issues/458#issuecomment-1282593280

**Comment by ms-henglu** [comment]
Close this issue as it's resolved, but feel free to reopen it if there's any question.
