### ISSUE TITLE
Add a "Forget" feature, instead of always sending DELETE

### ISSUE THREAD

**Issue by mariussm** [Azure/terraform-provider-azapi#199]
In trying to use the PIM APIs, more specifically the Microsoft.Authorization/roleEligibilityScheduleRequests@2020-10-01-preview resource type, everything works fine when creating this request. However, it is now possible to delete them from Azure - and this is by design. The problem arises when removing the resource from Terraform, where AzAPI will always send "DELETE" to the resource, causing issues:

│ Error: deleting "Resource: (ResourceId \"/subscriptions/aaaaaaaa-7c00-4cf1-972e-ec150e322282/resourceGroups/testpim123/providers/Microsoft.Authorization/roleEligibilityScheduleRequests/aaaaaaaa-db0d-b9f2-141f-26bc17516ed8\" / Api Version \"2020-10-01-preview\")": DELETE https://management.azure.com/subscriptions/aaaaaaaa-7c00-4cf1-972e-ec150e322282/resourceGroups/testpim123/providers/Microsoft.Authorization/roleEligibilityScheduleRequests/aaaaaaaa-db0d-b9f2-141f-26bc17516ed8
│ --------------------------------------------------------------------------------
│ RESPONSE 405: 405 Method Not Allowed
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "message": "The requested resource does not support http method 'DELETE'."
│ }
│ --------------------------------------------------------------------------------

I propose an additional property on the azapi_resource - "do_not_send_delete" = true or "forget_instead_of_delete" = true, where when this property is true, the "DELETE" request is simply not sent to Azure, but the resource is destroyed Terraform side anyway.

**Comment by mariussm** [comment]
Issue https://github.com/Azure/terraform-provider-azapi/issues/197 is related to this

**Comment by ms-henglu** [comment]
Hi @mariussm ,

Thank you for taking time to report this issue!

We'll think about the feature request and thank you for the proposal. Meanwhile, I have a workaround for it:

`azapi_resource_action` is more flexible, and when remove this resource from terraform configuration, no actions will be taken.
```hcl
resource "azapi_resource_action" "test" {
  type        = "Microsoft.Authorization/roleEligibilityScheduleRequests@2020-10-01-preview"
  resource_id = "/subscriptions/aaaaaaaa-7c00-4cf1-972e-ec150e322282/resourceGroups/testpim123/providers/Microsoft.Authorization/roleEligibilityScheduleRequests/aaaaaaaa-db0d-b9f2-141f-26bc17516ed8"
  method      = "PUT"
  body = jsonencode({
    properties = {
      principalId      = "xxx"
      requestType      = "AdminAssign"
      roleDefinitionId = "xxx"
    }
  })
}
```

**Comment by ms-henglu** [comment]
I'll close this issue, but feel free to reopen it if the workaround doesn't work for you.
