### ISSUE TITLE
azapi_resource_action: Ignore body properties for plan-diff

### ISSUE THREAD

**Issue by jkroepke** [Azure/terraform-provider-azapi#214]
Hi,

I'm using the `azapi_resource_action` resource to run a command in a private AKS cluster.

```terraform
# az aks command invoke --debug -g default -n jok -c "kubectl get pods"
# https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/run-command?tabs=HTTP
resource "azapi_resource_action" "runCommand" {
  type        = "Microsoft.ContainerService/managedClusters@2022-07-01"
  resource_id = data.azurerm_kubernetes_cluster.jok.id
  action      = "runCommand"

  response_export_values = ["*"]

  body = jsonencode({
    command      = "kubectl get pods",
    context      = ""
    clusterToken = var.clusterToken
  })
}

output "command_output" {
  value = jsondecode(azapi_resource_action.runCommand.output)
}
```

The body contains short-living credentials, which results into a plan diff on each terraform run.

It would be nice to have an option to ignore just body properties from plan-diff.

**Comment by ms-henglu** [comment]
Hi @jkroepke ,

Sorry for late update. Now you could use the `lifecycle.ignore_changes` to suppress the plan diff. However, when you want to use the latest token to run the action, you must remove the `lifecycle.ignore_changes` otherwise the latest token won't be used.

**Comment by jkroepke** [comment]
Great! The only issue which is left is issuing a new cluster token
