### ISSUE TITLE
az-api calling too many python modules

### ISSUE THREAD

**Issue by harshavmb** [Azure/terraform-provider-azapi#216]
While performing triage of an issue, I found `az-api` provider calling `python` modules. However, this isn't the case with `azurerm` provider. 

Below are examples of `strace` logs::

`
8751       0.000162 stat("/opt/az/lib/python3.6/site-packages/azure/cli/telemetry", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
8751       0.000216 stat("/opt/az/lib/python3.6", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
8751       0.000167 stat("/opt/az/lib/python3.6/_strptime.py", {st_mode=S_IFREG|0644, st_size=24747, ...}) = 0
8751       0.000328 stat("/opt/az/lib/python3.6/_strptime.py", {st_mode=S_IFREG|0644, st_size=24747, ...}) = 0
8751       0.000162 openat(AT_FDCWD, "/opt/az/lib/python3.6/__pycache__/_strptime.cpython-36.pyc", O_RDONLY|O_CLOEXEC) = 5
`

Below are the count of requests made with & without azapi provider ::

Without azapi provider::

```
harsha@ubuntu:~/terraform-playground/time-sleep-issue$ grep -R "python" strace2.out | wc -l
17
```

With azapi provider::

```
harsha@MUCL104558:~/terraform-playground/time-sleep-issue$ grep -R "python" strace.out | wc -l
3542
```

I'm also attaching [flamegraph](https://github.com/brendangregg/FlameGraph) of system calls extracted from `perf-report` which shows `54.16%` time spent in handling python call modules which isn't the case with `azurerm` provider. 
![kernel-big](https://user-images.githubusercontent.com/10049720/199684884-00fc8637-106a-4688-97f3-9a5bfefdb4c0.svg)

I did a quick dry run, but couldn't find any explicit imports of python modules. I must agree that I'm no software developer who can do deeper checks. 

Could you please look into this in identifying that specific go function which is making these python calls?

**Comment by ms-henglu** [comment]
Hi @harshavmb ,

Thank you for taking time to report this issue! 

I believe that you authenticated to azure with azure cli which is written in python. Would you please try other ways to authenticate to azure to avoid the python calling? 

refs: https://registry.terraform.io/providers/Azure/azapi/latest/docs#authenticating-to-azure

**Comment by harshavmb** [comment]
Hi @ms-henglu ,

Indeed, azapi appears to be invoking `az account get-access-token` via `execve` system call. I had a red herring when I couldn't see these python calls with `azurerm` provider. I do see similar behavior with that as well. 

In the end, my tests appear to be incorrect. Apologies for this question as it's simply wastage of time. 

Thanks again!
