### ISSUE TITLE
"microsoft.insights/components/analyticsItems@2015-05-01" - The requested resource does not support http method 'GET'.

### ISSUE THREAD

**Issue by eissko** [Azure/terraform-provider-azapi#217]
**Terraform Version**
Terraform v1.2.1

**AZAPI version**
    azapi = {
      source = "azure/azapi"
      version = "=1.0.0"
    }

**Affected Resource**
resource "azapi_resource"
"microsoft.insights/components/analyticsItems@2015-05-01"

**Terraform Configuration File**
```hcl
resource "azapi_resource" "create_query_function" {
  count = var.create_query_function ? 1 : 0 
  type = "microsoft.insights/components/analyticsItems@2015-05-01"
  name = "item"
  parent_id = local.app_insights_id # correct app insigth id
  body = jsonencode({
    Properties = {
      functionAlias = "test_function"
    }
    Scope = "Shared"
    Content = <<QUERY
    dependency | where time > ago(1h)
QUERY
    Id = "4d50b39c-ce1f-4566-941d-0fca40dd65da" # randomly generated id
  })
}
```

**Actual Problem**
Terraform apply during refresh making a GET request against azure API for analyticsItem as

 GET https://management.azure.com/subscriptions/subscription-id-redacted/resourceGroups/resource-group-name-redacted/providers/Microsoft.Insights/components/app-insights-name-redacted/analyticsItems/item

And it fails with error:

│ {
│   "Message": "The requested resource does not support http method 'GET'."
│ }

**References**
I followed official Microsoft documentation for creating "analyticsItems" according this page - https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/components/analyticsitems?pivots=deployment-language-terraform#applicationinsightscomponentanalyticsitemproperties-2

**Comment by eissko** [comment]
btw, I used terraform resource azurerm_application_insights_analytics_item instead. and it works correctly.

**Comment by ms-henglu** [comment]
Hi @eissko ,

Thank you for taking time to report this issue!

It seems that this resource type doesn't support GET method to read the resource, instead it uses a list API.

Here's how to manage this resource with `azapi_resource_action` resource, hope it can help you, :)

```hcl
resource "azapi_resource_action" "create_query_function" {
  count     = var.create_query_function ? 1 : 0
  type      = "microsoft.insights/components/analyticsItems@2015-05-01"
  name      = "item"
  parent_id = local.app_insights_id # correct app insigth id
  method = "PUT"
  body = jsonencode({
    Properties = {
      functionAlias = "test_function"
    }
    Scope   = "Shared"
    Content = <<QUERY
    dependency | where time > ago(1h)
QUERY
    Id      = "4d50b39c-ce1f-4566-941d-0fca40dd65da" # randomly generated id
  })
}
```

**Comment by ms-henglu** [comment]
I'll close this issue, but feel free to reopen it if there's further question.
