### ISSUE TITLE
not able to add a body's nested property to ignore_changes

### ISSUE THREAD

**Issue by MonsieurTib** [Azure/terraform-provider-azapi#219]
I'm trying to add a body's nested property to ignore_changes, but got the following error : 'Can't access attributes on a primitive-typed value (string)."

```terraform

resource "azapi_resource" "container_app_api_aval_entity" {
  lifecycle {
    ignore_changes = [ body.properties.template ]
  }
  type = "Microsoft.App/containerApps@2022-03-01"
  parent_id = azurerm_resource_group.portail_rg.id
  name = "xxx"
  location = azurerm_resource_group.portail_rg.location
  identity {
    type = "SystemAssigned"
  }
  
  body = jsonencode({
    properties = {
      managedEnvironmentId = data.azapi_resource.container_app_environment.id 
      configuration = {
        ingress = {
          allowInsecure = true
          targetPort = 80
          external = true          
        },        
      }      
      template = {
          containers = [ 
          { 
            image = "nginxdemos/hello"
            name = "xxxx"
          }
        ]
      }
    }
  })
  #response_export_values = ["properties.ingress.fqdn", "properties.template.containers"]
  response_export_values = ["*"]
}

```

**Comment by IhorHolovatsky** [comment]
I have the same issue, I want to deploy `container_app` with a quickstart image, so later I deploy my own image. 
After I deploy my own image (manually or via CD pipeline), the next `terraform plan` show changes.

Ignoring the `template` block of the body could resolve the issue but in fact, `body` is a string (see that the object we pass to the body is wrapped with `jsonencode`).

So the root question is How we can pass a function to lifecycle `ignore` changes, to determine whether to ignore changes on body string.

**Comment by piotr-napadlek** [comment]
Same issue here with a container app definition. I guess this is more of a terraform limitation than the provider, but I'm not sure why the creators decided to use `body` parameter as a string which needs to be manually transformed into json via jsonencode as opposed to using dynamic object for body and encoding it to json string under the hood. This would allow `lifecycle_ignore_changes` to work normally.

BTW I worked around the problem by tagging the docker image in a registry with a `latest` tag (plus normal versioned tag), and then setting the image in my template to be `latest`. The downside of it is that the terraform run causes dummy revision which deploys the same version but with different tag, but effectively there is no change in the deployed code.

**Comment by ms-henglu** [comment]
Hi all,

The `ignore_body_changes` feature is released in v1.9.0, here's how to use it: https://github.com/Azure/terraform-provider-azapi/issues/315#issuecomment-1716943998

Would you please check it? And let me know if it doesn't work for you.

Thanks!

**Comment by gianrubio** [comment]
@ms-henglu the feature does not work on v1.9.0

**Comment by ms-henglu** [comment]
Hi @danowensdev , 

Yes, we'll improve it in the future. Thanks!
