### ISSUE TITLE
Trying to create a recommendation digest but getting this error: "The requested resource does not support http method 'GET'."

### ISSUE THREAD

**Issue by alyssaashmore** [Azure/terraform-provider-azapi#222]
Hello! I am trying to create a recommendation digest per these Microsoft instructions:

https://learn.microsoft.com/en-us/azure/templates/microsoft.advisor/2020-01-01/configurations?pivots=deployment-language-terraform

```
data "azurerm_monitor_action_group" "action_group" {
  resource_group_name = "rg-avx-${module.locals.sub_yaml_decode.subscription_name}"
  name                = "ag-${module.locals.sub_yaml_decode.subscription_name}"
}

data "azurerm_subscription" "subscription" {
}

resource "azapi_resource" "recommendation_digest" {
  type = "Microsoft.Advisor/configurations@2020-01-01"
  parent_id = data.azurerm_subscription.subscription.id
  name = "recommendation-digest-${module.locals.sub_yaml_decode.subscription_name}"
  body = jsonencode({
    properties = {
      digests = [
        {
          actionGroupResourceId = data.azurerm_monitor_action_group.action_group.id
          categories = [
            "Cost",
            "HighAvailability",
            "OperationalExcellence",
            "Performance",
            "Security"
          ]
          frequency = 7
          name = "recommendation-digest-${module.locals.sub_yaml_decode.subscription_name}"
        }
      ]
    }
  })
}
```

Terraform plan works fine but, when I run terraform apply, I get this error: 

```
--------------------------------------------------------------------------------
│ RESPONSE 405: 405 Method Not Allowed
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "Message": "The requested resource does not support http method 'GET'."
│ }
│ --------------------------------------------------------------------------------
```

I saw other issues on here where the solution was to use azapi_resource_action instead of azapi_resource. For example, this issue: https://github.com/Azure/terraform-provider-azapi/issues/217. However ,when I run terraform apply then I get this error:

`│ Error: 'resource_id' and 'type' are not matched, expect 'type' to be Microsoft.Resources/subscriptions, but got Microsoft.Advisor/configurations`

Any help would be appreciated!

**Comment by ms-henglu** [comment]
Hi @alyssaashmore ,

Thank you for taking time to report this issue!

Yes, it seems this resource doesn't support GET method, so we must use `azapi_resource_action` to manage it.

Here's an example:

```hcl
resource "azapi_resource_action" "recommendation_digest" {
  type        = "Microsoft.Advisor/configurations@2020-01-01"
  resource_id = "${data.azurerm_subscription.subscription.id}/providers/Microsoft.Advisor/configurations/recommendation-digest-${module.locals.sub_yaml_decode.subscription_name}"
  method      = "PUT"
  body = jsonencode({
    properties = {
      digests = [
        {
          actionGroupResourceId = data.azurerm_monitor_action_group.action_group.id
          categories = [
            "Cost",
            "HighAvailability",
            "OperationalExcellence",
            "Performance",
            "Security"
          ]
          frequency = 7
          name      = "recommendation-digest-${module.locals.sub_yaml_decode.subscription_name}"
        }
      ]
    }
  })
}

```

**Comment by alyssaashmore** [comment]
Hi! Thank you very much for your response. I tried to change the code to this but I'm getting an error:

`--------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidConfigurationName
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidConfigurationName"
│   }
│ }
│ --------------------------------------------------------------------------------`

**Comment by alyssaashmore** [comment]
So was able to solve this error if anyone else runs into it... I changed resource_id to be: 

`resource_id = "${data.azurerm_subscription.subscription.id}/providers/Microsoft.Advisor/configurations/default"
`

and that worked. I'm not really sure why, but maybe you could weigh in @ms-henglu?

Thanks for the help!

**Comment by ms-henglu** [comment]
Hi @alyssaashmore ,

Glad that you've solved it! I guess the `"recommendation-digest-${module.locals.sub_yaml_decode.subscription_name}"` is not an acceptable name, so changing it to `default` fixed it. I've also updated my config above.

I'll close this issue, but feel free to reopen it if there's further question.
