### ISSUE TITLE
Support Query Parameters for resources

### ISSUE THREAD

**Issue by rdbartram** [Azure/terraform-provider-azapi#223]
I can use the `azapi_resource_action` to call the API [here](https://learn.microsoft.com/en-us/rest/api/desktopvirtualization/session-hosts/update?tabs=HTTP).

I need the ability to pass the Force query parameter, so I can update existing resources

**Comment by rdbartram** [comment]
I passed the info in the resourceid field and managed to get it to work. Might be worth implementing specifically though

**Comment by tamirkamara** [comment]
@rdbartram can you share how you did that?

**Comment by ms-henglu** [comment]
Hi all,

This feature has been supported by https://github.com/Azure/terraform-provider-azapi/pull/590 and released in v2.0.0-beta. Please give it a try.

I'll close this issue, feel free to reopen it if there's any questions.
