### ISSUE TITLE
Version 1.1.0 is marked as unreleased in CHANGELOG but published in Terraform registry

### ISSUE THREAD

**Issue by BzSpi** [Azure/terraform-provider-azapi#224]
Hello,

In the file CHANGELOG.md, the version `1.1.0` is marked as unreleased but provider is pushed on the Terraform registry as latest.

Please update the CHANGELOG.

**Comment by ms-henglu** [comment]
Hi @BzSpi ,

Thank you for taking time to report this issue!

I'll update the CHANGELOG.
