### ISSUE TITLE
"Microsoft.Advisor/configurations@2020-01-01" - The requested resource does not support http method 'GET'

### ISSUE THREAD

**Issue by DanAdams-Servent** [Azure/terraform-provider-azapi#227]
_**Affected Resource**_

resource "azapi_resource"
"Microsoft.Advisor/configurations@2020-01-01"

**_Terraform Configuration File_**

```
resource "azapi_resource" "azAdvisorDigest" {
  type      = "Microsoft.Advisor/configurations@2020-01-01"
  parent_id = data.azurerm_subscription.current.id
  name      = "digest001"
  schema_validation_enabled = false
  body = jsonencode({
    properties = {
      digests = [
        {
          name                  = "digest001"
          value                 = "Daily"
          actionGroupResourceId = var.actionGroupId
          frequency             = 7
          categories = [
            "HighAvailability",
            "Security",
            "Performance",
            "OperationalExcellence",
            "Cost"
          ]
          language = "en"
          state = "Active"
        }
      ]
    }
  })
}
```

**_Actual Problem_**

During a terraform apply the azapi resource provider attempts a GET request to the following URL:

`https://management.azure.com/subscriptions/<subscriptionId>/providers/Microsoft.Advisor/configurations/default?api-version=2020-01-01`

And it fails with error:
│ {
│ "Message": "The requested resource does not support http method 'GET'."
│ }

GET isn’t available for this api, you can instead use :

`https://management.azure.com/subscriptions/<subscriptionId>/providers/Microsoft.Advisor/configurations?api-version=2020-01-01`

Sending a PUT request to the top URL works fine when using postman.

**_References_**

[Azure Advisor REST API | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/advisor/)

**Comment by ms-henglu** [comment]
Hi @DanAdams-Servent ,

Thank you for taking time to report this issue!

It seems that this resource doesn't support GET http method, which means azapi_resource couldn't fetch the latest state of this issues.

Would you please give the following workaround a try? Thanks!
```hcl
resource "azapi_resource_action" "test" {
  type = "Microsoft.Advisor/configurations@2020-01-01"
  resource_id = "${data.azurerm_subscription.current.id}/providers/Microsoft.Advisor/configurations/default"
  method = "PUT"
  body = jsonencode({
    properties = {
      digests = [
        {
          name                  = "digest001"
          value                 = "Daily"
          actionGroupResourceId = var.actionGroupId
          frequency             = 7
          categories = [
            "HighAvailability",
            "Security",
            "Performance",
            "OperationalExcellence",
            "Cost"
          ]
          language = "en"
          state = "Active"
        }
      ]
    }
  })
}
```

**Comment by ms-henglu** [comment]
I'll close this issue, but feel free to reopen it if there's further question.
