### ISSUE TITLE
Unbale to use subscription rename using azapi_resource

### ISSUE THREAD

**Issue by bharathpendem** [Azure/terraform-provider-azapi#232]
resource "azapi_resource" "subscription_name1" {
  type = "Microsoft.Subscription/rename@2020-09-01"
  name = "default"
  parent_id = "XXXXXXXXXXXXX"
  ignore_casing             = false
  ignore_missing_property   = true
  schema_validation_enabled = false
  
  body = jsonencode({
    "properties": {
      subscriptionName = "test name"
  }
  })
}

when I try to apply I am getting "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."  Error message .
Have tried using azapi_update_resource as well.

**Comment by ms-henglu** [comment]
Hi @bharathpendem ,

Thank you for taking time to report this issue!

I guess that you want to use [this subscription rename API](https://learn.microsoft.com/en-us/rest/api/subscription/2020-09-01/subscription/rename?tabs=HTTP) in Terraform.

Here's an example:
```hcl
resource "azapi_resource_action" "test" {
  type        = "Microsoft.Resources/subscriptions@2022-09-01"
  resource_id = "/subscriptions/{subscriptionId}"
  action      = "providers/Microsoft.Subscription/rename"
  body = jsonencode({
    subscriptionName = "Test Sub"
  })
}

```

**Comment by bharathpendem** [comment]
Thanks for the update, Let me test and confirm the same.

**Comment by ms-henglu** [comment]
I'll close this issue since there's no response, please feel free to reopen it, thanks!
