### ISSUE TITLE
Provider zip filename uses the wrong format

### ISSUE THREAD

**Issue by vijaytdh** [Azure/terraform-provider-azapi#233]
I think the provider releases that you publish have the wrong file name, for example, the file:

terraform-provider-azapi_v1.1.0_linux_amd64.zip

I think this should actually be named:

terraform-provider-azapi_1.1.0_linux_amd64.zip

Without the "v" - if I look at other providers they do not include the "v" in the zip file name.

The documentation [here](https://developer.hashicorp.com/terraform/cli/config/config-file#provider-installation) states:

```
Terraform expects the given directory to contain a nested directory structure where the path segments together provide metadata about the available providers. The following two directory structures are supported:

Packed layout: HOSTNAME/NAMESPACE/TYPE/terraform-provider-TYPE_VERSION_TARGET.zip is the distribution zip file obtained from the provider's origin registry.
Unpacked layout: HOSTNAME/NAMESPACE/TYPE/VERSION/TARGET is a directory containing the result of extracting the provider's distribution zip file.
In both layouts, the VERSION is a string like 2.0.0 and the TARGET specifies a particular target platform using a format like darwin_amd64, linux_arm, windows_amd64, etc.
```

If you are running a CI pipeline behind a firewall and you use a local filesystem mirror, Terraform will ignore the file:

```
2022-12-20T14:09:52.792Z [WARN]  ignoring local provider path "/home/vijayt/tf-mirror/providers/registry.terraform.io/Azure/azapi/terraform-provider-azapi_v1.1.0_linux_amd64.zip" with invalid version "v1.1.0": a "v" prefix should not be used
```

Please may I request that the release process is changed to remove this extra "v" from the zip filename.

**Comment by ms-henglu** [comment]
Hi @vijaytdh ,

Thank you for taking time to report this issue!

I'll check and fix it. For your case, does it work if you change the zip file name to remove the extra `v`?

**Comment by vijaytdh** [comment]
@ms-henglu thanks for responding so quickly on this. Yes it does, in our CI pipeline code, I have added a special if statement just for this provider where I remove the extra `v` after downloading it and then Terraform will happily use it.
