### ISSUE TITLE
API result filter example

### ISSUE THREAD

**Issue by garddolau** [Azure/terraform-provider-azapi#236]
Hi Team,

What is the best way to filter results? trying to replicate this az cli to use azapi instead.

Got this far but don't know how best to filter results to just return privateEndpointConnections in "Pending" state

data "azapi_resource" "example" {
  resource_id            = azurerm_storage_account.storage_datalake.id
  type                   = "Microsoft.Storage/storageAccounts@2022-05-01"
  response_export_values = ["*"]
}

output "private_endpoint_connections" {
  value = jsondecode(data.azapi_resource.example.output).properties.privateEndpointConnections[0].id
}

I want to replicate query below.

$pending_connection_id = az network private-endpoint-connection list --resource-group "rg-name" --name "st-name" --type Microsoft.Storage/storageAccounts --query "[?properties.privateLinkServiceConnectionState.status=='Pending'].id" --output tsv

az network private-endpoint-connection approve --resource-group "rg-name" --id $pending_connection_id  --description "Approved"

Thanks,
Darren

**Comment by ms-henglu** [comment]
Hi @garddolau ,

Thank you for taking time to report this issue! And so sorry for the delayed response.

Here's an example, it shows how to use HCL's for-loop and if-condition to filter the data you needed.
```hcl
locals {
  connectionIds = [
    for connection in jsondecode(data.azapi_resource.example.output).properties.privateEndpointConnections : connection.id
    if connection.properties.privateLinkServiceConnectionState.status == "Pending"
  ]
}

resource "azapi_update_resource" "connection" {
  type = "Microsoft.Storage/storageAccounts/privateEndpointConnections@2022-09-01"
  resource_id = each.key
  body = jsonencode({
    properties = {
      privateLinkServiceConnectionState = {
        status      = "Approved"
        description = "example description"
      }
    }
  })
  for_each = toset(local.connectionIds)
}
```

**Comment by garddolau** [comment]
Closed
