### ISSUE TITLE
Microsoft.Web/staticSites/config@2022-03-01 - The requested resource does not support http method 'GET'

### ISSUE THREAD

**Issue by Grz3hu** [Azure/terraform-provider-azapi#241]
Terraform v1.3.7
azapi v1.2.0

**Terraform file:**
```
resource "azapi_resource" "storybook-site-appsettings" {
  type      = "Microsoft.Web/staticSites/config@2022-03-01"
  name      = "appsettings"
  parent_id = azurerm_static_site.storybook-site.id
  body = jsonencode({
    properties = {
      "AAD_CLIENT_ID" = azuread_application.storybook-app.application_id
    }
    kind = "string"
  })
  schema_validation_enabled = false
}
```

**error:**
```
│ --------------------------------------------------------------------------------
│ RESPONSE 405: 405 Method Not Allowed
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "Message": "The requested resource does not support http method 'GET'."
│ }
│ --------------------------------------------------------------------------------
│
│
│   with azapi_resource.storybook-site-appsettings,
│   on main.tf line 58, in resource "azapi_resource" "storybook-site-appsettings":
│   58: resource "azapi_resource" "storybook-site-appsettings" {
```

Problem:
Terraform is making a GET request to endpoint that provides only PUT method

I followed official microsoft documentation to write the code
https://learn.microsoft.com/en-us/azure/templates/microsoft.web/staticsites/config-appsettings?source=recommendations&pivots=deployment-language-terraform

**Comment by ms-henglu** [comment]
Hi @Grz3hu ,

Thank you for taking time to report this issue!

There's a workaround for this, hope it can help you.

```hcl
resource "azapi_resource_action" "storybook-site-appsettings" {
  type       = "Microsoft.Web/staticSites/config@2022-03-01"
  resoure_id = "${azurerm_static_site.storybook-site.id}/config/appsettings"
  method     = "PUT"
  body = jsonencode({
    properties = {
      "AAD_CLIENT_ID" = azuread_application.storybook-app.application_id
    }
    kind = "string"
  })
  schema_validation_enabled = false
}
```

**Comment by mdecoleman** [comment]
The above `PUT` works for the default `Production` app settings is there a way of updating/creating preview deployment app settings?

The `kind` field on create using vanilla `ARM` templates allows you to do that but it has no affect doing it above.

**Comment by ms-henglu** [comment]
Hi @mdecoleman , would you please share me how to do it with raw REST API? Then I can share you an azapi provider example. Thanks!

**Comment by ms-henglu** [comment]
I'll close this issue since there's no response, please feel free to reopen it, thanks!
