### ISSUE TITLE
azapi is not handling Azure rate limiting (HTTP 429 Too Many Requests)

### ISSUE THREAD

**Issue by hallgeir-osterbo-visma** [Azure/terraform-provider-azapi#242]
We're running into issues with Azure rate limiting when destroying multiple function apps created with azapi (I'm sure this applies to other resource types as well - this is just our specific use case). It seems the `azapi` provider doesn't handle HTTP 429 responses. 

Here is a minimal example I've created for this:
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.37.0"
    }
    azapi = {
      source  = "Azure/azapi"
      version = "=1.2.0"
    }
  }
}

provider "azurerm" {
  features {}
}


provider "azapi" {
}

resource "azurerm_resource_group" "example" {
  name     = "myrg"
  location = "norwayeast"
}

resource "azurerm_service_plan" "example" {
  name                = "example-app-service-plan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Windows"
  sku_name            = "Y1"
}

resource "azurerm_storage_account" "example" {
  name                     = "tfazapirl3ba2"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azapi_resource" "func" {
  count     = 10
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = "example-windows-function-app-3ba2-${count.index}"
  parent_id = azurerm_resource_group.example.id
  location  = azurerm_resource_group.example.location
  body = jsonencode({
    kind = "functionapp"
    properties = {
      enabled      = true
      serverFarmId = azurerm_service_plan.example.id
    }
  })
  tags = {
  }
}
```
Simply do:
`terraform init`
`terraform apply`
`terraform destroy`

and you get the following errors for multiple of the function apps:
```
--------------------------------------------------------------------------------
│ RESPONSE 429: 429 Too Many Requests
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "Code": "429",
│   "Message": "Cannot acquire exclusive lock to create, update or delete this site. Retry the request later.",
│   "Target": null,
│   "Details": [
│     {
│       "Message": "Cannot acquire exclusive lock to create, update or delete this site. Retry the request later."
│     },
│     {
│       "Code": "429"
│     },
│     {
│       "ErrorEntity": {
│         "ExtendedCode": "59206",
│         "MessageTemplate": "Cannot acquire exclusive lock to create, update or delete this site. Retry the request later.",
│         "Parameters": [],
│         "Code": "429",
│         "Message": "Cannot acquire exclusive lock to create, update or delete this site. Retry the request later."
│       }
│     }
│   ],
│   "Innererror": null
│ }
│ --------------------------------------------------------------------------------
│
```

With the `azurerm` provider, this works flawlessly (but there's a bug in `azurerm` related to using the dotnet-isolated runtime that prevents us from using it at this time: https://github.com/Azure/azure-functions-dotnet-worker/issues/1261 hence we turned to `azapi`). I suppose there is some backoff and retry logic in `azurerm` that is not implemented in `azapi`?

I know I can set parallelism to 1 in Terraform, but this is very suboptimal because it would serialize the whole infrastructure apply/destroy operation (and we have a LOT of resources). What would be the best way to work around this? And is there any plans to implement backoff-and-retry in case of hitting API limits with `azapi`?

**Comment by ms-henglu** [comment]
Hi @hallgeir-osterbo-visma ,

Thank you for taking time to report this issue!

The `azapi_resource` supports `locks`, which is used to avoid create/modify/delete multiple related `azapi resources` at the same time. Resources with same locks won't be created at the same time.

In the below example, 10 resources will be created one by one.
```hcl
resource "azapi_resource" "func" {
  count     = 10
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = "henglu0120-function-app-${count.index}"
  parent_id = azurerm_resource_group.example.id
  location  = azurerm_resource_group.example.location
  body = jsonencode({
    kind = "functionapp"
    properties = {
      enabled      = true
      serverFarmId = azurerm_service_plan.example.id
    }
  })
  locks = [azurerm_service_plan.example.id]
  tags = {
  }
}
```

And it's not necessary for the values in the `locks` to be resource IDs. So it's flexible, you can control how many resources can be created at the same time, in the following example, 3 resources will be created at the same time.

```hcl
locks = ["${count.index % 3}"]
```

refs: https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource#locks

**Comment by hallgeir-osterbo-visma** [comment]
Ah, that's great info - thank you! That should work for our scenario.
