### ISSUE TITLE
cannot update publicnetworkaccess on recovery services vault

### ISSUE THREAD

**Issue by fgarcia-cnb** [Azure/terraform-provider-azapi#243]
running the code below, modified from [microsoft documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/vaults?pivots=deployment-language-terraform)

```hcl
resource "azapi_update_resource" "public_access" {
  count       = var.resource_count
  type        = "Microsoft.RecoveryServices/vaults@2022-09-30-preview"
  resource_id = azurerm_recovery_services_vault.recovery_vault[count.index].id

  body = jsonencode({
    properties = {
      publicNetworkAccess = var.enable_public_access ? "Enabled" : "Disabled"
    }
  })
}
```

but getting the following error:

_Error: creating/updating "Resource: (ResourceId \"/subscriptions/HIDDEN/providers/Microsoft.RecoveryServices/vaults/td04agc96tgi-recovery-vault-00\" / Api Version \"2022-09-30-preview\")": PUT https://management.azure.com/subscriptions/HIDDEN/providers/Microsoft.RecoveryServices/vaults/td04agc96tgi-recovery-vault-00 -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request ERROR CODE: InvalidRestApiParameter -------------------------------------------------------------------------------- { "error": { "code": "InvalidRestApiParameter", "message": "redundancySettings parameter is invalid. Please provide a valid redundancySettings", "target": null, "details": null, "innerError": null } } -----------------------_

i suspect the issue is that its doing a PUT instead of a PATCH call

**Comment by fgarcia-cnb** [comment]
i tested from command line and api call definitely works when using patch

**Comment by ms-henglu** [comment]
Hi @fgarcia-cnb ,

Thank you for taking time to report this issue!

Would you please try to use `azapi_resource_action` which provides more flexibility, here's an example:

```hcl
resource "azapi_resource_action" "public_access" {
  count       = var.resource_count
  type        = "Microsoft.RecoveryServices/vaults@2022-09-30-preview"
  resource_id = azurerm_recovery_services_vault.recovery_vault[count.index].id
  
  method      = "PATCH"

  body = jsonencode({
    properties = {
      publicNetworkAccess = var.enable_public_access ? "Enabled" : "Disabled"
    }
  })
}
```

**Comment by fgarcia-cnb** [comment]
oh duh, i totally forgot about this new resource that allows the method flexibility. it worked. thanks

**Comment by ms-henglu** [comment]
Glad to see it works, I'll close this issue, but feel free to reopen it if there's further question.
