### ISSUE TITLE
Microsoft.RecoveryServices/vaults/replicationRecoveryPlans@2022-09-10

### ISSUE THREAD

**Issue by pmunozmartinez** [Azure/terraform-provider-azapi#246]
I deployed a recovery plan. For this, I used the azapi provider of type : [Microsoft.RecoveryServices/vaults/replicationRecoveryPlans@2022-09-10](mailto:Microsoft.RecoveryServices/vaults/replicationRecoveryPlans@2022-09-10) without any problem, but once deployed, every time I try to re-execute the terraform code, I get the following error:
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: BadRequest
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "BadRequest",
│     "message": "The resource name 'RecoveryPlan001' is already in use.",
│     "details": [
│       {
│         "code": "ArmResourceNameNotAvailable",
│         "message": "The resource name 'RecoveryPlan001' is already in use.",
│         "possibleCauses": "Another resource exists with the same name.",
│         "recommendedAction": "Specify a different resource name and try again.",

**Comment by ms-henglu** [comment]
Hi @pmunozmartinez ,

Thank you for taking time to report this issue!

Would you please share me more details so I can help investigate? Like the output of `terraform plan`.

And this resource is also supported in azurerm provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/site_recovery_replication_recovery_plan

**Comment by ms-henglu** [comment]
I'll close this issue since there's no response, please feel free to reopen it, thanks!
