### ISSUE TITLE
SPN role assignment to "/providers/Microsoft.aadiam" on AAD

### ISSUE THREAD

**Issue by rikribbers** [Azure/terraform-provider-azapi#247]
Hi,

More of a question then a bug report.... not entirely sure if this is the correct place. I am trying to enable AAD diagnostics logging in an automated way. I came accross this comment:  https://github.com/Azure/azure-rest-api-specs/issues/11085#issuecomment-1363008480

It states that you need to assign the "Contributor" role to the SPN for the "/providers/Microsoft.aadiam" scope in order to let the SPN automatically enable the diagnostic logging... so far so good... there is actually an az cli example there
````bash
az role assignment create --assignee-principal-type  ServicePrincipal --assignee-object-id <OBJECT_ID_ENTERPRISE_APP> --scope "/providers/Microsoft.aadiam" --role <ROLE_ID>
````

Translating that into terraform code using the azapi instead of a null_resource my attempt looked like this:

````hcl
data "azurerm_role_definition" "contributor" {
  name = "Contributor"
}

data "azuread_service_principal" "spn" {
  display_name = "my-awesome-application"
}

resource "azapi_resource" "role_assignment" {
  type      = "Microsoft.Authorization/roleAssignments@2022-04-01"
  name      = "some-generated-guid"
  parent_id = "/providers/Microsoft.aadiam"
  body = jsonencode({
    properties = {
      principalId      =  data.azuread_service_principal.spn.object_id
      roleDefinitionId =  data.azurerm_role_definition.connection.id
      principalType    = "ServicePrincipal"
    }
  })
}
````

````
│ Error: checking for presence of existing Resource: (ResourceId "/providers/Microsoft.aadiam/providers/Microsoft.Authorization/roleAssignments/b597f7cd-d635-e464-af8e-10e55f100a3d" / Api Version "2022-04-01"): GET https://management.azure.com/providers/Microsoft.aadiam/providers/Microsoft.Authorization/roleAssignments/b597f7cd-d635-e464-af8e-10e55f100a3d
│ --------------------------------------------------------------------------------
│ RESPONSE 403: 403 Forbidden
│ ERROR CODE: AuthorizationFailed
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "AuthorizationFailed",
│     "message": "The client 'some-object-id with object id 'some-object-id' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/read' over scope '/providers/Microsoft.aadiam/providers/Microsoft.Authorization/roleAssignments/b597f7cd-d635-e464-af8e-10e55f100a3d' or the scope is invalid. If access was recently granted, please refresh your credentials."
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with azapi_resource.role_assignment,
│   on main.tf line 187, in resource "azapi_resource" "role_assignment":
│  187: resource "azapi_resource" "role_assignment" {
│ 
╵
````

Reading through the documentation I came to the conslusion that parent_id should be "/" so it is on tenant scope. But now I am kind of stuck on where can I add the provider (/providers/Microsoft.aadiam) scope... It is not in the JSON according the API reference documentation.

So is there a way to do this with the azapi provider or am I stuck with the null_resource and az cli? If no, can this be added and If yes please enlighten me.

**Comment by ms-henglu** [comment]
Hi @rikribbers ,

Thank you for taking time to report this issue!

It seem that your azapi configuration is correct, the `parent_id` should be `/providers/Microsoft.aadiam`. Would you please check the permission? If you can use the az cli command to create the role assignment, I think it should work if you authenticate with azure by azure cli.

**Comment by rikribbers** [comment]
Hi  @ms-henglu ,

Thanks for replying. We actually do this in an Azure DevOps Pipeline so the underlying SPN should be capable of creating the role assingment. However I don't see any role assingment on the SPN

az role assignment list --all --assignee <Azure DevOps Service Connection SPN Application ID> --output json --query '[].{principalName:principalName, roleDefinitionName:roleDefinitionName, scope:scope}'
[]

Maybe out of context for this specific issue, but what RBAC should I assign the the SPN that is actually assigning the RBAC for the "Microsoft.aadiam" provider...

**Comment by rikribbers** [comment]
remove my last comment as that was totally wrong.

**Comment by rikribbers** [comment]
I have tested and I can assign the RBAC manually through AZ cli. However I now get a different error. I think it is related to my local setup (using vscode and Dev Containers)

will have to dive into that before I can make a more sensible response than the last one...

````
╷
│ Error: checking for presence of existing Resource: (ResourceId "/providers/Microsoft.aadiam/providers/Microsoft.Authorization/roleAssignments/a8f2cc1d-08c8-bfa0-f2e5-68f2a66141ac" / Api Version "2022-04-01"): DefaultAzureCredential authentication failed
│ GET http://169.254.169.254/metadata/identity/oauth2/token
│ --------------------------------------------------------------------------------
│ RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
│ --------------------------------------------------------------------------------
│ connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
│ --------------------------------------------------------------------------------
│ 
````

**Comment by rikribbers** [comment]
wow time flies when having fun... Finally got some time to deep dive into this. no issues just local development setup things.

but with 1.7.0 release this is fixed by using the following provider configuration

````hcl
provider "azapi" {
  use_msi = false
  use_cli = true
}
````

**Comment by abij** [comment]
As of version 1.10 this is still a solution to `403 Forbidden` when using the `azapi` with Azure-CLI authentication.

```hcl
provider "azapi" {
  use_msi = false  # Or an environment variable: ARM_USE_MSI=false
  # This is default use_cli = true and can be skipped.
}
```
I have the feeling there is a bug with the authentication, it does not try msi and fallback to azure-cli. There is a discussion in issue #377 to not set use msi as default.

The [azure.identity DefaultAzureCredential](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) class has a mechanism to try multiple types for example.
