### ISSUE TITLE
feature request: add resource to update authentication token

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#253]
Hi,

I have had an issue logged here on a module that uses AzAPI: Azure/terraform-azurerm-lz-vending#153

I believe this is caused by caching and would be resolved by re-authenticating.

I would like a dummy resource that could be built into the dependency graph that would create new credentials.

e.g.

```terraform
resource "azapi_resource" "prerequisite" {
  # ...
}

# Token refresh here
resource "azapi_token_refresh" "after_prerequisite" {}

resource "azapi_resource" "child" {
  # ...
  depends_on = [azapi_token_refresh.after_prerequisite]
}
```

This is similar to this issue in AzureRM but we use different SDK here:

Azure/terraform-azurerm-caf-enterprise-scale#536

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

The related issue is closed, is it still necessary to have this feature?

**Comment by matt-FFFFFF** [comment]
The retry feature solves this issue in another way
