### ISSUE TITLE
Enabling AAD diagnostic logging error message not handled properly

### ISSUE THREAD

**Issue by rikribbers** [Azure/terraform-provider-azapi#255]
Hi,

I am getting an error I don't understand, could be a bug or misunderstanding from my side.

I want to enable the signin logs from AAD to be sent to a loganalytics instance. We do this through automation in Azure DevOps. So the SPN that is underlying the service connection is executing the terraform 

The SPN is Contributor on the provider "/providers/Microsoft.AADIam" (assigned manually through az cli) 

Below is the configuration and the error code:

````hcl

data "azurerm_log_analytics_workspace" "log_analytics" {
  name                = "<name>"
  resource_group_name = "<rgname>"
}

resource "azapi_resource" "aad_diagnostics" {
  type      = "Microsoft.AADIam/diagnosticsettings@2017-04-01-preview"
  name      = "resource-logging"
  parent_id = "/"

  body = jsonencode({
    properties = {
      workspaceId = data.azurerm_log_analytics_workspace.log_analytics.id
      logs = [
        {
          category        = "AuditLogs",
          enabled         = true,
          retentionPolicy = { enabled = false, days = 0 }
        },
        {
          category        = "SignInLogs",
          enabled         = true,
          retentionPolicy = { enabled = false, days = 0 }
        }
      ]

    }
  })
}
````

````
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: creating/updating "Resource: (ResourceId \"/providers/Microsoft.AADIam/diagnosticsettings/resource-logging\" / Api Version \"2017-04-01-preview\")": missing error information
│ 
│   with azapi_resource.aad_diagnostics,
│   on main.tf line 104, in resource "azapi_resource" "aad_diagnostics":
│  104: resource "azapi_resource" "aad_diagnostics" {
│ 

````

Any suggestion or is this a bug?

**Comment by ms-henglu** [comment]
Hi @rikribbers ,

Thank you for taking time to report this issue!

I've created an issue to track the error message couldn't be parsed: https://github.com/Azure/azure-sdk-for-go/issues/19956

And I have some workarounds that might help with this case:
1. Register the `Microsoft.AADIam` resource provider, you can use: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_provider_registration
2. Would you please try to use Postman or similar tools to make the API call, see if there's any error?
```
PUT https://management.azure.com/providers/Microsoft.AADIam/diagnosticsettings/resource-logging?api-version=2017-04-01-preview
Authorization: Bearer {access token, you can get it with az cli command: az account get-access-token }

Body:
{
  "properties": {
    "workspaceId": "{data.azurerm_log_analytics_workspace.log_analytics.id}",
    "logs": [
      {
        "category": "AuditLogs",
        "enabled": true,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      },
      {
        "category": "SignInLogs",
        "enabled": true,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      }
    ]
  }
}
```

**Comment by rikribbers** [comment]
Did a test with option 1: Resource provider was indeed missing (not registered), did that and got the same error. Will try option 2 later.

**Comment by ms-henglu** [comment]
After registering the resource provider, I think then you can create this resource by the azapi provider.

**Comment by rikribbers** [comment]
Hi @ms-henglu ,

I have enable the providers on the subscriptions that did not solve the issue. Manually testing with postman gave the following error message:
````
{
    "code": "Conflict",
    "message": "Data sink '<removed log analytics workspace is here>' for category 'AuditLogs'. Data sinks can't be reused in different settings on the same category for the same resource."
}
````

I now know what todo.. remove the manual diagnostics that we have in place to resolve my issue. 

will rename this issue with the correct problem description to handle the error message correctly in the provider

**Comment by rikribbers** [comment]
@ms-henglu and many thanks for your support on this!

**Comment by ms-henglu** [comment]
I'll close this issue since it's resolved, please feel free to reopen it, thanks!
