### ISSUE TITLE
The requested resource does not support http method 'GET' - azurerm_static_site

### ISSUE THREAD

**Issue by swolg** [Azure/terraform-provider-azapi#256]
I encountered an error while attempting to deploy a Static Site on Azure and **update** the App Settings with azapi.
I tried to investigate the issue by using the https://resources.azure.com/ and some other workarounds, but I still cannot resolve it. 

Issue #241 has a similar problem, but I would need the update functionality.

![image](https://user-images.githubusercontent.com/72341912/217351153-b281d7d9-2484-4946-a0b4-b568760979f5.png)
![image](https://user-images.githubusercontent.com/72341912/217354326-3487f697-2e68-49de-acbe-1f8641806fa7.png)

**Terraform** 
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.41.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=2.31.0"
    }
    azapi = {
      source  = "azure/azapi"
      version = "=1.3.0"
    }
  }
  required_version = "=1.3.7"
}

provider "azurerm" {
  features {}
}
provider "azapi" {
}
```

```
resource "azurerm_static_site" "testing-site" {
  name                = "testing"
  location            = azurerm_resource_group.rg-testing-rg.location
  resource_group_name = azurerm_resource_group.rg-testing-rg.name
}

resource "azapi_update_resource" "testing-appsettings" {
  type      = "Microsoft.Web/staticSites/config@2022-03-01"
  name      = "appsettings"
  parent_id = azurerm_static_site.testing-site.id

  body = jsonencode({
    properties = {
      key1 = "value1"
    }
    kind = "appsettings"
  })
}
```

**Error**
```
--------------------------------------------------------------------------------
│ RESPONSE 405: 405 Method Not Allowed
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "Message": "The requested resource does not support http method 'GET'."
│ }
│ --------------------------------------------------------------------------------
│
│
│   with azapi_update_resource.testing-appsettings,
│   on main.tf line 47, in resource "azapi_update_resource" "testing-appsettings":
│   47: resource "azapi_update_resource" "testing-appsettings" 

```

Used sources:
- https://learn.microsoft.com/en-us/azure/templates/microsoft.web/staticsites/config-appsettings?pivots=deployment-language-terraform

- https://learn.microsoft.com/en-us/azure/templates/microsoft.web/staticsites?pivots=deployment-language-terraform

With kind regards.

**Comment by ms-henglu** [comment]
Hi @swolg ,

Thank you for taking time to report this issue!

There's a workaround for this, hope it can help you.

```hcl
resource "azapi_update_resource" "testing-appsettings" {
  type      = "Microsoft.Web/staticSites/config@2022-03-01"
  resoure_id = "${azurerm_static_site.testing-site.id}/config/appsettings"
  method     = "PUT"

  body = jsonencode({
    properties = {
      key1 = "value1"
    }
    kind = "appsettings"
  })
}

```

**Comment by VixiXia** [comment]
> ```terraform
>  kind = "appsettings"
> ```

Hello @ms-henglu , seems this workaround does not work. 
![image](https://user-images.githubusercontent.com/24731902/221480874-6f3dadcf-a14c-42bc-a386-704baed7b43f.png)

**Comment by ms-henglu** [comment]
My bad, it should be `azapi_resource_action` instead of `azapi_update_resource`. I'll update the previous comment.

**Comment by VixiXia** [comment]
It works, thanks @ms-henglu!

**Comment by kiranpradeep** [comment]
For future readers: `azapi_resource_action` does not detect changes made externally. For e.g. if `value1` is changed to `value2` via Azure portal or az cli, then terraform will not detect and will not sync state. But still, this is best workaround appears better than nothing else for now.

**Comment by ms-henglu** [comment]
I'll close this issue, but feel free to reopen it if there's further question.
