### ISSUE TITLE
File lock issue in site extensions when called by Azure API (via Terraform AzAPI)

### ISSUE THREAD

**Issue by SeanKilleen** [Azure/terraform-provider-azapi#258]
Hi all -- cross-posting this here as well as [over at the Kudu repository](https://github.com/projectkudu/kudu/issues/3435) because I'm genuinely not sure where the issue lies and it may be on the AzAPI side.

_____

## Background

This occurred during a possibly interesting edge case. 

We deployed an instance of the Datadog site extension via the AzAPI provider of Terraform:

```terraform
resource "azapi_resource" "mainapp_datadog_extension" {
  count = var.uses_app_slot ? 0 : 1 # Don't run it when we're running for a slot

  type      = "Microsoft.Web/sites/siteextensions@2022-03-01"
  name      = "Datadog.AzureAppServices.DotNet"
  parent_id = jsondecode(data.azapi_resource.azapi_site_mainapp.output).id
}
```

The `count` line was subsequently added because I'd forgotten it causing the extension to be deleted as expected until the time I deployed to an environment that uses the main app (this current client is using app slots as full-fledged environments. I know, I know. I'm working on it.) 

When deploying to the main site once again, I saw the error in the Terraform apply response.

So in summary I think the reproduction is the following, though I haven't had the space to confirm yet:

* Enable an extension via Az API (maybe with terraform, but likely independent of it)
* Remove the extension via Az API (maybe with terraform, but likely independent of it)
* Enable the same extension again for the same site/slot.
* Expected behavior: Enabling it once again works
* Actual behavior: See error message shown below.

## The log/error given by the failure.

> "System.IO.IOException: The process cannot access the file because it is being used by another process.\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)\r\n   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\FileSystemHelpers.cs:line 68\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\FileSystemHelpers.cs:line 75\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\FileSystemHelpers.cs:line 75\r\n   at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.<Attempt>b__0() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 18\r\n   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 43\r\n   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 20\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.EnsureInstallationEnvironment(String installationDir, ITracer tracer) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManagerV2.cs:line 525\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.<InstallExtension>d__26.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManagerV2.cs:line 479\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.<TryInstallExtension>d__25.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManagerV2.cs:line 259"

## Other things I've noticed

Some other things I noticed led me to think it could be an AzAPI issue:

* I know the Terraform is working Terraform because I was able to successfully apply it to two other environments.
* I am able to execute this operation with no problems, in that environment, when using the Azure portal UI.
* This persisted across multiple restarts
* This persisted across scaling the application down/up which I believe restarts the worker process
* This persisted across moving the app service to a different app service plan

So I can't tell if the issue is with the Kudu Site extensions or the way the Azure API might be somehow using those extensions behind the scenes.

**Comment by ms-henglu** [comment]
Hi @SeanKilleen ,

Thank you for taking time to report this issue!

From the error message, it seems that they're not from azapi. Azapi provider is a thin layer on top of the ARM REST API. In this case, it only makes one PUT request to create the extension resource.

Would you please try to create the extension by REST API or other client tools and see if the issue persisted?

**Comment by ms-henglu** [comment]
BTW,  `parent_id = jsondecode(data.azapi_resource.azapi_site_mainapp.output).id` can be simplified to `parent_id  data.azapi_resource.azapi_site_mainapp.id`. :)

**Comment by SeanKilleen** [comment]
Ah I see, @ms-henglu -- while I haven't had the time to recreate, you are almost certainly correct that this wouldn't be on the AzAPI side. Going to close this.

Also, thank you for the tip! :) Adding a note for myself on that.
