### ISSUE TITLE
Cannot create openshift cluster

### ISSUE THREAD

**Issue by fbfsadam-burton** [Azure/terraform-provider-azapi#261]
'code': 'InvalidResourceProviderPermissions',
│     'message': 'The resource provider service principal does not have Network Contributor permission on vnet

resource "azapi_resource" "aro_cluster" {
  name      = "ARO-${var.g_tag_environment}-${var.resource_prefix != "" ? var.resource_prefix : random_string.resource_prefix.result}"
  location  = var.aro_location
  parent_id = azurerm_resource_group.rg.id
  type      = "Microsoft.RedHatOpenShift/openShiftClusters@2022-04-01"
  tags      = "${merge( local.common_tags, local.extra_tags)}"
  
  body = jsonencode({
    properties = {
      clusterProfile = {
        domain               = var.aro_domain
        fipsValidatedModules = var.fips_validated_modules
        resourceGroupId      = azurerm_resource_group.aro_rg.id
        pullSecret           = var.pull_secret
      }
      networkProfile = {
        podCidr              = var.pod_cidr
        serviceCidr          = var.service_cidr
      }
      servicePrincipalProfile = {
        clientId             = var.aro_cluster_aad_sp_client_id
        clientSecret         = var.aro_cluster_aad_sp_client_secret
      }
      masterProfile = {
        vmSize               = var.master_node_vm_size
        subnetId             = data.azurerm_subnet.get_master_subnet_id.id
        encryptionAtHost     = var.master_encryption_at_host
      }
      workerProfiles = [
        {
          name               = var.worker_profile_name
          vmSize             = var.worker_node_vm_size
          diskSizeGB         = var.worker_node_vm_disk_size
          subnetId           = data.azurerm_subnet.get_worker_subnet_id.id
          count              = var.worker_node_count
          encryptionAtHost   = var.worker_encryption_at_host
        }
      ]
      apiserverProfile = {
        visibility           = var.api_server_visibility
      }
      ingressProfiles = [
        {
          name               = var.ingress_profile_name
          visibility         = var.ingress_visibility
        }
      ]
    }

  })

**Comment by ms-henglu** [comment]
Hi @fbfsadam-burton ,

Thank you for taking time to report this issue!

Here's a post shows how to deploy an [Azure Red Hat OpenShift](https://learn.microsoft.com/en-us/azure/openshift/intro-openshift) cluster using [Terraform](https://www.terraform.io/) with the [AzAPI Provider](https://registry.terraform.io/providers/azure/azapi/latest/docs). You can find the code of this sample along with Terraform modules under this [Azure Sample](https://github.com/Azure-Samples/aro-azapi-terraform).

I think you need to add the role assignments like the following config:
```hcl
resource "azurerm_role_assignment" "aro_cluster_service_principal_network_contributor" {
  scope                = azurerm_virtual_network.virtual_network.id
  role_definition_name = "Contributor"
  principal_id         = var.aro_cluster_aad_sp_object_id
  skip_service_principal_aad_check = true
}

resource "azurerm_role_assignment" "aro_resource_provider_service_principal_network_contributor" {
  scope                = azurerm_virtual_network.virtual_network.id
  role_definition_name = "Contributor"
  principal_id         = var.aro_rp_aad_sp_object_id
  skip_service_principal_aad_check = true
}

```

**Comment by fbfsadam-burton** [comment]
We have both the permissions :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ms-henglu** [comment]
Please check whether `aro_rp_aad_sp_object_id` is passed with a correct value, it should be
```bash
# Get the service principal object ID for the OpenShift resource provider
aroResourceProviderServicePrincipalObjectId=$(az ad sp list --display-name "Azure Red Hat OpenShift RP" --query [0].id -o tsv)

```

**Comment by fbfsadam-burton** [comment]
It is :). Even the azure deployment logs are correct :)   I can paste a screen print tomorrow :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ms-henglu** [comment]
Please check whether `aro_rp_aad_sp_object_id` is passed with a correct value, it should be
```bash
# Get the service principal object ID for the OpenShift resource provider
aroResourceProviderServicePrincipalObjectId=$(az ad sp list --display-name "Azure Red Hat OpenShift RP" --query [0].id -o tsv)

```

**Comment by ms-henglu** [comment]
I'll close this issue since there's no response, please feel free to reopen it, thanks!
