### ISSUE TITLE
<redacted> in azure response causes constant change in azapi_resource for Kubernetes flux configuration

### ISSUE THREAD

**Issue by damienpontifex** [Azure/terraform-provider-azapi#268]
I'm using the the `azapi_resource` to create a `Microsoft.KubernetesConfiguration/fluxConfigurations@2022-11-01` resource as so:
```terraform
resource "azapi_resource" "flux_configuration" {
  type      = "Microsoft.KubernetesConfiguration/fluxConfigurations@2022-11-01"
  name      = "flux-system"
  parent_id = azurerm_kubernetes_cluster.aks_cluster.id
  depends_on = [
    azapi_resource.flux_aks_extension
  ]

  body = jsonencode({
    properties = {
      scope      = "cluster",
      namespace  = "flux-system"
      sourceKind = "GitRepository"
      configurationProtectedSettings = {
        sshPrivateKey = base64encode(tls_private_key.main.private_key_pem)
      }
# ... remainder here removed for brevity
```

The state (and result from `az k8s-configuration flux show`) has the `sshPrivateKey` as `"<redacted>"` which causes terraform to think that a change is needed every time this is applied

I have tried using `nonsensitive` surrounding the TLS private key, but considering the response from the az CLI has the redacted value, I'm guessing it's a response from ARM that's then being stored in terraform state.

Is there a way for terraform and ARM responses to work better together here? 
i.e. I understand the reason the key is redacted in the ARM response, but terraform shouldn't want to constantly modify this resource unless the `tls_private_key` is also modified.

**Comment by damienpontifex** [comment]
@ms-henglu is this a bug that could accept a community contribution? 

If so, any guidance on this as I'd be happy to submit a PR with some guidance on what a "fix" for this might entail

**Comment by ms-henglu** [comment]
Hi @damienpontifex ,

Sure! Appreciated that you want to contribute!

> If so, any guidance on this as I'd be happy to submit a PR with some guidance on what a "fix" for this might entail

Yes, we already added some workaround to bypass this kind of difference, some sensitive fields are returned in `****`. I think it's okay to add similar logic to bypass the case that sensitive fields are returned in `<redacted>`.

https://github.com/Azure/terraform-provider-azapi/blob/v1.4.0/utils/json.go#L98

**Comment by damienpontifex** [comment]
@ms-henglu I _think_ this is what you mean with the PR I just opened, linked here. Let me know any feedback or if it's way off the mark of what you intended to guide me towards :)
