### ISSUE TITLE
Defender for Cloud alert suppressions are not working

### ISSUE THREAD

**Issue by waynejnicklin** [Azure/terraform-provider-azapi#269]
I tried to use the subscription ID as the parent ID... I get the error "Error: `parent_id is invalid`: expect ID of `Microsoft.Security/alertsSuppressionRules`"

But if I use  `Microsoft.Security/alertsSuppressionRules` as the parent_id, I get the error:

 Error: invalid resource ID: resource id 'Microsoft.Security/alertsSuppressionRules' must start with '/'
│ 
│   with azapi_resource.db_reader_60_days,
│   on suppression_rules.tf line 4, in resource "azapi_resource" "db_reader_60_days":
│    4:   parent_id = "Microsoft.Security/alertsSuppressionRules"

I'm using the latest 1.4.0 of the azure/azapi provider.

So what am I supposed to put in there, to tie an alert suppression to a subscription?

resource "azapi_resource" "db_reader_60_days" {
  type      = "Microsoft.Security/alertsSuppressionRules/@2019-01-01-preview"
  name      = "${local.db_reader_role}-60-days"
  parent_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/Microsoft.Security/alertsSuppressionRules"
  body = jsonencode({
    properties = {
      state                  = "Enabled"
      reason                 = "FalsePositive"
      alertType              = "*"
      expirationDateUtc      = "9999-12-31 23:59:59.9999999Z"
      suppressionAlertsScope = {
        allOf = {
          field    = "entities.useraccount.name"
          contains = "${local.db_reader_role}"
        }
      }
    }
  })
}

**Comment by ms-henglu** [comment]
Hi @waynejnicklin ,

Thank you for taking time to report this issue!

I noticed there's a redundant `/` before `@` in the type field. It should be `  type      = "Microsoft.Security/alertsSuppressionRules@2019-01-01-preview"`.

And the `allOf` field should be an array, would you please give the below example a try? 

```hcl
resource "azapi_resource" "db_reader_60_days" {
  type      = "Microsoft.Security/alertsSuppressionRules@2019-01-01-preview"
  name      = "${local.db_reader_role}-60-days"
  parent_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  body = jsonencode({
    properties = {
      state             = "Enabled"
      reason            = "FalsePositive"
      alertType         = "*"
      expirationDateUtc = "9999-12-31 23:59:59.9999999Z"
      suppressionAlertsScope = {
        allOf = [
          {
            field    = "entities.useraccount.name"
            contains = "${local.db_reader_role}"
          }
        ]
      }
    }
  })
}
```

**Comment by waynejnicklin** [comment]
Thank you, that is working fine now! :-)
