### ISSUE TITLE
InvalidIdentityValues error when trying to update a resource with azapi_update_resource

### ISSUE THREAD

**Issue by carvarr** [Azure/terraform-provider-azapi#270]
I'm trying to add a feature that is missing in the azurerm provider within cosmosdb resource, this is my code:

resource "azapi_update_resource" "feature_fulltext_query" {
  type        = "Microsoft.DocumentDB/databaseAccounts@2022-11-15-preview"
  resource_id = azurerm_cosmosdb_account.db_account.id

  body = jsonencode({
    properties = {
      diagnosticLogSettings = {
        enableFullTextQuery = "True"
      }
    }
  })

  depends_on = [
    azurerm_cosmosdb_account.db_account
  ]
}

Expected behaviour:

Update should run successfully and the feature Diagnostics full-text query should be "on"

Actual behaviour:

I'm getting an error related with the user assigned identity that has the provisioned cosmosdb account.

`Error: creating/updating "Resource: (ResourceId \"/subscriptions/68212a61-c662-4f6c-bb44-4f910179bddb/resourceGroups/rg-gobrepo-persistence-dll-001/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-gobrepo-dll-bbc2\" / Api Version \"2022-11-15-preview\")": PUT https://management.azure.com/subscriptions/68212a61-c662-4f6c-bb44-4f910179bddb/resourceGroups/rg-gobrepo-persistence-dll-001/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-gobrepo-dll-bbc2
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidIdentityValues
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidIdentityValues",
│     "message": "Invalid value for the identities '/subscriptions/68212a61-c662-4f6c-bb44-4f910179bddb/resourcegroups/rg-gobrepo-persistence-dll-001/providers/Microsoft.ManagedIdentity/userAssignedIdentities/uai-cosmos-gobrepo-dll'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with module.cosmos.azapi_update_resource.feature_fulltext_query,
│   on .terraform/modules/cosmos/main.tf line 119, in resource "azapi_update_resource" "feature_fulltext_query":
│  119: resource "azapi_update_resource" "feature_fulltext_query" {
`

**Comment by ms-henglu** [comment]
Hi @carvarr ,

Thank you for taking time to report this issue!

The `azapi` provider is embedded with ARM API spec, and it's used in `azapi_update_resource` to remove the readonly fields. But the `Microsoft.DocumentDB/databaseAccounts@2022-11-15-preview` is not included in the v1.4.0 release: https://github.com/Azure/terraform-provider-azapi/tree/v1.4.0/internal/azure/generated/cosmos-db/microsoft.documentdb

Would you please try `Microsoft.DocumentDB/databaseAccounts@2022-08-15-preview`? And it's highly recommended to use [the azapi VSCode extension](https://marketplace.visualstudio.com/items?itemName=azapi-vscode.azapi), it provides language features like auto-complete, it's easy to know which types are available in the latest azapi provider.

**Comment by carvarr** [comment]
@ms-henglu thank you for your reply, I could apply the change using the API versión suggested. Regards.
