### ISSUE TITLE
azapi_resource randomly generates 'missing error information'

### ISSUE THREAD

**Issue by John-ltf** [Azure/terraform-provider-azapi#277]
We are using azapi provider (version 1.4.0) because of a limitation in azurerm provider that couldn't set azurerm_app_service_certificate_binding referencing a certificate stored in a KeyVault in a different subscription.

However, the 'azapi_resource' resource sometimes generates the following error:

E`rror: creating/updating "Resource: (ResourceId \"/subscriptions/.../resourceGroups/.../providers/Microsoft.Web/certificates/my-certificate-90e09913\" / Api Version \"2022-03-01\")": missing error information`

The terraform configuration that we use:
```
resource "azapi_resource" "roles-certificate" {
  type = "Microsoft.Web/certificates@2022-03-01"

  name      = local.certificate_name
  parent_id = data.azurerm_resource_group.rg.id
  location  = data.azurerm_resource_group.rg.location

  ignore_missing_property = true
  ignore_casing           = true

  response_export_values = ["id", "name", "properties.keyVaultId", "properties.keyVaultSecretName"]

  body = jsonencode({
    "properties" : {
      "keyVaultId" : data.azurerm_resources.internal_resource.id,
      "keyVaultSecretName" : local.certificate_name
    }
  })
}
```

**Comment by ms-henglu** [comment]
Hi @John-ltf ,

Thank you for taking time to report this issue! I guess it's similar with https://github.com/Azure/terraform-provider-azapi/issues/195.

As a workaround, would you please make this request via Postman to see the actual error? Thanks!

**Comment by John-ltf** [comment]
Hi @ms-henglu,

That helped. We found the root cause.

Thanks for the help. You can close the issue

**Comment by ms-henglu** [comment]
Great! I'll close this issue but feel free to reopen it if there's further question.
