### ISSUE TITLE
Can AzApi be told to wait for long running operations?

### ISSUE THREAD

**Issue by xximjasonxx** [Azure/terraform-provider-azapi#281]
We are using AzApi to deploy an Azure API Management instance, but often for some operations (hostname configuration) the deployment action will complete in the terminal before the service update is complete in Azure.

Question:
Is this intended? I confess I do not recall if this is simply because ARM (via AzApi) operates different from AzureRM (using Rest APIs) or if there is an option I am missing.

Thanks in advance

**Comment by ms-henglu** [comment]
Hi @xximjasonxx ,

Thank you for taking time to open this issue!

Azapi does wait for long running operations. My guess in this case is that the API might not implement by the ARM API guideline which means the LRO finished but the deployment is still in progress. And Azapi also manages resources by Rest APIs.

Would you please share some details on this API?

Thanks!

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.

**Comment by jsabo** [comment]
@ms-henglu creating a virtual wan virtual hub and automatically creating the vnet connection and bgp peers fails trying to create the bgp connections because terraform succeeds and moves on before the router provisioning state is successful. 
```

azapi_resource.vhub-bgpconnection-2: Creating...
╷
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/****/resourceGroups/sabo-vwan/providers/Microsoft.Network/virtualHubs/sabo-vwan-vhub/bgpConnections/sabo-vwan-vhub-bgpconnection-1\" / Api Version \"2023-04-01\")": PUT https://management.azure.com/subscriptions/****/resourceGroups/sabo-vwan/providers/Microsoft.Network/virtualHubs/sabo-vwan-vhub/bgpConnections/sabo-vwan-vhub-bgpconnection-1
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: HubBgpConnectionParentHubMustHaveProvisionedRoutingState
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "HubBgpConnectionParentHubMustHaveProvisionedRoutingState",
│     "message": "HubBgpConnection /subscriptions/****/resourceGroups/sabo-vwan/providers/Microsoft.Network/virtualHubs/sabo-vwan-vhub/bgpConnections/sabo-vwan-vhub-bgpconnection-1 cannot be created or updated because parent Virtual Hub /subscriptions/****/resourceGroups/sabo-vwan/providers/Microsoft.Network/virtualHubs/sabo-vwan-vhub RoutingState is not Provisioned.",
│     "details": []
│   }
│ }
│ -----------------------------
```
