### ISSUE TITLE
`ipSecurityRestrictionsDefaultAction` does not modify Unmatched Rule Action for App Service Networking

### ISSUE THREAD

**Issue by latiosu** [Azure/terraform-provider-azapi#284]
When using AzAPI provider for Terraform to set the "Unmatched rule action" to "Dent" in the App Service networking, the documented field `ipSecurityRestrictionsDefaultAction` (see [docs](https://learn.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions?tabs=azurecli#change-unmatched-rule-action-for-main-site)) makes no changes the App Service networking rules.
![image](https://user-images.githubusercontent.com/7020503/234443313-538ed79f-74e4-4423-944c-6769fe8618d5.png)

**Reproduction Steps**
1. Create a resource group
2. Create an Linux Web App
3. Modify existing resource group & web app with following TF:
```terraform
resource "azapi_update_resource" "wa_public_network_access_rules" {
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = <web_app_name>
  parent_id = <resource_group_id>

  body = jsonencode({
    properties = {
      publicNetworkAccess = "Enabled"
      siteConfig = {
        ipSecurityRestrictionsDefaultAction = "Deny"
      }
    }
  })
}
```

**Expected Outcome**
Unmatched rule action is changed to "Deny".
![image](https://user-images.githubusercontent.com/7020503/234444208-c7d2ae99-7d8c-405a-8d8a-be530848b74e.png)

**Actual Outcome**
Unmatched rule action is unchanged and remains as default value of "Allow".
![image](https://user-images.githubusercontent.com/7020503/234444358-430d3b73-0d14-4473-8ac3-e74c0697c5e4.png)

**Comment by WhiteRabbit-Code** [comment]
Same occurs for me. This could lead to a critical security issue if it is mistakenly set to 'Allow'.

This was already mentioned in [#20331](https://github.com/hashicorp/terraform-provider-azurerm/issues/20331), but not fixed there.

**Comment by ms-henglu** [comment]
Thanks @gittyNico , I'll close this issue as it's resolved, but feel free to reopen it if there's any question.
