### ISSUE TITLE
Plan fails in local environment when `use_oidc` is true

### ISSUE THREAD

**Issue by buzztaiki** [Azure/terraform-provider-azapi#287]
If `use_oidc` is true, the plan failed with `failed to obtain a credential: invalid tenantID` in environments where OIDC is disabled, such as the local environment.

In the same environment, the plan succeeds in the case of `azurerm`.

There seems to be the following differences between `azurerm` and `azapi` when `use_oidc` is true
- `azurerm`: if `tenantID` is empty, OIDC is not used
  - https://github.com/hashicorp/go-azure-sdk/blob/6c35830c310553a1bf686822e287cc9309c42f4c/sdk/auth/auth.go#L93
- `azapi`: use OIDC even if `tenant_id` is empty
  - https://github.com/Azure/terraform-provider-azapi/blob/6775698b76a99b53be1afac398f9fa7f82fd834a/internal/provider/provider.go#L330

## Example hcl
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.54.0"
    }
    azapi = {
      source  = "Azure/azapi"
      version = "~> 1.5.0"
    }
  }
}

provider "azurerm" {
  features {}
  use_oidc = true
}

provider "azapi" {
  use_oidc = true
}

resource "azurerm_resource_group" "main" {
  name     = "test"
  location = "japaneast"
}

resource "azapi_resource" "main" {
  type      = "Microsoft.App/managedEnvironments@2022-03-01"
  parent_id = azurerm_resource_group.main.id
  location  = azurerm_resource_group.main.location
  name      = "test"

  body = jsonencode({
    properties = {}
  })
}
```

## Actual behavior
```
❯❯ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # azurerm_resource_group.main will be created
  + resource "azurerm_resource_group" "main" {
      + id       = (known after apply)
      + location = "japaneast"
      + name     = "test"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: failed to obtain a credential: invalid tenantID. You can locate your tenantID by following the instructions listed here: https://docs.microsoft.com/partner-center/find-ids-and-domain-names
│
│   with provider["registry.terraform.io/azure/azapi"],
│   on main.tf line 19, in provider "azapi":
│   19: provider "azapi" {
│
╵
```

## Expected behavior
Plan should be successful.

## Workaround
Use `ARM_USE_OIDC` environment variable.
https://github.com/Azure/terraform-provider-azapi/blob/6775698b76a99b53be1afac398f9fa7f82fd834a/internal/provider/provider.go#L152

**Comment by ms-henglu** [comment]
Hi @buzztaiki ,

Thank you for taking time to report this issue!

Yes, the auth behavior is a little different between `azapi` and `azurerm`, it seem that `azurerm` will use `azure cli` when OIDC is not available. We'll improve it, thanks!

**Comment by ms-henglu** [comment]
I'll close this issue since it's resolved, please feel free to reopen it, thanks!
