### ISSUE TITLE
Can AzAPI support Microsoft.Quota?

### ISSUE THREAD

**Issue by articice** [Azure/terraform-provider-azapi#290]
I want to build preconditions in Terraform for provisioning instances with `create_before_destroy` lifecycle, checking for quotas.
There's an [Azure Quota Service API](https://learn.microsoft.com/en-us/rest/api/quota/) in preview (2021-03-15-preview).
I've registered it using 
```
Register-AzResourceProvider -ProviderNamespace Microsoft.Quota
```

and requests like 
```
GET https://management.azure.com//subscriptions/{subscription ID}/providers/Microsoft.Compute/locations/northeurope/providers/Microsoft.Quota/quotas?api-version=2021-03-15-preview
```
seem to be working.

Is it possible to parse this JSON using AzAPI?

ps: actually, I also want checks for HDInsight Cores quota, but that is not supported by this preview API version.

**Comment by ms-henglu** [comment]
Hi @articice ,

Thank you for taking time to report this issue!

Yes, you can do it with azapi provider. I also found a bug in this case, actually `azapi` should be able to auto-register the required resource provider, but `Microsoft.Quota` returns an incorrect error code, so you must register this resource provider manually. I've created an issue to track it: https://github.com/Azure/azure-sdk-for-go/issues/20823

Here's an full example:
```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_provider_registration" "test" {
  name = "Microsoft.Quota"
}

data "azapi_resource" "test" {
  type                   = "Microsoft.Quota/quotas@2021-03-15-preview"
  parent_id              = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/providers/Microsoft.Compute/locations/northeurope"
  name                   = "DiskEncryptionSetCount"
  response_export_values = ["*"]
  depends_on             = [azurerm_resource_provider_registration.test]
}

output "o1" {
  value = jsondecode(data.azapi_resource.test.output)
}
```
And you'll see the output is:
```hcl
Outputs:

o1 = {
  "id" = "/subscriptions/{subscription_id}/providers/Microsoft.Compute/locations/northeurope/providers/Microsoft.Quota/quotas/DiskEncryptionSetCount"
  "name" = "DiskEncryptionSetCount"
  "properties" = {
    "isQuotaApplicable" = false
    "limit" = {
      "limitObjectType" = "LimitValue"
      "limitType" = "Independent"
      "value" = 5000
    }
    "name" = {
      "localizedValue" = "DiskEncryptionSets"
      "value" = "DiskEncryptionSetCount"
    }
    "properties" = {}
    "unit" = "Count"
  }
  "type" = "Microsoft.Quota/Quotas"
}
```

**Comment by articice** [comment]
Thanks a lot, it worked!
Do you know if other resource types will be supported by a newer version of this API?

Also, if anyone is interested, I found a way to get HDInsight quotas, as per [HDInsight Locations](https://learn.microsoft.com/en-us/rest/api/hdinsight/2021-06-01/locations/get-capabilities) request:

```
data "azurerm_client_config" "current" {}

data "azapi_resource" "hdinsight_cores" {
  type = "Microsoft.HDInsight/locations@2021-06-01"
  parent_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  response_export_values = ["quota.coresUsed", "quota.maxCoresAllowed"]
  name = "northeurope/capabilities"
}

output "out" {
  value = jsondecode(data.azapi_resource.hdinsight_cores.output).quota
}
```

**Comment by ms-henglu** [comment]
Hi @articice - Sadly I'm not sure, please check the quota RP documents about the supported resource types.
