### ISSUE TITLE
Feature request: `azapi_resource_action` not flexible enough to register resource providers or get provider data

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#299]
## Scenario:

Customer wants to pre-register resource providers using azapi.

Customer also wants to get provider data using provider api.

I realise that azapi will try to do this for any resource that it tries to deploy https://github.com/Azure/terraform-provider-azapi/issues/82#issuecomment-1095709598

However this does not cover the customer scenario where they want to pre-register providers for another team to use (perhaps not with TF). OR when a customer wants to get provider data to determine availability zone support for resources.

## Attempted configuration:

```terraform
resource "azapi_resource_action" "provreg" {
  resource_id = "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute"
  type        = "Microsoft.Resources/providers@2021-04-01"
  method      = "POST"
  action      = "register"
}
```

I tried this but the HTTP Client within the provider changed the URL to this. You see it inserted the supplied `type` into the request:

```
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "message": "No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Resources/providers/Microsoft.Compute/register?api-version=2021-04-01'."
│ }
│ --------------------------------------------------------------------------------
```

## Solution requested:

I would like more control over the REST request to enable a request to a URI of my choosing, in this case: `/subscriptions/{subscriptionId}/providers/{resourceProviderNamespace}/register?api-version=2021-04-01`.

AND 

GET `/subscriptions/{subscriptionId}/providers/{resourceProviderNamespace}?api-version=2021-04-01`

It would be good if there was an additional attribute for both data and managed resource `azapi_resource_action`... like this:

### Managed resource

```terraform
resource "azapi_resource_action" "provreg" {
  uri         = "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/register"
  api_version = "2021-04-01"
  method      = "POST"
  body        = jsonencode({})
}
```

### Data source

```terraform
# This gets the output from the compute provider
# This us useful in allowing us to find if a resource supports
# availability zones or not
data "azapi_resource_action" "compute_provider" {
  uri                    = "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute"
  api_version            = "2021-04-01"
  response_export_values = ["*"]
  method                 = "GET"
}

output "compute_provider" {
  value = jsondecode(data.azapi_resource_action.compute_provider.output)
}
```

ref: https://learn.microsoft.com/en-us/rest/api/resources/providers/register

/cc @jtracey93

**Comment by matt-FFFFFF** [comment]
I have made a draft attempt at what this could look like in #300

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thank you for taking time to report this issue and making a PR for it!

I have a workaround to bypass the azapi type validation:

```hcl
data "azurerm_client_config" "current" {}

resource "azapi_resource_action" "test" {
  type        = "Microsoft.Resources/subscriptions@2021-04-01"
  resource_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  action      = "/providers/Microsoft.Network/register"
  method      = "POST"
}

data "azapi_resource_action" "test" {
  type                   = "Microsoft.Resources/subscriptions@2021-04-01"
  resource_id            = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  action                 = "/providers/Microsoft.Network"
  method                 = "GET"
  response_export_values = ["*"]
}

output "o1" {
  value = jsondecode(data.azapi_resource_action.test.output)
}
```

The weird part of above solution is that the `2021-04-01` might not be a valid version for `Microsoft.Resources/subscriptions` resource, it's the api-version used to register the Network RP.

I'm thinking that it might be easier to use, if we introduce resource provider types, for example, "Microsoft.Network@2021-04-01", then above solution will look like:

```hcl
data "azurerm_client_config" "current" {}

resource "azapi_resource_action" "test" {
  type        = "Microsoft.Network@2021-04-01"
  resource_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/providers/Microsoft.Network"
  action      = "register"
  method      = "POST"
}

data "azapi_resource" "test" {
  type                   = "Microsoft.Network@2021-04-01"
  resource_id            = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/providers/Microsoft.Network"
  response_export_values = ["*"]
}

output "o1" {
  value = jsondecode(data.azapi_resource.test.output)
}
```

**Comment by matt-FFFFFF** [comment]
Thanks for the reply @ms-henglu 

I will try the workaround!

The GET call in the data source in your example doesn't actually use the network resource provider. It's serviced by the `providers` api, with its own API version: https://learn.microsoft.com/en-us/rest/api/resources/Providers/Get?tabs=HTTP

It's this same API that is responsible for provider registration too.

I think it would be really useful to have an option to have full control over the URIs for azapi_resource_action. Perhaps we can use another resource called `azapi_rest_action` or similar...

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Sorry for the late update.

This feature has been supported in the latest azapi release v1.8.0. For the API to register a provider or fetch its information, we take the provider ID as a resource ID, and its type is `Microsoft.Resources/providers`, then you manage it like a normal resource.

Here's an example for registering a resource provider and fetch its data:

```hcl

data "azurerm_client_config" "current" {}

resource "azapi_resource_action" "test" {
  type        = "Microsoft.Resources/providers@2021-04-01"
  resource_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/providers/Microsoft.Network"
  action      = "register"
  method      = "POST"
}

data "azapi_resource" "test" {
  type = "Microsoft.Resources/providers@2021-04-01"
  parent_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  name = "Microsoft.Network"
  response_export_values = ["*"]
}

output "o1" {
  value = jsondecode(data.azapi_resource.test.output)
}
```

**Comment by matt-FFFFFF** [comment]
Thanks for the update @ms-henglu much appreciated
