### ISSUE TITLE
Question: Can i use this to authenticate and make a call to *azurewebsites.net?

### ISSUE THREAD

**Issue by riemers** [Azure/terraform-provider-azapi#307]
So basicly, currently i have this line:

`az rest --method post --uri "https://whatever-p-func.azurewebsites.net/api/TriggerFunctionJoin" --body @~/payload.json --resource "https://management.core.windows.net"`

Which works just well, it uses the authentication of the logged in user does its thing. Only with azapi it expects a resource type which of course this does not have.

Is the only way to create a custom provider for terraform and add authentication/token support in there too? I hate to have to authenticate twice if i don't have too. 

Any tips on how to get this 'terraformed' is welcome. Thanks!

p.s. have used the azapi for terraform before to set perm ip's and other things and worked like a charm.

**Comment by ms-henglu** [comment]
Hi @riemers ,

Thank you for taking time to report this issue and apologize for late response.

This API is from data-plane(the url host is some resource's endpoint) and it triggered an action, unfortunately it is not supported in azapi provider. 

We're working on the data plane support, and now the azapi provider supports limited set of data plane resources, refs: https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_data_plane_resource#available-resources

**Comment by riemers** [comment]
Too bad, but understandable for now, i'll close the ticket since this won't be in here any time soon. Thanks for your time.
