### ISSUE TITLE
AzAPI provider dows not support parameter "alias"

### ISSUE THREAD

**Issue by adammontlake** [Azure/terraform-provider-azapi#308]
When working with multiple subscriptions in Azure, you need a way to specify which subscription to deploy to.
AzureRM (and most other providers) allow you to specify multiple providers, and give them aliases, so that you can deploy the resource to the correct subscription.

AzAPI does not support this functionality, so need to specify the subscription ID manually which of course is cumbersome, and not always possible.

- AzAPI supported [arguments](https://registry.terraform.io/providers/Azure/azapi/latest/docs)
- Terraform on using multiple [providers](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations)

**Comment by ms-henglu** [comment]
Hi @adammontlake ,

Thank you for taking time to report this issue!

The AzAPI provider does support alias feature, because it's a Terraform feature and it's not recorded in the AzAPI document, here's an example:

```hcl
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azapi" {
  alias = "one"
  default_location = "westus"
}

provider "azapi" {
  alias = "two"
  default_location = "westeurope"
}


resource "azapi_resource" "rg" {
  type      = "Microsoft.Resources/resourceGroups@2020-06-01"
  parent_id = "/subscriptions/{subscription_id}"
  name      = "one"
  body      = jsonencode({})
  
  provider = azapi.one
}


resource "azapi_resource" "rg1" {
  type      = "Microsoft.Resources/resourceGroups@2020-06-01"
  parent_id = "/subscriptions/{subscription_id}"
  name      = "two"
  body      = jsonencode({})
  
  provider = azapi.two
}

```

For multi subscription deployment in Azure, AzAPI has more flexibility, because it can deploy resources in multiple subscriptions with one provider definition.

You can use reference in `parent_id` fields, then you only need to specify the subscription_id for the top-level resource, for example: resource group.

```hcl

resource "azapi_resource" "rg1" {
  type      = "Microsoft.Resources/resourceGroups@2020-06-01"
  parent_id = "/subscriptions/{subscription_one_id}"
  name      = "henglutwo"
}

resource "azapi_resource" "vnet1" {
  type      = "Microsoft.Network/virtualNetworks@2023-02-01"
  parent_id = azapi_resource.rg.id
  name      = "vnet1"
}


resource "azapi_resource" "rg2" {
  type      = "Microsoft.Resources/resourceGroups@2020-06-01"
  parent_id = "/subscriptions/{subscription_two_id}"
  name      = "henglutwo"
}

resource "azapi_resource" "vnet2" {
  type      = "Microsoft.Network/virtualNetworks@2023-02-01"
  parent_id = azapi_resource.rg2.id
  name      = "vnet2"
}

```

**Comment by adammontlake** [comment]
Thank you @ms-henglu, this is very useful and a great explanation.
Please consider adding this to the official documentation, I think it would be very useful to many people.

Appreciate you taking the time to write this.

**Comment by ms-henglu** [comment]
I'll close this issue, please feel free to reopen it if there's further question.
