### ISSUE TITLE
How to get list of all resource groups filtered by tags?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/terraform-provider-azapi#309]
Can someone share the terraform script block. I am unable to figure out the script to get all resource groups filtered by tags

**Comment by ms-henglu** [comment]
Hi @smartaquarius10 ,

Thank you for taking time to report this issue and apologize for late response.

Here's an example of using `Microsoft.ResourceGraph` API to filter the resources:
```hcl

data "azapi_resource_action" "test" {
  type        = "Microsoft.ResourceGraph@2020-04-01-preview"
  resource_id = "/providers/Microsoft.ResourceGraph"
  action      = "resources"
  body = jsonencode({
    query = <<-KQL
resourcecontainers
| where type == "microsoft.resources/subscriptions/resourcegroups"
| where tags["CreatedBy"] != ""
| take 10
    KQL
  })
  response_export_values = ["*"]
}

output "o1" {
  value = jsondecode(data.azapi_resource_action.test.output)
}

```

API docs: https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2020-04-01-preview)/resources/resources?tabs=HTTP
Azure Portal: https://ms.portal.azure.com/#view/HubsExtension/ArgQueryBlade

related issue: https://github.com/Azure/terraform-provider-azapi/issues/311
