### ISSUE TITLE
How to correctly POST queries against `Microsoft.ResourceGraph/resources`

### ISSUE THREAD

**Issue by gettek** [Azure/terraform-provider-azapi#311]
Hi, really enjoying using the AzAPI module!

One slight issue I'm having though is in the attempt of running a `POST` method on ["Microsoft.ResourceGraph/resources@2021-03-01"](https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2020-04-01-preview)/resources/resources?tabs=HTTP). It will be **super beneficial** for my use case, as I'm sure for many others, if we could retrieve ARG Query results at runtime.

Finding the correct `resource_id` scope and/or `action` property is what I'm scratching my head around, and apologies in advance if this is an obvious fix.

Both `data.azapi_resource_action` and `resource.azapi_resource_action` have similar results...

#### Snippet
```hcl
terraform {
  required_version = ">= 1.4"
  required_providers {
    azapi = {
      source  = "azure/azapi"
      version = ">=1.7.0"
    }
  }
}

# Retrieve resource graph query results
data "azapi_resource_action" "run_argq" {
  type        = "Microsoft.ResourceGraph/resources@2021-03-01"
  resource_id = "/"
  body = jsonencode({
    properties = {
      query = file("${path.module}/query.kql")
    }
  })
  response_export_values = ["data"]
}

```

#### Result
```bash
Error: invalid resource ID: /Microsoft.ResourceGraph/resources/tenants
```

#### Snippet with Root Management Group as resource_id

```hcl
# Retrieve resource graph query results
data "azapi_resource_action" "run_argq" {
  type        = "Microsoft.ResourceGraph/resources@2021-03-01"
  resource_id = "/providers/Microsoft.Management/managementGroups/${data.azurerm_client_config.current.tenant_id}"
  body = jsonencode({
    properties = {
      query = file("${path.module}/query.kql")
    }
  })
  response_export_values = ["data"]
}
```

#### Result
```bash
Error: `resource_id` and `type` are not matched, expect `type` to be Microsoft.Management/managementGroups, but got Microsoft.ResourceGraph/resources
```

Thanks in Advance

**Comment by gettek** [comment]
Thanks @ms-henglu, looking forward to the enhancements!

**Comment by ms-henglu** [comment]
Hi @gettek ,

The provider level action feature has been released in v1.8.0.

Here's an example, would you please give it a try? Thanks!

```hcl
data "azapi_resource_action" "test" {
  type        = "Microsoft.ResourceGraph@2020-04-01-preview"
  resource_id = "/providers/Microsoft.ResourceGraph"
  action      = "resources"
  body = jsonencode({
    query = "resources| where name contains \"test\""
  })
  response_export_values = ["*"]
}
```

**Comment by gettek** [comment]
Hi @ms-henglu, many thanks for actioning this so quickly!

After a quick test its excellent to see returning results but there seems a slight issue with output formatting which will prevent filtering of properties as both columns and rows are segregated. For example we cannot select output objects such as: `jsondecode(data.azapi_resource_action.test.output).data.some_property` see below:

#### `jsondecode(data.azapi_resource_action.test.output)`
```json
{
"data": {
    "columns": [
      {
        "name": "resourceId",
        "type": "string"
      },
      {
        "name": "status",
        "type": "integer"
      },
      {
        "name": "age",
        "type": "integer"
      }
    ],
    "rows": [
      [
        "/subscriptions/....", 
        "active",
        391
      ],
      [
        "/subscriptions/....", 
        "active",
        393
      ]
    ]
  }
}
```

#### Output should be like original POST ops
```json
{
"data": [
    {
      "age": 391,
      "status": "active",
      "resourceId": "/subscriptions/...."
    },
    {
      "age": 393,
      "status": "active",
      "resourceId": "/subscriptions/...."
    }
  ]
}
```

**Comment by ms-henglu** [comment]
Hi @gettek ,

Yes, there's a field to control the output format: https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2020-04-01-preview)/resources/resources?tabs=HTTP&tryIt=true&source=docs#resultformat

```hcl
data "azapi_resource_action" "test" {
  type = "Microsoft.Resources/providers@2020-04-01-preview"
  resource_id = "/providers/Microsoft.ResourceGraph"
  action = "resources"
  body = jsonencode({
    query = "resources| take 10"
    options = {
      resultFormat = "objectArray"
    }
  })
  response_export_values = ["*"]
}
```

**Comment by gettek** [comment]
Hi @ms-henglu, sorry I overlooked that in the docs this is great, many thanks for your help!
