### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by oleksandr-ivanov-ah** [Azure/terraform-provider-azapi#330]
I am trying to deploy Rapid7 security extensions:

```hcl
terraform {
  required_version = "~> 1.4"
    azapi = {
      source  = "azure/azapi"
      version = "~> 1.8"
    }
  }

}

resource "azapi_resource" "rapid7" {
  type = "Microsoft.Security/locations/securitySolutions@2015-06-01-preview"
  parent_id = "/subscriptions/0000000-0000-0000-0000-000000000/resourceGroups/rg-terraform-prd-weeu-01/providers/Microsoft.Security/locations/westcentralus"
  schema_validation_enabled = false

  name                      = var.name

  body = jsonencode({
    Properties = {
      Location               = "westcentralus",
      Template               = "rapid7.insightplatform"
      ProvisioningParameters = "{\"licenseCode\":\"${var.rapid7_base64_license}\",\"publicKey\":\"${var.rapid7_public_key}\",\"autoUpdate\":\"true\"}"
    }
  })
```
It adds  Rapid7 security extensions but fails with error:
```bash
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to azapi_resource.rapid7, provider "provider[\"registry.terraform.io/azure/azapi\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by ms-henglu** [comment]
Hi @oleksandr-ivanov-ah ,

Thank you for taking time to report this issue!

I couldn't deploy this resource because there're some requisites. But I guess it's caused by the upstream API, would you please share me some request traces, so I could continue investigate?
Here's how: https://developer.hashicorp.com/terraform/internals/debugging

And here's a workaround to bypass the API issue:

```hcl
resource "azapi_resource_action" "rapid7" {
  type = "Microsoft.Security/locations/securitySolutions@2015-06-01-preview"
  resource_id = "/subscriptions/ac516b91-6abc-48df-95ac-4bbf7f33937b/resourceGroups/rg-terraform-prd-weeu-01/providers/Microsoft.Security/locations/westcentralus/securitySolutions/${var.name}"
  
  method = "PUT"

  body = jsonencode({
    Properties = {
      Location               = "westcentralus",
      Template               = "rapid7.insightplatform"
      ProvisioningParameters = "{\"licenseCode\":\"${var.rapid7_base64_license}\",\"publicKey\":\"${var.rapid7_public_key}\",\"autoUpdate\":\"true\"}"
    }
  })
}
```

**Comment by oleksandr-ivanov-ah** [comment]
@ms-henglu it works, but it is a workaround.  I would appreciate it if you fix the bug in azapi_resource

**Comment by ms-henglu** [comment]
@oleksandr-ivanov-ah , Yes, I'll continue looking into it, it seems to be an issue on the API side.

**Comment by oleksandr-ivanov-ah** [comment]
@ms-henglu  I have Azure Resources that was deployed by the ARM/Bicep. I going to import them and noticed that there is no options for importing azapi_resource_action. 
Do you have any updates about the fix for the azapi_resource ?

**Comment by ms-henglu** [comment]
Hi @oleksandr-ivanov-ah , `azapi_resource_action` is only used to perform an HTTP request, so there's no use to import them into the state, because it doesn't monitor anything and it won't be triggered again unless you change the configuration.

**Comment by ms-henglu** [comment]
Hi @oleksandr-ivanov-ah , sorry for late update, if you have resources deployed by other client tools like ARM/bicep, I think you could use the `azapi_resource` for importing. This issue should not happen for imported resources.

**Comment by ms-henglu** [comment]
Close this issue as it's resolved, but feel free to reopen it if there's any question.
