### ISSUE TITLE
azapi_update_resource_group

### ISSUE THREAD

**Issue by mpjtaylor** [Azure/terraform-provider-azapi#331]
Wondering if its possible to update resource group for a resource group that isn't in my state and I haven't created using azapi or azurerm.

Use case could be 
tags

**Comment by ms-henglu** [comment]
Hi @mpjtaylor ,

Thank you for taking time to report this issue!

Here's an example config for your case, hope it could help you.
```hcl
resource "azapi_update_resource" "test" {
  type        = "Microsoft.Resources/resourceGroups@2022-09-01"
  resource_id = "/subscriptions/{subscription_id}/resourceGroups/{resource_group_name}"
  body = jsonencode({
    tags = {
      "newKey" = "newValue"
    }
  })
}
```

**Comment by mpjtaylor** [comment]
Thanks, yes this works missed this
