### ISSUE TITLE
Model Validation Error - nodeType must be the first property in the JSON property bag

### ISSUE THREAD

**Issue by heoelri** [Azure/terraform-provider-azapi#333]
Hi there, I'm facing an issue deploying a private preview service with `Azure/azapi` in version `1.8.0`. The service expects a certain order of the properties in the JSON property bag and it seems like TF or azapi is re-ordering them.

Here's the property bag:

```hcl
resource "azapi_resource" "example_resource" {
  type      = "Microsoft.xxx/xxx@2022-11-01-preview"
  name      = "ahm-example-with-sai"

  schema_validation_enabled = false # embedded schema validation is not yet available

  parent_id = azurerm_resource_group.example.id # use the resource group as the parent
  location  = azurerm_resource_group.example.location # same location as the resource group

  identity {
    type = "SystemAssigned" # use a system-assigned identity (default)
  }
  body = jsonencode({
    properties = {
     activeState: "Inactive" # set the active state to Inactive (default)
     refreshInterval: "PT1M"  # set the refresh interval to 1 minute (default)
     nodes: [
      {
        nodeType: "AggregationNode"
        nodeId: "0" # the root node always needs to be no. 0
        name: "ahm-example-with-sai"
        impact: "Standard"
        childNodeIds: [
          "1"
        ]
        visual: {
          x: 345
          y: 45
        }
      },
      {
        nodeType: "AggregationNode"
        nodeId: "1" # needs to be a unique value (string)
        name: "New system component"
        impact: "Standard"
        childNodeIds: []
        visual: {
          x: 345
          y: 65
        }
      },
     ]
    }
  })

  response_export_values = [ "*" ] # export all response values
}
```

```console
--------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: Bad Request
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "Bad Request",
│     "message": "Validation Error",
│     "details": [
│       {
│         "code": "Model Validation Error",
│         "message": "$.properties.nodes[0].nodeType: nodeType must be the first property in the JSON property bag."
│       }
│     ]
│   }
│ }
```

Is there a way to configure that to force jsonencode to maintain the provided order?

**Comment by heoelri** [comment]
Based on what I've read here: https://github.com/hashicorp/terraform/issues/27880 I thought that not using `jsonencode()` might help to preserve the given order, but it seems like that's not the case:

```hcl
resource "azapi_resource" "example_resource" {
  type      = "Microsoft.xxx/xxx@2022-11-01-preview"
  name      = "ahm-example-with-sai"

  schema_validation_enabled = false # embedded schema validation is not yet available

  parent_id = azurerm_resource_group.example.id # use the resource group as the parent
  location  = azurerm_resource_group.example.location # same location as the resource group

  identity {
    type = "SystemAssigned" # use a system-assigned identity (default)
  }
  body = <<-JSON
  {
    "properties": {
      "activeState": "Inactive", 
      "refreshInterval": "PT1M",
      "nodes": [
        {
          "nodeType": "AggregationNode",
          "nodeId": "0",
          "name": "ahm-example-with-sai",
          "impact": "Standard",
          "childNodeIds": [
            "1"
          ],
          "visual": {
            "x": 345,
            "y": 45
          }
        }
      ]
    }
  }
  JSON

  response_export_values = [ "*" ] # export all response values
}
```

Results in:

```console
# azapi_resource.example_resource will be updated in-place
  ~ resource "azapi_resource" "example_resource" {
      ~ body                      = jsonencode(
          ~ {
              ~ properties = {
                  + nodes           = [
                      + {
                          + childNodeIds = [
                              + "1",
                            ]
                          + impact       = "Standard"
                          + name         = "ahm-example-with-sai"
                          + nodeId       = "0"
                          + nodeType     = "AggregationNode"
                          + visual       = {
                              + x = 345
                              + y = 45
                            }
                        },
                    ]
                    # (2 unchanged attributes hidden)
                }
            }
        )
```

Is there any known solution to preserve the order of my json?

**Comment by ms-henglu** [comment]
Hi @heoelri ,

Thank you for taking time to report this issue!

I think there're multiple questions:

1. About the "nodeType must be the first property in the JSON property bag"
I believe this is an API bug. The API should not rely on the order of JSON. Is it possible to report it to the feature owner?

2. How to preserve the order of json?
`jsonencode` func will reorder the properties. Using heredoc JSON string could preserve the order.

3. > azapi_resource.example_resource will be updated in-place

Because the JSON that the API returned doesn't match with configuration, terraform wants to update the resource. It seems that there're 3 nodes defined in the config, but the API only has two.

**Comment by heoelri** [comment]
Thank you very much @ms-henglu. 

> 1. About the "nodeType must be the first property in the JSON property bag"
>    I believe this is an API bug. The API should not rely on the order of JSON. Is it possible to report it to the feature owner?

I agree, it would be better if the API would not require a certain order.

> 2. How to preserve the order of json?
>    `jsonencode` func will reorder the properties. Using heredoc JSON string could preserve the order.

Why does my second example, [here](https://github.com/Azure/terraform-provider-azapi/issues/333#issuecomment-1674294973), not work then?

**Comment by ms-henglu** [comment]
> Why does my second example, https://github.com/Azure/terraform-provider-azapi/issues/333#issuecomment-1674294973, not work then?

It does preserve the JSON order, so the resource is created. But what stored in the API is different from what you defined in the configuration, then terraform want to update the resource. 

Would you please try to use Postman to call GET API on this resource? So we could check the state in the API.

**Comment by ms-henglu** [comment]
I'll close this issue as there's no response, but feel free to reopen this issue if there's any question.
