### ISSUE TITLE
Error: resource_id and type are not matched when using azapi_update_resource

### ISSUE THREAD

**Issue by mimyz** [Azure/terraform-provider-azapi#344]
Hello,

I've encountered a problem that could either be an issue with Azure's API or with the azapi provider - not sure. Currently I am trying to toggle [Malware scanning for Storage](https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-malware-scan) on a specific storage account. Here is the code:

```
resource "azapi_update_resource" "example" {
  type        = "Microsoft.Security/defenderForStorageSettings@2022-12-01-preview"
  resource_id = azurerm_storage_account.example.id

  body = jsonencode({
    properties = {
        isEnabled: true,
        malwareScanning: {
            onUpload: {
                isEnabled: true,
                capGBPerMonth: 5000
            },
            scanResultsEventGridTopicResourceId: azurerm_eventgrid_topic.example.id
        },
        sensitiveDataDiscovery: {
            isEnabled: true
        },
        overrideSubscriptionLevelSettings: true
    }
  })

  depends_on = [
    azurerm_storage_account.example,
    azurerm_eventgrid_topic.example
  ]
}
```

Running this results in the resource_id and type are not matched error. For type I have tried `Microsoft.Security/defenderForStorageSettings`, `Microsoft.Security/pricings`, `Microsoft.Storage/storageAccounts`. The latter of which is able to run, but not successfully enable malware scanning.

One of the issues I potentially see is malware scanning isnt handled by the `Microsoft.Storage/storageAccount` provider, but by some other azurerm resource which isn't in the state.

Another concern is the mismatch of URLs in Microsofts Documentation as noted on their [Learn article](https://learn.microsoft.com/en-us/azure/defender-for-cloud/advanced-configurations-for-malware-scanning#rest-api) compared to the [API reference](https://learn.microsoft.com/en-us/rest/api/defenderforcloud/defender-for-storage/create?tabs=HTTP)

Any suggestions would be appreciated!

**Comment by ms-henglu** [comment]
Hi @mimyz ,

Thank you for taking time to report this issue!

Here's an example:
```hcl
resource "azurerm_resource_group" "test" {
  name     = "henlgu95"
  location = "eastus"
}

resource "azurerm_storage_account" "test" {
  name                     = "henlgu95"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_kind             = "BlobStorage"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azapi_update_resource" "defenderForStorageSetting" {
  type      = "Microsoft.Security/defenderForStorageSettings@2022-12-01-preview"
  parent_id = azurerm_storage_account.test.id
  name      = "current"
  body = jsonencode({
    properties = {
      isEnabled = true
      malwareScanning = {
        onUpload = {
          capGBPerMonth = 5000
          isEnabled     = true
        }
      }
      sensitiveDataDiscovery = {
        isEnabled = true
      }
      overrideSubscriptionLevelSettings = true
    }
  })
}

```

**Comment by mimyz** [comment]
Hi,

Thanks for the suggestion. I have been toying around with your sample for a bit, and I am finding some success it isn't quite turning on malware scanning. However I did notice that when I would try to re-apply the plan. terraform would note:
![image](https://github.com/Azure/terraform-provider-azapi/assets/143206077/b1223cd5-6a36-4d1b-bdae-dc8f4e6124ba)
though it never does turn it to true.

Additionally, I tried an alternate method suggested by Microsoft to no avail either:

```hcl
resource "azurerm_storage_account" "example" { ... }

resource "azapi_resource_action" "enable_defender_for_Storage" {
  type        = "Microsoft.Security/defenderForStorageSettings@2022-12-01-preview"
  resource_id = "${azurerm_storage_account.example.id}/providers/Microsoft.Security/defenderForStorageSettings/current"
  method      = "PUT"

  body = jsonencode({
    properties = {
      isEnabled = true
      malwareScanning = {
        onUpload = {
          isEnabled     = true
          capGBPerMonth = 5000
        }
      }
      sensitiveDataDiscovery = {
        isEnabled = true
      }
      overrideSubscriptionLevelSettings = true
    }
  })
}
```
