### ISSUE TITLE
How to ignore_body_changes for nested properties

### ISSUE THREAD

**Issue by jkroepke** [Azure/terraform-provider-azapi#352]
I want to setup an vm gallery, however I would like to ignore properties inside a list:

```
  ~ resource "azapi_resource" "gallery_application_version_linux" {
      ~ body                      = jsonencode(
          ~ {
              ~ properties = {
                  ~ publishingProfile = {
                      ~ targetRegions      = [
                          ~ {
                              ~ name                 = "West Europe" -> "westeurope"
                                # (2 unchanged attributes hidden)
                            },
                        ]
                        # (8 unchanged attributes hidden)
                    }
                    # (1 unchanged attribute hidden)
                }
            }
        )
        id                        = "/subscriptions/***/resourceGroups/rg-dev-opsstack-westeurope-001/providers/Microsoft.Compute/galleries/DEV_GAL_OPSSTACK_WESTEUROPE_001/applications/opsstack-agent-linux/versions/1.1.0"
        ignore_body_changes       = [
            "properties.publishingProfile.source.media_link",
            "properties.publishingProfile.targetRegions.*.name",
        ]
        name                      = "1.1.0"
        # (9 unchanged attributes hidden)
    }
```

I tired `properties.publishingProfile.targetRegions.*.name`, however it seems like it has not affect.

**Comment by gianrubio** [comment]
I quickly read the the code and the provider does not seem to support the [override of specific item in list. ](https://github.com/Azure/terraform-provider-azapi/blob/fc1aa615439b62d6da33463c05293619f834e08f/utils/json.go#L157)

**Comment by ms-henglu** [comment]
Hi @jkroepke ,

Thank you for taking time to report this issue and apologize for late response.

Thanks @gianrubio for answering the question, and yes, the provider doesn't support the override of specific item in the list.


More details: https://github.com/Azure/terraform-provider-azapi/issues/315#issuecomment-1716943998

**Comment by jkroepke** [comment]
My from point of view, this can be archived by using json path at the ignore property.

**Comment by mvanhil** [comment]
Adding the following snippet to the azapi_resource doesn't work as intented. Just like @jsheetzmt pointed out.

ignore_body_changes = ["properties.template.containers[0].image"]

**Comment by aleksanderJunge** [comment]
@mvanhil @jsheetzmt I am trying to accomplish the same thing, however it overwrites the existing container app image despite having the line:
 ignore_body_changes = [ "properties.template.containers[0].image" ] 

what did you change to make it work?

**Comment by koldyba** [comment]
> I was doing something wrong. It works as expected for me

Could you please provide some example of working config? @mvanhil 
It seems it should not work: https://github.com/Azure/terraform-provider-azapi/issues/315 

For me it does not work either, have tried following:

`ignore_body_changes = ["properties.template.containers[0].image"]`
`ignore_body_changes = ["properties.template.containers[\"job_name\"].image"]`
`ignore_body_changes = ["properties.template.containers"]`

**Comment by deen-nitj** [comment]
I am also trying to achieve same thing. For me it did not work with 
ignore_body_changes = ["properties.template.containers"]

Getting the error as below.

**Error: ignoring specific item in list is not supported**

@mvanhil : Can u please share configuration if it is working for you.

**Comment by mvanhil** [comment]
In the meanwhile I migrated all the azapi stuff to the modified TF resources. I was missing the workload profile feature, but since that has been added, I migrated everything over. A lot easier now. :-)

**Comment by deen-nitj** [comment]
@mvanhil: Thanks for your quick response.

**Comment by ms-henglu** [comment]
Close this issue as it's completed, but feel free to reopen it if there's any question.
