### ISSUE TITLE
azapi_resource does not honour the Terraform count condition

### ISSUE THREAD

**Issue by ro6it** [Azure/terraform-provider-azapi#355]
Facing issue while using the Terraform count condition for creation of resources on a condition but instead of checking the condition it is asking to use the count.index in the block, I mean it should not behave like this.

`resource "azapi_resource_action" "ssh_public_key_gen" {
  count =  var.admin_ssh_key_path == null ? 1 : 0
  type        = "Microsoft.Compute/sshPublicKeys@2022-11-01"
  resource_id = azapi_resource.ssh_public_key.id
  action      = "generateKeyPair"
  method      = "POST"

  response_export_values = ["publicKey", "privateKey"]
}`

╷
│ Error: Missing resource instance key
│ 
│   on ssh.tf line 8, in resource "azapi_resource_action" "ssh_public_key_gen":
│    8:   resource_id = azapi_resource.ssh_public_key.id
│ 
│ Because azapi_resource.ssh_public_key has "count" set, its attributes must be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     azapi_resource.ssh_public_key[count.index]

**Comment by ms-henglu** [comment]
Hi @ro6it ,

Thank you for taking time to open this issue and apologize for late response.

From the error message, it seems that the `azapi_resource.ssh_public_key` has "count" set. So the `azapi_resource.ssh_public_key` is actually an array, you need to add index, for example:

```hcl

resource "azapi_resource_action" "ssh_public_key_gen" {
  count       = var.admin_ssh_key_path == null ? 1 : 0
  type        = "Microsoft.Compute/sshPublicKeys@2022-11-01"
  resource_id = azapi_resource.ssh_public_key[0].id
  action      = "generateKeyPair"
  method      = "POST"

  response_export_values = ["publicKey", "privateKey"]
}
```

**Comment by ms-henglu** [comment]
Close this issue as it's resolved, but feel free to reopen it if there's any question.
