### ISSUE TITLE
Links to guides seem to be broken in the terraform registry

### ISSUE THREAD

**Issue by Tiberriver256** [Azure/terraform-provider-azapi#356]
Click on any of these links:
![image](https://github.com/Azure/terraform-provider-azapi/assets/6989492/eeed5f55-c7ca-4739-8490-af2ae71dd1e9)

Result:

![image](https://github.com/Azure/terraform-provider-azapi/assets/6989492/dd905153-7a8d-4ffe-9f6f-b738c0f03243)

**Comment by ms-henglu** [comment]
Hi @Tiberriver256 ,

Thank you so much for taking time to report this issue!

I've opened a PR to fix it.
