### ISSUE TITLE
Timeout on authenticating with Managed Identity

### ISSUE THREAD

**Issue by TZdybel** [Azure/terraform-provider-azapi#358]
Recently I have encountered couple of errors regarding authentication with Managed Identity when running plan with AzAPI resources in it. I am using a VM that is running multiple terraform plans in parallel so there might be a situation when bunch of authorization requests from AzAPI resources may be send almost at once and throttled because of that.

Error I get looks like this
```
Error: reading "Resource: (ResourceId \"/subscriptions/xxxxx/providers/Microsoft.Security/securityContacts/default\" / Api Version \"2020-01-01-preview\")": ChainedTokenCredential: failed to acquire a token.
Attempted credentials:
	managed identity timed out
	AzureCLICredential: ERROR: Tenant shouldn't be specified for managed identity account
```

I was trying to make it "retry" with AzureCLICredentials but after I set it up I got above error about tenant, that shouldn't be set.

Some time ago we had similar throttling issues with azurerm and azuread providers but both of them were fixed by changing library that was used to authenticate. For example, here's a PR for azuread - https://github.com/hashicorp/terraform-provider-azuread/pull/1026

I would greatly appreciate digging into that issue 😃

**Comment by ms-henglu** [comment]
Hello @TZdybel ,

Thank you for taking time to report this issue and apologize for late response.

We'll investigate and fix this issue.

**Comment by ostcrom** [comment]
Bumping because I am also experiencing this issue.
