### ISSUE TITLE
Remove tag from subscription

### ISSUE THREAD

**Issue by Satak** [Azure/terraform-provider-azapi#365]
I know I can add tag keys and values but how do I remove tag key?

I can add tags like this:
```tf
resource "azapi_update_resource" "subscription_tags" {
  for_each = var.tags

  type      = "Microsoft.Resources/tags@2022-09-01"
  parent_id = each.value.id
  name      = "default"

  body = jsonencode({
    properties = {
      tags = each.value.tags
    }
  })
}
```

But once tag is set I can not remove it. Let's say there was a type in the configuration and I want to remove the typo key and then add the corrected key. How to do this? Is it even possible?

**Comment by ms-henglu** [comment]
Hello @Satak ,

Thank you for taking time to report this issue and apologize for late response.

The `azapi_update_resource` will combine the tags key in the config with the tags key in the remote, so you couldn't remove a tag key by it.

Here's a workaround, by using the `azapi_resource_action` to make a PUT request to set the final state for the tags.

```hcl

// we use the data source to get the resource id of the tags resource
data "azapi_resource_id" "tags" {
  type = "Microsoft.Resources/tags@2023-07-01"
  parent_id = "some resource id"
  name = "default"
}

resource "azapi_resource_action" "put_tags" {
  type = "Microsoft.Resources/tags@2023-07-01"
  resource_id = data.azapi_resource_id.tags.id
  method = "PUT"
  body = jsonencode({
    properties = {
      tags = {
        key2 = "value2"
      }
    }
  })
}
```

**Comment by Satak** [comment]
Yes this is working as expected. There is a small caveat in this and that is tags set outside Terraform. Even if I use `PUT` method it doesn't remove tags that are set outside Terraform, for example manually from console and this doesn't see the drift. So I had to first use the `DELETE` method to wipe out all existing tags and then set the tags with Terraform by the `PUT` method. `POST` method is apparently not supported.

**Comment by ms-henglu** [comment]
Thanks for the updated solution, I'll close this issue as it's resolved. But feel free to reopen it if there's any question.
