### ISSUE TITLE
How to set `deleteEmptyServerFarm` for resource type `Microsoft.Web/sites`

### ISSUE THREAD

**Issue by antonioc74** [Azure/terraform-provider-azapi#375]
Unable to set parameter `deleteEmptyServerFarm` on resource type `Microsoft.Web/sites`.

This parameter is documented: https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/delete?view=rest-appservice-2022-03-01#uri-parameters

In the example provided, there is no mention of the parameter: https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web_sites%402022-09-01/main.tf

Is it possible to set this parameter `deleteEmptyServerFarm`?

**Comment by ms-henglu** [comment]
I'll close this issue as it's duplicated with https://github.com/Azure/terraform-provider-azapi/issues/223
