### ISSUE TITLE
azapi_data_plane_resource: Support Microsoft.KeyVault/vaults/certificates

### ISSUE THREAD

**Issue by jkroepke** [Azure/terraform-provider-azapi#379]
Hi,

I would like to managed Key Vault certificates via azapi

**Comment by ms-henglu** [comment]
Hi @jkroepke ,

Thank you for taking time to report this issue!

Sadly the APIs used to manage key vault certificates have a complicated pattern, we'll work on supporting more data plane APIs like them.

**Comment by ms-henglu** [comment]
Close this issue as it's out of azapi's support scope, but feel free to reopen it if there's any question.
