### ISSUE TITLE
Error adding custom domain to ACA through azapi

### ISSUE THREAD

**Issue by AstridBro** [Azure/terraform-provider-azapi#380]
I went into the step to set up the customDomain and it requires me to have a self-signed certificate. I did try and successfully generate a new certificate in Azure Key Vault and upload my own certificate into Azure Key Vault. 

But when running the pipelines to deploy app environment, it shows this error as the image below

![47b0a980-6e87-4fc0-b084-d3792ffd5c87](https://github.com/Azure/terraform-provider-azapi/assets/22913402/30235271-542b-47f3-b76d-dfd149632569)

"Certificate must contain one private key".

I have tried uploading the certificate and adding the custom domain from the portal. And it works nicely.
It works fine when using Azure CLI as well, but using azapi there might be a bug here.

**Comment by ms-henglu** [comment]
I'll close this issue as there's no response, but feel free to reopen this issue if there's any questions.
