### ISSUE TITLE
https://registry.terraform.io/providers/Azure/azapi/latest/docs links to data-sources and resources are broken

### ISSUE THREAD

**Issue by warrenackerman** [Azure/terraform-provider-azapi#381]
Documentation regarding the [Data Sources](https://registry.terraform.io/docs/configuration/data-sources) and [Resources](https://registry.terraform.io/docs/configuration/resources) supported by the AzAPI Provider can be found in the navigation to the left.

The links above appear to be broken at the moment.

**Comment by ms-henglu** [comment]
Hi @warrenackerman ,

Thank you for taking time to open this issue!

The link you shared are https://registry.terraform.io/docs/configuration/data-sources and https://registry.terraform.io/docs/configuration/resources, they're not related with `azapi` provider.

Would you please try the below link and its left navigation?
https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource

**Comment by ms-henglu** [comment]
Close this issue as it's resolved, but feel free to reopen it if there's any question.
