### ISSUE TITLE
`ignore_body_changes` not working with azapi_update_resource for failover group

### ISSUE THREAD

**Issue by kmoravcik** [Azure/terraform-provider-azapi#386]
I have the following block:
```
resource "azapi_update_resource" "failover_group_upd" {
  type        = "Microsoft.Sql/servers/failoverGroups@2021-11-01"
  resource_id = data.azapi_resource.failover_group.id

  body = jsonencode({
    properties = {
      databases = concat(jsondecode(data.azapi_resource.failover_group.output).properties.databases, [data.azurerm_mssql_database.sql_database_fd.id])
    }
  })

  ignore_body_changes = ["properties.databases"]

  depends_on = [
    data.azurerm_mssql_database.sql_database_fd,
  ]
}
```

I added the   ignore_body_changes       = ["properties.databases"] line because currently Im dealing with an issue where my backup server is set as the active one and azure does not allow to perform modifications on the secondary server.

I wanted to overcome this problem using the ignore_body_changes but its not working for me.

Terraform fails with the following output:

```
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: FailoverGroupUpdateOrDeleteRequestOnSecondary
--------------------------------------------------------------------------------
{
  "error": {
    "code": "FailoverGroupUpdateOrDeleteRequestOnSecondary",
    "message": "Modifications to the failover group are not allowed on a secondary server. Execute 
  }
}
```

Is this a bug or am I using it incorrectly ?

**Comment by ms-henglu** [comment]
Hi @kmoravcik ,

Thank you for taking time to report this issue and apologize for late response.

With `ignore_body_changes` specified, the `databases` will still be set in the payload, the value is the current value in the remote.

There're other ways that might fix this issue:
1. Comment out the `databases = ...` line, the `azapi_update_resource` will make no changes to the resource.
2. Set `count = 0` to the `azapi_update_resource`, then no actions will be taken when you apply the config.

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.
