### ISSUE TITLE
AzAPI Microsoft.AVS/privateClouds data resource gives unrecognized API version when using valid API's

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/terraform-provider-azapi#389]
When trying to use the data azapi_resource for Microsoft.AVS/privateClouds resources, the valid API's located at https://learn.microsoft.com/en-us/azure/templates/microsoft.avs/privateclouds?pivots=deployment-language-terraform return an error "400 bad Request".  These api's work find for the regular azapi_resource, just not any of the data sources.  

Example tested is below.   I also tested the azapi_resource_list resource and it failed with the same error. 

`data "azapi_resource" "avs_test" {
    type = "Microsoft.AVS/privateClouds@2021-06-01"
    name = "test"
    parent_id = var.privatecloud_id
}`

**Comment by ms-henglu** [comment]
Hi @jchancellor-ms ,

Thank you for taking time to report this issue and apologize for late response.

I guess the `var.privatecloud_id` is the ID of an existing private cloud resource, if so, the config should be:

```hcl
data "azapi_resource" "avs_test" {
  type        = "Microsoft.AVS/privateClouds@2021-06-01"
  resource_id = var.privatecloud_id
}
``` 

And here're other examples to use the data source for private cloud resources:
```hcl
data "azapi_resource" "avs_test" {
  type      = "Microsoft.AVS/privateClouds@2021-06-01"
  name      = "private_cloud_name"
  parent_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg_name"
}

data "azapi_resource_list" "listPrivateCloudsByResourceGroup" {
  type      = "Microsoft.AVS/privateClouds@2021-06-01"
  parent_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg_name"
}

data "azapi_resource_list" "listPrivateCloudsBySubscription" {
  type      = "Microsoft.AVS/privateClouds@2021-06-01"
  parent_id = "/subscriptions/00000000-0000-0000-0000-000000000000"
}
```

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.
