### ISSUE TITLE
Bump AKS API Version

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/terraform-provider-azapi#395]
# Bumping the AKS Preview and GA APIS 
I work on the AKS Team on NodeAutoProvisioning. We added a flag to our preview api, but many customers are saying the latest version of the terraform API is about 6 months old. 

SEE:  https://github.com/Azure/karpenter/issues/80#issuecomment-1875700877 

Would it be possible to bump the AKS API versions of the teraform-provider? What are the steps to move forward there? 

Thanks!

**Comment by Bryce-Soghigian** [comment]
cc: [nfsouzaj](https://github.com/nfsouzaj)

**Comment by ms-henglu** [comment]
Hello @Bryce-Soghigian ,

Thank you for taking time to report this issue!

The docs are not update to date, but the `azapi` provider does support the latest `2023-10-02-preview`, here's an example of how to use the node provisioning profile:

```hcl

resource "azapi_resource" "rg" {
  type     = "Microsoft.Resources/resourceGroups@2020-06-01"
  name     = "henglu0109aks"
  location = "westeurope"

}
resource "azapi_resource" "cluster" {
  type      = "Microsoft.ContainerService/managedClusters@2023-10-02-preview"
  parent_id = azapi_resource.rg.id
  name      = "henglu0109aks"
  location  = "westeurope"
  identity {
    type = "SystemAssigned"
    identity_ids = []
  }
  
  body = jsonencode({
    properties = {
      agentPoolProfiles = [
        {
          count  = 1
          mode   = "System"
          name   = "default"
          vmSize = "Standard_DS2_v2"
        },
      ]
      nodeProvisioningProfile = {
        mode = "Auto"
      }
      dnsPrefix = "henglu0109aks"
    }
  })
}

**Comment by Bryce-Soghigian** [comment]
Thank you @ms-henglu
