### ISSUE TITLE
Microsoft.Subscription/aliases: changes to tags are not updated Azure. 

### ISSUE THREAD

**Issue by jain-ranjith** [Azure/terraform-provider-azapi#396]
We are using azapi to provision provision new subscriptions.
These subscriptions are created with provided tag inputs. However, if we change the value for `tags` the plan shows the difference and apply succeeds, but these new values are not updated in subscriptions.

Steps to reproduce:

Create a new subscription,

main.tf:
```
resource "azapi_resource" "new_subscription" {
  type      = "Microsoft.Subscription/aliases@2021-10-01"
  name      = random_uuid.alias_uuid.result
  parent_id = "/"
  body = jsonencode({
    properties = {
      additionalProperties = {
        managementGroupId    = data.azurerm_management_group.mg.id
        subscriptionOwnerId  = local.subscriptionOwnerId
        subscriptionTenantId = data.azurerm_client_config.current.tenant_id
        tags = {
          env = "test"
        }
      }
      billingScope = data.azurerm_billing_mca_account_scope.example.id
      displayName  = local.displayName
      workload     = "Production"
    }
  })
}
```

subscription is created with tag `{ env = "test" }`.

Change configuration by updating the tag (modify or delete or add a new tag).

main.tf:
```
resource "azapi_resource" "new_subscription" {
  type      = "Microsoft.Subscription/aliases@2021-10-01"
  name      = random_uuid.alias_uuid.result
  parent_id = "/"
  body = jsonencode({
    properties = {
      additionalProperties = {
        managementGroupId    = data.azurerm_management_group.mg.id
        subscriptionOwnerId  = local.subscriptionOwnerId
        subscriptionTenantId = data.azurerm_client_config.current.tenant_id
        tags = {
          env   = "test-modified"
		  owner = "new owner"
        }
      }
      billingScope = data.azurerm_billing_mca_account_scope.example.id
      displayName  = local.displayName
      workload     = "Production"
    }
  })
}

```
The plan shows as new tags to be updated.

plan:
```
 # azapi_resource.new_subscription will be updated in-place
  ~ resource "azapi_resource" "new_subscription" {
      ~ body                      = jsonencode(
          ~ {
              ~ properties = {
                  ~ additionalProperties = {
                      ~ tags                 = {
                          ~ env   = "test" -> "test-modified"
                          + owner = "new owner"
                        }
                        # (3 unchanged attributes hidden)
                    }
                    # (3 unchanged attributes hidden)
                }
            }
        )
```
		
		
Terraform apply succeeds. The terraform state shows new tag information.
But in reality, no changes are made to the subscription tags. The subscription still has the old tag. 

Any changes to tags (update existing tag, remove a tag, create new tag) show that changes are being applied. Terraform state gets updated.  But no changes are made to Azure resources.

**Comment by jain-ranjith** [comment]
The behavior is also the same for renaming or deleting subscriptions. Changes are made only to the terraform state, but no changes are made in real to the Azure subscription.

**Comment by ms-henglu** [comment]
Hi @jain-ranjith ,

Thank you for taking time to report this issue and apologize for late response.

Would you be able to update the `tags` by Postman? If so, please share me the request, then I could help you fix the config.

**Comment by ms-henglu** [comment]
I'll close this issue as there's no response, but feel free to reopen it if there's any questions.
