### ISSUE TITLE
Parameter name cannot be empty. - "ExtendedCode": "01014" BadRequest

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/terraform-provider-azapi#408]
I am getting the following error and cannot find what the issue is.
For the life of me i cannot find the missing/invalid parameter.
any thoughts?

Error: creating/updating "Resource: (ResourceId \"/subscriptions/<subid>/resourceGroups/<RSG>/providers/Microsoft.Web/sites/lgc-tstn-dev-abc123\" / Api Version \"2022-09-01\")": PUT https://management.azure.com/subscriptions/<subid>/resourceGroups/<RSG>/providers/Microsoft.Web/sites/lgc-tstn-dev-abc123
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE UNAVAILABLE
│ --------------------------------------------------------------------------------
│ {
│   "Code": "BadRequest",
│   "Message": "Parameter name cannot be empty.",
│   "Target": null,
│   "Details": [
│     {
│       "Message": "Parameter name cannot be empty."
│     },
│     {
│       "Code": "BadRequest"
│     },
│     {
│       "ErrorEntity": {
│         "ExtendedCode": "01014",
│         "MessageTemplate": "Parameter name cannot be empty.",
│         "Parameters": [],
│         "Code": "BadRequest",
│         "Message": "Parameter name cannot be empty."
│       }
│     }
│   ],
│   "Innererror": null
│ }

**Comment by ms-henglu** [comment]
Hi @AaronSaikovski ,

Thank you for taking time to report this issue!

I have an example of how to use the `Microsoft.Web/sites` resource, hope it could help you
https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web_sites%402022-09-01/main.tf

And about fixing your configuration, I think it's better to contact MS Support, they have a better domain knowledge about how to use each azure resources.

**Comment by ms-henglu** [comment]
I'll close this issue but feel free to reopen it if there's any questions.
