### ISSUE TITLE
How about changing the name to `Tricep`? :laughing:

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#41]
I thought that this project depends on ARM, Bicep, Terraform, I know it might not make much sense, just a wild idea. :laughing:

**Comment by lonegunmanb** [comment]
What about ["Magi"](https://en.wikipedia.org/wiki/Biblical_Magi)?

**Comment by ms-henglu** [comment]
@lonegunmanb , this reminds me of EVA, Magi is the name of the supercomputers.

**Comment by lonegunmanb** [comment]
Exactly!

**Comment by grayzu** [comment]
What do you think about **_azapi_**. It is short and to the point and kind of rolls off of the tongue. I know it is much more boring than Magi ;-)
