### ISSUE TITLE
parent_id is invalid route table

### ISSUE THREAD

**Issue by kaytharius** [Azure/terraform-provider-azapi#410]
I am attempting to deploy a route table with azapi and am getting the following error.

Error: `parent_id is invalid`: expect ID of `Microsoft.Network/routetables`
│
│   with azapi_resource.routetable,
│   on main.tf line 137, in resource "azapi_resource" "routetable":
│  137: resource "azapi_resource" "routetable" {

The parent_id that I am supplying is the resource group ID.  I am outputting the network resource group ID so I know it's correct.

Changes to Outputs:
  + network_rg_id             = "/subscriptions/{subscription}/resourceGroups/dev-ncus-mytestworkload-net-rg-01"
  
  Here is the sample of code.
  
  resource "azapi_resource" "routetable" {
  type             = "Microsoft.Network/routetables/@2023-04-01"
  name             = local.route_table_name
  parent_id        = local.network_rg_id
  location         = var.location
  tags             = var.subscription_tags
  body = jsonencode({
    properties = {
      disableBgpRoutePropagation = true
      routes = [
        {
          name = "default"
          properties = {
            addressPrefix = "0.0.0.0/0"
            hasBgpOverride = false
            nextHopIpAddress = "some IP"
            nextHopType = "VirtualAppliance"
          }
          #type = "string"
        },
        {
          name = "${local.vnet_name}_localvnet"
          properties = {
            addressPrefix = var.address_space
            hasBgpOverride = false
            nextHopIpAddress = "some IP"
            nextHopType = "VirtualAppliance"
          }
          #type = "string"
        }
      ]
    }
  })
}

The error seems like it's expecting a route table as a parent ID rather than a resource group ID. Any help would be appreciated.

**Comment by ms-henglu** [comment]
Hello @kaytharius ,

Thank you for taking time to report this issue!

I noticed that there's a redundant `/` in the type, it should be `type = "Microsoft.Network/routeTables@2023-04-01"`.

And here's an example: https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Network_routeTables%402022-09-01/main.tf

**Comment by kaytharius** [comment]
Thank you so much. I'm not sure how I missed that.
