### ISSUE TITLE
Action should not be re-executed when updating to provider to >= 1.11.0

### ISSUE THREAD

**Issue by juljaeg** [Azure/terraform-provider-azapi#411]
When updating the provider to a version equal or higher than 1.10.0 it shows a resource property being added:

```text
   # azapi_resource_action.aks_rotate_cluster_certificates[0] will be updated in-place
   ~ resource "azapi_resource_action" "aks_rotate_cluster_certificates" {
         id          = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx-aks/rotateClusterCertificates"
       + when        = "apply"
         # (5 unchanged attributes hidden)
     }
```

Unfortunately the action will be reexecuted which potentially breaks running systems (see example above with rotating certificates). As this is a modify action this should not have any consequences in terms of action execution.

**Comment by ms-henglu** [comment]
Hi @juljaeg ,

Thank you for taking time to report this issue and apologize for late response.

Apologize for this breaking change, to avoid executing the action, please add `when="apply"` to your configuration.

**Comment by rossmotley** [comment]
Adding `when="apply"` into the configuration didn't help me here, does it need to be added into the state?

**Comment by ms-henglu** [comment]
Hello @rossmotley , you're right. I have updated above comment, please check: https://github.com/Azure/terraform-provider-azapi/issues/411#issuecomment-1993718497

**Comment by rossmotley** [comment]
@ms-henglu I can confirm that the lifecycle ignore worked for me. I didn't know about this feature - thank you!

**Comment by ms-henglu** [comment]
Glad to see it's resolved. I'll close this issue but feel free to open it if there's any question.

**Comment by royveshovda** [comment]
There seems to be regression for me when upgrading to 1.13.0. Now the ignore_changes for `when` does not seem to work anymore
