### ISSUE TITLE
Update `azidentity` to correctly handle IMDS reachability when running in a docker container

### ISSUE THREAD

**Issue by J0F3** [Azure/terraform-provider-azapi#413]
When running in a docker container  `terraform plan` or `terraform apply` fails with a error regarding Managed Identity credentials:

```
│ Error: reading "Resource: (ResourceId \"/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.ApiManagement/service/<redacted>/policyFragments/<redacted>\" / Api Version \"2021-12-01-preview\")": ChainedTokenCredential authentication failed
│ GET http://169.254.169.254/metadata/identity/oauth2/token
│ --------------------------------------------------------------------------------
│ RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
│ --------------------------------------------------------------------------------
│ connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
│ --------------------------------------------------------------------------------
│
│
│   with azapi_resource.jfe-azapi-repo-iac,
│   on main.tf line 20, in resource "azapi_resource" "<redacted>":
│   20: resource "azapi_resource" "<redacted>" {
│
╵
```

There was a bug fix made in the Azure SDK which handles the error correctly so the next credential is tried: https://github.com/Azure/azure-sdk-for-go/issues/22274
Therefore the provider should update to the lastest version so the fix gets integrated and `terraform plan / apply` does not fail unexpected when running in a container on docker desktop.

Workaround: 
For those who also ran in this error there is a simple workaround for now. Just set the following environment variable before running terraform: 
`ARM_USE_MSI=false`

The default value is `true` so the provider will always try Managed Identity Credentials first, before Azure CLI Credentials when running locally. Because the IP address of the IMDS is somehow reachable when running in a container on docker desktop the provider will fail to get credentials and abort with the error.

Maybe it would be also a good idea to set the Managed Identity Credentials by default to `false` so it has explicitly to be enabled when Managed Identity is expected to be used.  Just like suggest here already: https://github.com/Azure/terraform-provider-azapi/issues/377

Thanks!

**Comment by ms-henglu** [comment]
Hi @J0F3 ,

Thank you for taking time to report this issue and apologize for late response.

Currently this feature is only included in a beta release of the `azidentity`: https://github.com/azure/azure-sdk-for-go/blob/main/sdk/azidentity/CHANGELOG.md#bugs-fixed-2

We'll update the `azidentity` once there's a stable release.

**Comment by J0F3** [comment]
Hi @ms-henglu 

Just accidently passed by here again😄 I think this this is fixed now as `azidentity` got updated in the meantime: https://github.com/Azure/terraform-provider-azapi/blob/5c44f394cb6c5456299580d617c4b3e87780882b/go.mod#L5
 
 So, I think it can be closed or what do you think?

**Comment by ms-henglu** [comment]
Thanks @J0F3 for checking this! I'll close this issue, feel free to reopen it if there's any questions.
