### ISSUE TITLE
Allow for authenticating to Azure using the Azure CLI

### ISSUE THREAD

**Issue by marcin478** [Azure/terraform-provider-azapi#414]
This is already supported by the [azurerm ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli) and [azuread](https://github.com/hashicorp/terraform-provider-azuread/pull/1266) providers.
It's required to solve the problem with the 10 minutes _idToken_ validity limitation when using [Workload Identity to Federation for Azure DevOps Service Connection](https://devblogs.microsoft.com/premier-developer/azure-devops-workload-identity-federation/).

**Comment by ms-henglu** [comment]
Hi @marcin478 ,

Thank you for taking time to report this issue and apologize for late response.

The `azapi` provider does support this feature, more details could be found here: https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/azure_cli

**Comment by srvmsr** [comment]
We are facing the same issue , azure cli auth works well when auzure cli is authenticated via Service principal client secret, however we get below error when we use [Workload Identity to Federation for Azure DevOps Service Connection](https://devblogs.microsoft.com/premier-developer/azure-devops-workload-identity-federation/). 


 "Error: reading "Resource: (ResourceId \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\" / Api Version \"2022-09-01\")": ChainedTokenCredential authentication failed
│ GET http://169.254.169.254/metadata/identity/oauth2/token
│ --------------------------------------------------------------------------------
│ RESPONSE 400 Bad Request
│ --------------------------------------------------------------------------------
│ {
│   "error": "invalid_request",
│   "error_description": "Identity not found"
│ }

At the same config , azurerm provider works well.
Provider config as below:

`
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.63.0"
    }
    azapi = {
      source = "Azure/azapi"
      version = "~> 1.8.0"
    }
  }
  backend "azurerm" {
  }
}

provider "azapi" {
  use_cli = true
}

provider "azurerm" {
  skip_provider_registration = true
  features {}
}

`

**Comment by sikksakk** [comment]
+1 to @srvmsr 
Using Workload Identity is not working.

**Comment by mkocaks** [comment]
+1 to @srvmsr Same issue for me :-(

**Comment by mkocaks** [comment]
Not tried to use OIDC option....

**Comment by mkocaks** [comment]
Also we have this with just using standard service connections in devops (not federated)

**Comment by ms-henglu** [comment]
Hi all,

Sorry for late update, this feature has been supported in the latest azapi release, more details could be found here: https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/service_principal_oidc

I'll close this issue as it's completed, but feel free to reopen it if there's any questions.
