### ISSUE TITLE
Ignore schema on azapi_update_resource

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-provider-azapi#422]
Doing this:

```hcl
resource "azapi_update_resource" "insights_custom_metrics" {
  type          = "microsoft.insights/components@2020-02-02"
  resource_id   = azurerm_application_insights.this.id
  ignore_casing = true

  body = jsonencode({
    properties = {
      "CustomMetricsOptedInType" = "WithDimensions"
    }
  })

  depends_on = [azurerm_application_insights.this]
}
```

yields no changes on the resource. (The property is an undocumented feature which is not declared in the schema).
However doing this:

```shell
az resource patch --id theResourceId --properties "{ \"CustomMetricsOptedInType\": \"WithDimensions\" }"
```

works just fine.

I suspect the azapi provider is verifying the schema and dropping undeclared properties? Would it be possible to add an ignore-flag for update like in create?

**Comment by davidkarlsen** [comment]
related to #285

**Comment by ms-henglu** [comment]
Hi @davidkarlsen ,

Thank you for taking time to open this issue!

The `azapi_update_resource` updates an existing resource by `PUT` http method, and it seems that this field could not be updated by `PUT`. Here's a workaround for that:

```
resource "azapi_resource_action" "insights_custom_metrics" {
  type        = "microsoft.insights/components@2020-02-02"
  resource_id = azurerm_application_insights.this.id
  method      = "PATCH"
  body = jsonencode({
    properties = {
      "CustomMetricsOptedInType" = "WithDimensions"
    }
  })
}
```

**Comment by davidkarlsen** [comment]
perfect - thanks a lot. Then I close this as it's not really tied to validation.
