### ISSUE TITLE
azapi_resource - If tags are managed by `azapi_resource`, and a new tag is introduced outside of Terraform, the whole body/resource gets replaced during the update operation

### ISSUE THREAD

**Issue by NikolaiKleppe** [Azure/terraform-provider-azapi#430]
## Scenario

* A resource is deployed to a target subscription with `azapi_resource`, and tags are used.
* The subscription has a policy in place which inherits tags from subscription to resources.
* The resource deployed by `azapi_resource` will have its tags changed, and this is reflected during Terraform Plan (where Environment was added by the policy):
   <img src="https://github.com/Azure/terraform-provider-azapi/assets/7556264/35dd551d-0791-450d-86d4-b1bde9f9044b" width=50% height=50%>
* Once Terraform Apply is run, any changes (that is a part of the body) that was made to this resource outside of Terraform will be lost. 

Why "any changes made to this resource **outside** of Terraform"? 

We have a few scenarios where we want end users to be able to modify resources deployed by Terraform - Normally in these cases you would use ignore_changes in `azurerm`.

`ignore_body_changes` does not work with tags.

I have tried to ignore all changes but properties are still replaced during the update operation:
```
ignore_body_changes  = [
   "*"
 ]
```

## Example

* Make changes to resource in Azure Portal - I've added email notification in an Action Group:
  <img src="https://github.com/Azure/terraform-provider-azapi/assets/7556264/58e59b76-47e3-42ca-947c-8500ac783c66" width=100% height=100%>

* Run Terraform Apply where tags are updated as shown above

* Properties are replaced:
  ![image](https://github.com/Azure/terraform-provider-azapi/assets/7556264/72246e39-b6d8-4129-98ba-f78d14611a8e)

  ![image](https://github.com/Azure/terraform-provider-azapi/assets/7556264/a7c485e9-3364-4549-8606-2d22555f2aff)

If the use of tags is removed from the terraform code then it works as expected as no update is being performed.

Same thing happens with Alert Processing Rules (`Microsoft.AlertsManagement/actionRules`) - If for example a schedule is set it will get deleted when tags are updated

## Resources

Tested with:

`Microsoft.Insights/actionGroups@2023-01-01`
`Microsoft.AlertsManagement/actionRules@2021-08-08`
`azure/azapi v1.12.1`

**Comment by ms-henglu** [comment]
Hi @NikolaiKleppe ,

Thank you for taking time to report this issue!

The terraform's native ignore change feature could also work on the top-level field "tags" like azurerm. Here's an example:

```
resource "azapi_resource" "rg" {
  type     = "Microsoft.Resources/resourceGroups@2023-07-01"
  name     = "henglu313rg"
  location = "westus"
  tags = {
    environment = "production"
  }
  lifecycle {
    ignore_changes = [
      tags,
    ]
  }
}
```

**Comment by NikolaiKleppe** [comment]
Hi @ms-henglu 

Thanks for the tip - Didn't think lifecycle was available in azapi :) I added it and this ignores tags as expected, thanks!

But is it expected behaviour that a tag update otherwise replaces other properties on the resource?

**Comment by ms-henglu** [comment]
Hi @NikolaiKleppe , glad to see it's resolved.

> But is it expected behaviour that a tag update otherwise replaces other properties on the resource?

No. 

For example, in this case:
> If for example a schedule is set it will get deleted when tags are updated

Please check if the azapi resource has the schedule defined in the config?

**Comment by NikolaiKleppe** [comment]
@ms-henglu I'll provide a minimal example. I tried commenting out the `schedule` block as well but result is the same.


```hcl

terraform {
  required_version = "~>1.0"
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~>3.0"
    }
    azapi = {
      source = "Azure/azapi"
      version = ">=1.9.0" # For "ignore_body_changes"
    }
  }
}

provider "azurerm" {
  features {
  }
}

provider "azapi" {}

data "azurerm_subscription" "current" {}

resource "azurerm_resource_group" "rg1" {
  name = "test-rg1"
  location = "westeurope"
}

resource "azapi_resource" "alert_processing_rule_standard" {

  type = "Microsoft.AlertsManagement/actionRules@2021-08-08"

  parent_id = azurerm_resource_group.rg1.id

  name      = "test_apr1"
  location  = "Global"

  tags      = {
    "myTag1" = "test_one"
    "myTag2" = "test_two"
  }

  body = jsonencode({
    properties = {
      #schedule = {}
      actions = [
        {
          actionType = "RemoveAllActionGroups" # This sets the rule to Suppress all alerts and should not be changed
        }
      ]
      conditions = [
        {
          field    = "AlertRuleName"
          operator = "Contains"
          values   = [
            "alert-"
          ]
        }
      ]
      description = "An Alert Processing Rule which is used to enable Maintenance Mode for the resources under the given scope."
      enabled     = false # MM Should be disabled by default, especially as the initial scope is set to the whole subscription
      scopes = [
        data.azurerm_subscription.current.id # Set scope to subscription ID
      ]
    }
  })

  schema_validation_enabled = false

  ignore_body_changes  = [
    "properties.schedule", # Schedule is set in Azure Portal
    "properties.enabled",  # The Enabled/Disabled field should be configurable in Azure Portal
    "properties.scopes",   # Scopes should be configured in Azure Portal for the relevant resources to be put under maintenance
  ]

}
```

## Add Tag and add a Schedule in portal

These are set by clicking Edit:

![chrome_9nEc3KzPjm](https://github.com/Azure/terraform-provider-azapi/assets/7556264/919b24f5-4c10-4777-bf3e-745354828098)


## Terraform Apply

Only tags are listed as will be updated:

![Code_URwMYwarPX](https://github.com/Azure/terraform-provider-azapi/assets/7556264/21c3b530-decc-42c8-b96f-8fb1a1e63f03)


## Result

Schedule and tag is removed

![chrome_fZJsPFna5t](https://github.com/Azure/terraform-provider-azapi/assets/7556264/91a8190b-a611-4f3a-8dbd-a59f4a77f7dd)

**Comment by ms-henglu** [comment]
Thanks for the details! It's a bug of the `ignore_body_changes` feature, I'll open a PR to fix it.
