### ISSUE TITLE
Add support for using Azure Dynamic Credentials

### ISSUE THREAD

**Issue by Mralbert93** [Azure/terraform-provider-azapi#435]
Currently, the `AzureRM` and `AzureAD` providers (maintained by HashiCorp) support using OIDC integration with Azure to get dynamic credentials. This request is to have a similar implementation on AzAPI which is maintained by Azure. 

This provider is frequently used by our customers to cover edge cases where there is not support in AzureRM or to workaround known issues. This change would allow customers to use already existing dynamic credentials which have been injected into the run.
 
It looks like this provider already supports authenticating via a `oidc_token_file_path`, but it does not support specifying a `client_id_file_path` which would be necessary. 

https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials/azure-configuration

**Comment by Mralbert93** [comment]
Please find the provider-sided implementation needed for dynamic credentials on our providers here:

AzureRM: https://github.com/hashicorp/terraform-provider-azurerm/pull/21764
AzureAD: https://github.com/hashicorp/terraform-provider-azuread/pull/1189

**Comment by ms-henglu** [comment]
Hi @Mralbert93 ,

Thank you for taking time to report this issue!

I'll work on this feature.

**Comment by Mralbert93** [comment]
Hi @ms-henglu ! I tested this and it looks like dynamic credentials are compatible with AzAPI. There should be no change needed here, so I am closing this out. Sorry for the false alarm! 

![image](https://github.com/Azure/terraform-provider-azapi/assets/61246987/cea797fb-76d5-423d-96e3-d0a60fffeab2)
![dynamiccredsevidence](https://github.com/Azure/terraform-provider-azapi/assets/61246987/92dee962-0d5c-4411-90a4-4d78179aed11)

**Comment by Mralbert93** [comment]
Re-opening this as this change is needed to support dynamic credentials w/ provider aliases. T
