### ISSUE TITLE
bug?: plan after apply does not produce clean output

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-provider-azapi#444]
Desired outcome is to be able to run Terraform Plan after an Apply & have it return 'no changes required'.

I've noticed with the container apps managed environment resource, that if you enable workload_profiles, you receive the following during the plan after apply.

It seems to be related to settings that are created during the enabling of the workload profile environment - e.g. the defaultDomain, infrastructureResourceGroup, etc.

```terraform
     ~ output                    = jsonencode(
            {
              - properties = {
                  - customDomainConfiguration   = {
                      - certificatePassword        = null
                      - certificateValue           = null
                      - customDomainVerificationId = "REDACTED"
                      - dnsSuffix                  = null
                      - expirationDate             = null
                      - subjectName                = null
                      - thumbprint                 = null
                    }
                  - defaultDomain               = "REDACTED.australiaeast.azurecontainerapps.io"
                  - infrastructureResourceGroup = "REDACTED"
                  - peerAuthentication          = {
                      - mtls = {
                          - enabled = false
                        }
                    }
                  - staticIp                    = "10.1.1.150"
                  - vnetConfiguration           = {
                      - dockerBridgeCidr       = null
                      - infrastructureSubnetId = "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/virtualNetworks/REDACTED/subnets/REDACTED"
                      - internal               = true
                      - platformReservedCidr   = null
                      - platformReservedDnsIP  = null
                    }
                  - workloadProfiles            = [
                      - {
                          - name                = "Consumption"
                          - workloadProfileType = "Consumption"
                        },
                    ]
                }
            }
```

I don't seem to be able to ignore these because i'm not able to include "outputs" in a lifecycle block.

There's an example of this in a CI run here; https://github.com/kewalaka/terraform-azurerm-avm-res-app-managedenvironment/actions/runs/8166972609/job/22326608745#step:5:412

I've noticed that the results when not using a workload profile is clean, so it seems to be these managed outputs which are polluting the output response?

I'm not sure if this is the right repo to raise this, either!

**Comment by ms-henglu** [comment]
Hi @kewalaka ,

Thank you for taking time to report this!

The root cause of above plan change is that there's a change inside body, but got hidden because there's sensitive value used in the `body`.

```
~ resource "azapi_resource" "this_environment" {
      ~ body                      = (sensitive value)
        id                        = "/subscriptions/***/resourceGroups/rg-yp16/providers/Microsoft.App/managedEnvironments/cae-yp16"
```

We're working on improving this and will release the improvement in the next release to avoid changes hidden in the plan.  And I have a workaround that might help you, you could use `nonsensitive` function to mark the body not sensitive to see the detailed plan change, but please notice this might cause credential leakage, please don't use it in the production environment, only for local testing.

**Comment by kewalaka** [comment]
this is resolved - example run shows "no changes to infrastructure"

https://github.com/kewalaka/terraform-azurerm-avm-res-app-managedenvironment/actions/runs/9039041360/job/24841252000#step:5:352
