### ISSUE TITLE
unexpected SHA-256 hash

### ISSUE THREAD

**Issue by lambohamp** [Azure/terraform-provider-azapi#461]
Hey. I am facing the following issue during executing `terraform init`:

```
Error while installing azure/azapi v1.13.0: checksum list has unexpected
SHA-256 hash 18e1464f3e11436f04f3fabd842a079d47a2d7b56489e8d920d9cd5156bbd52e
(expected 8170881d34e63fdade2a382c6b3d0bbbd68ffc0a1527835b4fc113cd8726acc6)
```

**Comment by lambohamp** [comment]
The issue is caused by my local misconfiguration (a wrong version of Terraform).

**Comment by BzSpi** [comment]
Hello @lambohamp 

what kind of misconfiguration did you have ? We're many to face it :).

**Comment by ms-henglu** [comment]
Hello @BzSpi , this issue may happen to some os platforms, I plan to make a patch release shortly to address some bugs in the v1.13.0 as well as this issue.

**Comment by stemaMSFT** [comment]
@lambohamp or @BzSpi would you mind sharing for our reference what version of Terraform you were previously on?
