### ISSUE TITLE
AzApi v1.13.0: Error: Provider produced invalid plan

### ISSUE THREAD

**Issue by jakaxd** [Azure/terraform-provider-azapi#463]
Since the release of 1.13.0, we are seeing the following error message when running terraform plan:

│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/azure/azapi" planned an invalid value for
│ azapi_resource.hierarchical_containers["app-004-transaction_hashes"].timeouts:
│ planned for existence but config wants absence.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

However going back to version 1.12.0 has appeared to fix the issue for us.

**Comment by ms-henglu** [comment]
Hi @jakaxd ,

Thank you for taking time to report this issue!

Would you please share us a complete config to help us investigate? Thanks!

**Comment by ms-henglu** [comment]
Thanks @jakaxd for the config, and you didn't use the `timeouts`, right?

**Comment by ms-henglu** [comment]
Sorry that I couldn't reproduce this issue, would you please share more details about problematic resource? Is it created by Terraform or imported into Terraform?

**Comment by ms-henglu** [comment]
This root cause is https://github.com/hashicorp/terraform/issues/32460, please upgrade to the latest terraform.

**Comment by stemaMSFT** [comment]
@jakaxd for our own reference, would you mind providing what version of Terraform you were previously on when you encountered the issue?
