### ISSUE TITLE
Breaking change in minor version 1.13

### ISSUE THREAD

**Issue by Felix-Franz** [Azure/terraform-provider-azapi#467]
According to [Semver](https://semver.org), breaking changes should only be included in major versions.
Since we are pinning to version `~> 1.0`, changes introduced in `1.13` broke our current Terrform automation.

**Comment by hejtmii** [comment]
Hi, we have the same problem and getting the following error while we don't use `tags` at all (we only use `properties`), and having `version = ">=1.9.0"` in our terraform config

```
embedded schema validation failed: the argument "body" is invalid:
`tags` is not expected here. Do you mean `properties`? 
 You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
```

**Comment by ms-henglu** [comment]
Hi @hejtmii , thanks for reporting this issue, it's the same as https://github.com/Azure/terraform-provider-azapi/issues/462.

**Comment by A7exSchin** [comment]
> Hi @Felix-Franz ,
> 
> Thank you for taking time to report this issue and apologize for the trouble.
> 
> Apologize again that we shouldn't include any breaking changes in a minor release. In this minor release, we introduce the dynamic properties which solves many pain points in the `azapi` provider, and want to bring this feature to the 1.x users.

Still, we as project maintainers should decide which features we want and if we need/want them we will upgrade. Pushing a breaking change in a minor version just is bad practice...

**Comment by tiwood** [comment]
@ms-henglu, can we expect a rollback?
Otherwise we have to adjust the pinning in all our projects as they broke with the latest minor release.

**Comment by 4c74356b41** [comment]
> Hi @Felix-Franz ,
> 
> Thank you for taking time to report this issue and apologize for the trouble.
> 
> Apologize again that we shouldn't include any breaking changes in a minor release. In this minor release, we introduce the dynamic properties which solves many pain points in the `azapi` provider, and want to bring this feature to the 1.x users.

thats cool, but how does this work? i only see breaking changes which seem to be irrelevant, however we do observe issues same as the people above see.

I can also add that for us it seems like location property never gets populated in some cases, doesnt matter what we put into it.

**Comment by ms-henglu** [comment]
Hi @4c74356b41, it seems to be a bug, would you please open another issue for it? So I could help you investigate and fix it.

**Comment by ms-henglu** [comment]
Hello @Felix-Franz , @tiwood ,

We have released v1.13.1, in this release, a new field called `enable_hcl_output_for_data_source` is introduced, which is used to enable the HCL output for the data source, the default value is `false`.
  This could resolve the following breaking changes in the previous release:
  - `azapi_resource` data source: The `output` field changes from JSON string to HCL object. Users can use access the fields in the output as an HCL object. Please remove the `jsondecode` function when using the `output` field.
  - `azapi_resource_list` data source: The `output` field changes from JSON string to HCL object. Users can use access the fields in the output as an HCL object. Please remove the `jsondecode` function when using the `output` field.
  
  Please notice if you already upgraded to `v1.13.0` and removed `jsondecode` function for the `output` of data sources, when upgrade to the `v1.13.1` release, you need to set `enable_hcl_output_for_data_source = true` in the `azapi` provider block to enable the HCL output for data sources.

**Comment by jchancellor-ms** [comment]
@ms-henglu - The schema for the provider doesn't seem to include the new enable_hcl_output_for_data_source.  Also, by issuing this as a bug fix that includes a breaking change it forces us to pin our version on 1.13.1 which means we can't follow our normal pattern of ~> 1.x versioning.  Can we please not push breaking changes in minor releases and bug fixes in the future?
![image](https://github.com/Azure/terraform-provider-azapi/assets/84210452/71235465-f5f2-4179-8228-d457ee74f8ca)

**Comment by ms-henglu** [comment]
Hi @jchancellor-ms , thanks for reporting this! This error comes from the Hashicorp Terraform extension, I guess it should be fixed if you run `terraform init -upgrade` to download the `v1.13.1` version and reload the VSCode.

> Also, by issuing this as a bug fix that includes a breaking change it forces us to pin our version on 1.13.1 which means we can't follow our normal pattern of ~> 1.x versioning. Can we please not push breaking changes in minor releases and bug fixes in the future?

Yes, we will improve our testing, version releasing, and breaking change handling processes to avoid this sort of issue from occurring again.

**Comment by fergoid** [comment]
> @ms-henglu - The schema for the provider doesn't seem to include the new enable_hcl_output_for_data_source. Also, by issuing this as a bug fix that includes a breaking change it forces us to pin our version on 1.13.1 which means we can't follow our normal pattern of ~> 1.x versioning. Can we please not push breaking changes in minor releases and bug fixes in the future? ![image](https://private-user-images.githubusercontent.com/84210452/326609289-71235465-f5f2-4179-8228-d457ee74f8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTA2NDUsIm5iZiI6MTcxNDQ5MDM0NSwicGF0aCI6Ii84NDIxMDQ1Mi8zMjY2MDkyODktNzEyMzU0NjUtZjVmMi00MTc5LTgyMjgtZDQ1N2VlNzRmOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTgwZjkzNjBiY2RkNTU1MGVlMjU3NzEzNDBiYTJlOTA2YWUyZjQwOGJmM2VmN2ZmODMyM2U5OWY3MmMwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9TFBmZ1x5egYggDd7dBHnSlXll7jJbK5opdmhdceAc)

I think you can do something like this "~> 1.0, != 1.13.0".  That should keep you on pessimistic versioning but skip the bad version

**Comment by jchancellor-ms** [comment]
> > @ms-henglu - The schema for the provider doesn't seem to include the new enable_hcl_output_for_data_source. Also, by issuing this as a bug fix that includes a breaking change it forces us to pin our version on 1.13.1 which means we can't follow our normal pattern of ~> 1.x versioning. Can we please not push breaking changes in minor releases and bug fixes in the future? ![image](https://private-user-images.githubusercontent.com/84210452/326609289-71235465-f5f2-4179-8228-d457ee74f8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTA2NDUsIm5iZiI6MTcxNDQ5MDM0NSwicGF0aCI6Ii84NDIxMDQ1Mi8zMjY2MDkyODktNzEyMzU0NjUtZjVmMi00MTc5LTgyMjgtZDQ1N2VlNzRmOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTgwZjkzNjBiY2RkNTU1MGVlMjU3NzEzNDBiYTJlOTA2YWUyZjQwOGJmM2VmN2ZmODMyM2U5OWY3MmMwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9TFBmZ1x5egYggDd7dBHnSlXll7jJbK5opdmhdceAc)
> 
> I think you can do something like this "~> 1.0, != 1.13.0". That should keep you on pessimistic versioning but skip the bad version

Thanks @fergoid  - Just learned something new as I wasn't aware of the option to exclude specific versions.  Let me give that a shot and see if I can stabilize my calling module around this issue.

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any question. Thanks.
