### ISSUE TITLE
Value Conversion Error

### ISSUE THREAD

**Issue by aravindmetla** [Azure/terraform-provider-azapi#470]
we are using below module file to deploy api connection.
// Creates eventgrid api connection with managedIdentity for logic app  to be used by workflow
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
  required_version = ">= 0.14"
}

resource "azapi_resource" "api_connecton_eventgrid" {
  type                      = "Microsoft.Web/connections@2018-07-01-preview"
  name                      = "${var.project_name}-arm"
  location                  = var.location
  parent_id                 = var.parent_id
  schema_validation_enabled = false
  tags = {
    project_name = var.project_name
  }

  body = jsonencode({
    properties = {
      api = {
        displayName = "Azure Resource Manager",
        id          = "/subscriptions/${var.subscription_id}/providers/Microsoft.Web/locations/${var.location}/managedApis/arm"
      }
      displayName        = "Azure Resource Manager",
      parameterValueType = "Alternative",
    }
  })
}

below is the part where we call the above module
module "arm_api_connection_emp" {
  source          = "../modules/api_connection/arm"
  project_name    = "emp"
  location        = var.location
  parent_id       = azurerm_resource_group.emp_logic_apps.id
  subscription_id = var.subscription_id
}

above configuration is working April 18th after which we have not deployed. Today when we are trying to deploy the same code we are getting below error
Error: Value Conversion Error

  with module.arm_api_connection_emp.azapi_resource.api_connecton_eventgrid,
  on ../modules/api_connection/arm/arm_api_connection.tf line 11, in resource "azapi_resource" "api_connecton_eventgrid":
  11: resource "azapi_resource" "api_connecton_eventgrid" {

An unexpected error was encountered trying to build a value. This is always
an error in the provider. Please report the following to the provider
developer:

Received unknown value, however the target type cannot handle unknown values.
Use the corresponding `types` package type or a custom type that handles
unknown values.

Path: ["project_name"]
Target Type: string
Suggested Type: basetypes.StringValue

anyone please suggest how to resolve this

**Comment by Narayan-Mitra** [comment]
@ms-henglu , May we know when permanent fixes will be released.

**Comment by Narayan-Mitra** [comment]
@ms-henglu , Thank you for sharing update, We will test and update here.
