### ISSUE TITLE
Cannot acquire token error using confirmed good client+cert

### ISSUE THREAD

**Issue by plk** [Azure/terraform-provider-azapi#478]
Using version 1.13.0, client cert and password plus `use_msi = false` in provider. Exactly the same settings, (client id, cert, password, tenant, subscription) that work fine in an `azurerm` provider.  Consistently get "failed to acquire token" just for the `azapi` provider. Nothing in the log about certificate problems.

**Comment by stemaMSFT** [comment]
Hey @plk thanks for the issue. Does rollback to v1.12.1 fix this issue? It may be similar to what we've seen in #475 but not 100% certain.

**Comment by plk** [comment]
Rollback to 1.12.1 fixes it ...

**Comment by ms-henglu** [comment]
Hello @plk ,

Thank you for taking time to report this issue!

The bug fix has been released in v1.13.1, would you please have a try? Thanks.

**Comment by plk** [comment]
Yes, v1.13.1 fixes the issue, thanks.

**Comment by ms-henglu** [comment]
Thanks for the confirming it! I'll close this issue but feel free to reopen it if there's any question.
