### ISSUE TITLE
Support authentication using encoded certificate bundle directly: [client_certificate]

### ISSUE THREAD

**Issue by loomkoom** [Azure/terraform-provider-azapi#488]
#### Description
The azapi provider documentation mentions that it supports service principal authentication using client certificates by using the [client_certificate_path](https://registry.terraform.io/providers/Azure/azapi/latest/docs#client_certificate_path), which contains the path of a `.pfx`/`.p12` file.

However, passing the client-certificate base64 encoded to the `client_certificate` value like in [azurerm](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#client_certificate) and [azuread](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#client_certificate) doesn't seem to be supported.

It would be nice for the **azapi** provider to also support this method of authentication through the extra `client_certificate` argument.

#### Error Log
```
Error: Unsupported argument

  on crossplane-provider-config.tf line 19, in provider "azapi":
  19:   client_certificate = var.clientCertificate

An argument named "client_certificate" is not expected here.
```

#### Config
```hcl
variable "subscriptionId" {}
variable "tenantId" {}
variable "clientId" {}
variable "clientCertificate" {}

terraform {
  required_providers {
    azapi = {
        source  = "azure/azapi"
        version = "=1.13.1"
    }
  }
}

provider "azapi" {
  subscription_id = var.subscriptionId
  tenant_id = var.tenantId
  client_id = var.clientId
  client_certificate = var.clientCertificate
}
```

**Comment by ms-henglu** [comment]
Hi @loomkoom ,

Thank you for taking time to report this issue, this feature has been released in the azapi v1.14.0. 

I'll close this issue as it's completed, but feel free to reopen it if there's any question.
