### ISSUE TITLE
Move an azure container job from a cae to another doesn't destroy and recreate it

### ISSUE THREAD

**Issue by btpemercier** [Azure/terraform-provider-azapi#490]
## Context

- an Azure container job
- a CAE called A
- a CAE called B

## Resource details

- Terraform resource : `azapi_resource`
- Azapi type : `Microsoft.App/jobs@2023-05-01`

## Reproduce

- Deploy CAE A
- Deploy container app job on CAE A
- Change the `body.properties.environmentId` to CAE B

## Current behavior

- Modify Job on CAE B

```json
{
  "error": {
     "code": "ContainerAppsJobEnvironmentMismatch",
     "message": "Container Apps Job 'container-app-name' already exists in a different environment. To create it in the environment '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.App/managedEnvironments/container-app-name' delete it from the enviroment 'cae-a' first."
   }
}
```

## Expected behavior

- Destroy Job on CAE A
- Create Job on CAE B

**Comment by ms-henglu** [comment]
Hello @btpemercier ,

Thank you for taking time to report this issue.

Currently the azapi provider doesn't support replacing resource when it is not able to update. For this case, please run `terraform taint azapi_resource.{container app label}`, then run `terraform apply` command and terraform destroy the container job before creating a new one.

**Comment by ms-henglu** [comment]
Hi @btpemercier ,

The v2.0.1 supports replacement triggers, more details please check: https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/2.0-upgrade-guide#replacement-triggers

I'll close this issue as it's resolved, but feel free to reopen if there's any questions.
