### ISSUE TITLE
Running Terraform init on Mac M3 Max

### ISSUE THREAD

**Issue by evotch** [Azure/terraform-provider-azapi#495]
│ Error while installing azure/azapi v1.13.1: archive has incorrect checksum zh:1747a2e3b341f2c05a3a54c6998a95ba00284db0d3d21767c5ba10fcff8505c2 (expected zh:e3eb48ee8c36ee4f81850d8a21fc59b81886c729d7c3b7adece4a25f355bed2f)

**Comment by ms-henglu** [comment]
Hi @evotch ,

Thank you for taking time to report this issue.

Which terraform are you using? Would you please try to use the latest Terraform version or use another network connection?

I downloaded the zip file from GitHub release, and the hash is matched:

```
> shasum -a 256 *.zip
e3eb48ee8c36ee4f81850d8a21fc59b81886c729d7c3b7adece4a25f355bed2f  terraform-provider-azapi_1.13.1_darwin_arm64.zip
```

**Comment by ms-henglu** [comment]
I'll close this issue as there's no response from the requestor, feel free to reopen this issue if there' any question.
