### ISSUE TITLE
Az Api Provider in firewall like a Malware

### ISSUE THREAD

**Issue by DAVIDR532** [Azure/terraform-provider-azapi#499]
This Provider is recognized by the firewalls like a malicious URL, please validate becuase i cant use this provider in my projects,.

required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azapi" {
}

**Comment by ms-henglu** [comment]
Hi @DAVIDR532 ,

Thank you for taking time to report this issue!

This provider is released on GitHub, please check whether the firewall blocks it.

**Comment by ms-henglu** [comment]
I'll close this issue as there's no response from the requestor, feel free to reopen this issue if there's any question.
