### ISSUE TITLE
Error: The terraform-provider-azapi_v1.13.1 plugin crashed!

### ISSUE THREAD

**Issue by TF-rk** [Azure/terraform-provider-azapi#502]
The provider crashes during initialization with the following error:

> Stack trace from the terraform-provider-azapi_v1.13.1 plugin:
> panic: interface conversion: interface {} is nil, not string
> goroutine 24 [running]:
> github.com/Azure/terraform-provider-azapi/internal/services.(*AzapiResource).Read(0xc000428028, {0xe0cb108, 0xc001678f30}, {{{{0xe0d00d8, 0xc001707050}, {0xcf1aa0, 0xc001706330}}, {0xe0d20c8, 0xc00027d180}}, 0xc000428068, ...}, ...)
> 	github.com/Azure/terraform-provider-azapi/internal/services/azapi_resource.go:616 +0x206c
> github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001eb860, {0xe0cb108, 0xc001678f30}, 0xc001678fc0, 0xc00077f6b8)
> 	github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_readresource.go:101 +0x64e
> github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001eb860, {0xe0cb108?, 0xc001678e10?}, 0xc0003fe280)
> 	github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_readresource.go:55 +0x3ff
> github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc00025efa0, {0xe0cb108?, 0xc001678270?}, 0xc001912060)
> 	github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/tf6server/server.go:776 +0x4c3
> github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xdf07e0?, 0xc00025efa0}, {0xe0cb108, 0xc001678270}, 0xc0001bc800, 0x0)
> 	github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x169
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b9200, {0xe0cb108, 0xc0016781b0}, {0xe0d0a60, 0xc00039c1a0}, 0xc00001c000, 0xc0003921e0, 0xe6fd1c8, 0x0)
> 	google.golang.org/grpc@v1.62.1/server.go:1386 +0xe23
> google.golang.org/grpc.(*Server).handleStream(0xc0001b9200, {0xe0d0a60, 0xc00039c1a0}, 0xc00001c000)
> 	google.golang.org/grpc@v1.62.1/server.go:1797 +0x100c
> google.golang.org/grpc.(*Server).serveStreams.func2.1()
> 	google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
> created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 12
> 	google.golang.org/grpc@v1.62.1/server.go:1038 +0x135
> 
> Error: The terraform-provider-azapi_v1.13.1 plugin crashed!
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.

Provider versions with this error: 1.13.0 & 1.13.1

No errors when I use the v1.12.0

**Comment by marvinbuss** [comment]
Any updates on this? I am also running into this issue.

**Comment by ms-henglu** [comment]
Hi @TF-rk  ,

Thank you for taking time to report this issue, the bug fix has been released in the azapi v1.14.0. 

I'll close this issue as it's completed, but feel free to reopen it if there's any question.
