### ISSUE TITLE
409 Conflict "AnotherOperationInProgress" when creating multiple subnets using azapi

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-provider-azapi#503]
I'm working on the AVM module for virtual networks, we are trialling AzAPI for the subnet creation as it better supports Azure Policy scenarios where route tables & NSGs need to be created at the same time as the subnet

All is working well except when creating or deleting multiple subnets there are fairly frequent race conditions reported as follows:

```
│ --------------------------------------------------------------------------------
│ RESPONSE 409: 409 Conflict
│ ERROR CODE: AnotherOperationInProgress
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "AnotherOperationInProgress",
│     "message": "Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/***/providers/Microsoft.Network/locations/westus2/operations/a12c9cd0-ef67-4686-ae31-32ef46bad36b?api-version=2023-11-01.",
│     "details": []
│   }
│ }
│ --------------------------------------------------------------------------------
```

I have tried to put in waits after the vnet operation (60 seconds so far, for both create & delete), but I think the conflict might actually be between the subnet operations.

Is this a bug?  It seems the op-lock for subnet operations is being released too quickly?

Example run;
https://github.com/kewalaka/terraform-azurerm-avm-res-network-virtualnetwork/actions/runs/9040871432

Code:
https://github.com/kewalaka/terraform-azurerm-avm-res-network-virtualnetwork/blob/feat/use-azapi-for-subnets/main.subnet.tf

Thanks!

**Comment by matt-FFFFFF** [comment]
You need to use the locks feature of AzAPI.

I would recommend setting the vnet resource id to the lock value.

This will act like a mutex and ensure only one operation happens at once.

See LZ vending module with the UMI federated credentials for an example.

**Comment by kewalaka** [comment]
closed as fixed as per Matt's suggestion.

**Comment by lestermarch** [comment]
> You need to use the locks feature of AzAPI.
> 
> I would recommend setting the vnet resource id to the lock value.
> 
> This will act like a mutex and ensure only one operation happens at once.
> 
> See LZ vending module with the UMI federated credentials for an example.

For anyone who lands on this thread, [here](https://github.com/Azure/terraform-azurerm-lz-vending/blob/bc62cc12abc6c150e3bebe2f9c201eb000a6e305/modules/usermanagedidentity/main.tf#L76) is the code reference.

In particular, there is a `locks` attribute for the subnet which you can set to (a list containing) your virtual network ID:

```hcl
resource "azapi_resource" "subnet" {
  for_each = var.subnets

  type = "Microsoft.Network/virtualNetworks/subnets@2024-05-01"

  name      = each.key
  locks     = [azapi_resource.virtual_network.id]
  parent_id = azapi_resource.virtual_network.id

  body = { ... }
}
```
