### ISSUE TITLE
IP whitelisting doesn't work on azapi_update_resource on AML

### ISSUE THREAD

**Issue by SnehithaGatadi** [Azure/terraform-provider-azapi#506]
The code used to whitelist Ip using azapi looks like below.

resource "azapi_update_resource" "azurerm_machine_learning_workspace" {
  type      = "Microsoft.MachineLearningServices/workspaces@2023-10-01"
  name      = "${var.resource_name}"
  parent_id = data.azurerm_resource_group.current.id
    body = jsonencode({
    properties = {
      "publicNetworkAccess": "Enabled",
      "ipAllowlist": [""]
}
})

I was trying to whitelist Ip on AML using azapi resource block. But failing to achieve the functionality as expected.
This functionality works fine while testing it using Azure REST API. But not with the code.
We need the functionality as Enabled from selected IP addresses. But instead, we are getting a functionality as Enabled from all networks.
Could you please let me know if I could get some help on achieving this functionality?

**Comment by SnehithaGatadi** [comment]
Hi stemaMSFT, we are using Terraform v1.7.5 and AzAPI >=0.3. I have also tried with the latest version of AzAPI = 1.13.1. But still it doesn't work.

**Comment by stemaMSFT** [comment]
Hey @SnehithaGatadi looking at the [AzAPI reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/workspaces?pivots=deployment-language-terraform) I don't see any ipAllowList property, nor do I see it in the [REST API docs](https://learn.microsoft.com/en-us/rest/api/azureml/workspaces/update?view=rest-azureml-2024-04-01&tabs=HTTP#publicnetworkaccess). Where are you getting that from?

**Comment by SnehithaGatadi** [comment]
Hi Steven,

Please find some of the links which I have followed.

Overview of the Terraform AzAPI provider | Microsoft Learn<https://learn.microsoft.com/en-us/azure/developer/terraform/overview-azapi-provider>
Support enabling public access only from IP ranges for AML · Issue #454 · Azure/terraform-provider-azapi (github.com)<https://github.com/Azure/terraform-provider-azapi/issues/454>

Thanks,
Snehitha

**Comment by ms-henglu** [comment]
Hi @SnehithaGatadi ,

Thank you for taking time to open this issue.

Here's an example:

```hcl

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "acctesthenglu56"
  location = "West Europe"
}

resource "azurerm_application_insights" "example" {
  name                = "acctesthenglu56"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

resource "azurerm_key_vault" "example" {
  name                = "acctesthenglu56"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "premium"
}

resource "azurerm_storage_account" "example" {
  name                     = "acctesthenglu56"
  location                 = azurerm_resource_group.example.location
  resource_group_name      = azurerm_resource_group.example.name
  account_tier             = "Standard"
  account_replication_type = "GRS"
}

resource "azapi_resource" "workspace" {
  type      = "Microsoft.MachineLearningServices/workspaces@2024-04-01-preview"
  parent_id = azurerm_resource_group.example.id
  name      = "acctesthenglu56"
  location  = "westeurope"
  identity {
    type         = "SystemAssigned"
    identity_ids = []
  }
  body = {
    properties = {
      applicationInsights = azurerm_application_insights.example.id
      keyVault            = azurerm_key_vault.example.id
      publicNetworkAccess = "Enabled"
      storageAccount      = azurerm_storage_account.example.id
      v1LegacyMode        = false
      ipAllowlist         = ["168.168.168.168/32"]
    }
    sku = {
      name = "Basic"
      tier = "Basic"
    }
  }
}
```

If you want to enable the `ipAllowlist ` feature on an existing machine learning workspace, please refer to the example below:

```hcl
resource "azurerm_machine_learning_workspace" "example" {
  name                    = "acctesthenglu56"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  application_insights_id = azurerm_application_insights.example.id
  key_vault_id            = azurerm_key_vault.example.id
  storage_account_id      = azurerm_storage_account.example.id

  identity {
    type = "SystemAssigned"
  }
  public_network_access_enabled = true
}

resource "azapi_update_resource" "update_workspace" {
  type        = "Microsoft.MachineLearningServices/workspaces@2024-04-01-preview"
  resource_id = azurerm_machine_learning_workspace.example.id
  body = {
    properties = {
      ipAllowlist = ["168.168.168.168/32"]
    }
  }
}

```

Related issue: https://github.com/Azure/terraform-provider-azapi/issues/454

**Comment by ms-henglu** [comment]
Hi @SnehithaGatadi , I just realized that you could configure this feature with azapi provider but it's not working as expected, right?

Please check the JSON view from the portal, and see if the `publicNetworkAccess` and `ipAllowlist` are configured correctly. If they're correctly configured, I believe this issue is on the machine learning service side.

**Comment by SnehithaGatadi** [comment]
Hi ms-henglu, I have checked the JSON view from the portal and could see the publicNetworkAccess and ipAllowlist are configured correctly.

**Comment by SnehithaGatadi** [comment]
Hi ms-henglu, do we have any solution for this issue?

**Comment by ms-henglu** [comment]
Hi @SnehithaGatadi , this seems to be an issue on the service. Because it's not working as expected but configured correctly. Would you please check it with azure machine learning service team? Thanks

**Comment by stemaMSFT** [comment]
@SnehithaGatadi we have spoken with the service team and they have stated that this would not be supported until the feature GA's, as they will need to make changes to the API/SDK of the service to make calls to the management plane that are currently not integrated.

**Comment by stemaMSFT** [comment]
Closing as this is not intended to be supported until service team modifies API.
