### ISSUE TITLE
No AKS Workload Identity support

### ISSUE THREAD

**Issue by MXClyde** [Azure/terraform-provider-azapi#518]
Azurerm provider supports [AKS Workload Identity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/aks_workload_identity). It seems azapi does not. Is there a workaround or plan to add this functionality?

**Comment by ms-henglu** [comment]
Hi @MXClyde ,

Thank you for taking time to report this!

We'll investigate how to support this feature in `azapi` provider.

**Comment by MXClyde** [comment]
Hi @ms-henglu,

FYI my colleague @walkline has created a pull request to add this support: https://github.com/Azure/terraform-provider-azapi/pull/522
