### ISSUE TITLE
Support for Machine Learning API Version: 2024-04-01

### ISSUE THREAD

**Issue by lightdrive** [Azure/terraform-provider-azapi#524]
# Overview
Whilst we are waiting for a native resource or an update in the AzureRM provider to provision Azure AI Studio we are instead trying the Az API provider but the required version 2024-04-01 is not listed as supported. When will it be added and released?

[Machine Learning Connections](https://github.com/hashicorp/terraform-provider-azurerm/issues/25857)

# Description
We've used Az API to provision almost all of the new resource types required for Azure AI Studio by using the newer API and setting __schema_validation__ to false apart from Machine Learning Connections, we can provision them but subsequent runs cause a provider crash on reading the resource.

Issue is similar to #502 but we have been able to add the location field to the resources and it still crashes on the read.

We are not expecting a bug fix here since we have bypassed the supported version.

**Comment by marvinbuss** [comment]
The API Version is supported just fine. Please check these samples:
* AI Studio Hub: https://github.com/PerfectThymeTech/terraform-azurerm-modules/tree/main/modules/aistudiohub
* AI Studio Project: https://github.com/PerfectThymeTech/terraform-azurerm-modules/tree/main/modules/aistudioproject
This is supported in azapi and hence you can close this ticket from my point of view.

**Comment by lightdrive** [comment]
Thanks for that, it looks like great code. I didn't go into extra detail on the issue for the sake of brevity, we're using Terraform Enterprise on v1.6.0 - I know you put great than 0.12 on your requirements but could you tell me which version exactly so I can try your code out? I presume you can re-run the code without a panic? We could provision but it would not run again when trying to read what it had provisioned.
________________________________

**Comment by marvinbuss** [comment]
With the latest `v1.14.0` i am able to deploy all resources just fine, but on the project, every update causes the following validation error:
```
{
│   "error": {
│     "code": "ValidationError",
│     "severity": null,
│     "message": "Managed network cannot be disabled once enabled.",
│     "messageFormat": null,
│     "messageParameters": null,
│     "referenceCode": null,
│     "detailsUri": null,
│     "target": null,
│     "details": [],
│     "innerError": null,
│     "debugInfo": null,
│     "additionalInfo": null
│   },
...
│ }
```

My property bag does not include any managed vnet references:
```hcl
...
  body = {
    kind = "Project"
    properties = {
      description         = "AI Studio Project - ${var.ai_studio_project_name}"
      friendlyName        = title(replace(var.ai_studio_project_name, "-", " "))
      hubResourceId       = var.ai_studio_hub_id
      publicNetworkAccess = "Disabled"
    }
  }
...
```

**Comment by ms-henglu** [comment]
Hi @marvinbuss , would you please open another issue for your case? It seems unrelated with this one.

**Comment by marvinbuss** [comment]
> Hi @marvinbuss , would you please open another issue for your case? It seems unrelated with this one.

@ms-henglu: I just created another issue here: https://github.com/Azure/terraform-provider-azapi/issues/564

**Comment by ms-henglu** [comment]
Hi @lightdrive ,

Thank you for taking time to report this issue.

Actually this resource type is supported by the latest azapi release, more details see: https://learn.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/2024-04-01/workspaces/connections?pivots=deployment-language-terraform

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, and feel free to reopen it if there's any questions.
