### ISSUE TITLE
API support for VM Avaialbility zone infromation

### ISSUE THREAD

**Issue by sureshg07** [Azure/terraform-provider-azapi#527]
We are using below mentioned API inoder to get the availability zone for Virtual Machines for each locations.

https://management.azure.com/subscriptions/$subscriptionID/providers/Microsoft.Compute/skus?api-version=2021-07-01&$filter=location eq $location'

We will like to request for api support to get the info from Terraform.

**Comment by ms-henglu** [comment]
Hi @sureshg07 ,

Thank you for taking time to report this issue!

There's already an issue requesting this feature: https://github.com/Azure/terraform-provider-azapi/issues/223. We're working on it and please subscribe above feature for the latest updates.

**Comment by zioproto** [comment]
For any one that needs an example. This example computes the possible availability zones for my subscription for the SKU `Standard_D4d_v5` in region `eastus2`.

```
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = ">=2.0, < 3.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.86.0, <4.0"
    }
  }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

data "azurerm_subscription" "current" {}

data "azapi_resource_list" "example" {
  parent_id              = data.azurerm_subscription.current.id
  type                   = "Microsoft.Compute/Skus@2021-07-01"
  response_export_values = ["*"]

  query_parameters = {
    "$filter" = [format("location eq '%s'", "eastus2")]
  }
}

locals {
  filtered_vms = [
    for item in data.azapi_resource_list.example.output.value :
    item if(item.resourceType == "virtualMachines" && item.name == "Standard_D4d_v5")
  ]
  zones = local.filtered_vms[0].locationInfo[0].zones
  restrictions = local.filtered_vms[0].restrictions[0].restrictionInfo.zones
  finalzones = setsubtract(local.zones, local.restrictions)
}
```

You can test now with Terraform console:

```
% terraform console
> local.finalzones
toset([
  "1",
  "3",
])
> exit
```
