### ISSUE TITLE
Is there documentation which API versions are supported by the provider?

### ISSUE THREAD

**Issue by A7exSchin** [Azure/terraform-provider-azapi#530]
I got a mail last week which basically states that an API version I use is to be deprecated and I should update. I am using `Microsoft.ContainerService/managedClusters@2023-01-02-preview` with the resource `azapi_update_resource`. I wanted to update to the newest API version supported by the provider but have not found any documentation or changelog entries for versions documenting which API versions are supported by the provider.

Is there anything to point me towards?

Thanks!

**Comment by ms-henglu** [comment]
Hi @A7exSchin ,

Thank you for taking time to report this issue!

Yes, please check this document for the available api-versions and properties: https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?pivots=deployment-language-terraform

**Comment by ms-henglu** [comment]
Yes.

**Comment by A7exSchin** [comment]
Thank you
