### ISSUE TITLE
azapi_update_resource - Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by lkurzyniec** [Azure/terraform-provider-azapi#531]
tf version
```
Terraform v1.6.6
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.13.1
+ provider registry.terraform.io/hashicorp/azurerm v3.107.0
```

tf code
```tf
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
    azapi = {
      source = "azure/azapi"
    }
  }
}

provider "azurerm" {
  features {}
}

locals {
  version = "v4"
}

resource "azurerm_resource_group" "example" {
  name     = "lk-auto-scale-out-test-rg"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "lk-auto-scale-out-test-asp-${local.version}"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "P0v3"
}

variable "configuration" {
  type = object({
    autoscaling = optional(object({
        service_plan_maximum_instance_count = number
      }))
  })
  nullable = false
  default = {
     autoscaling = {
       service_plan_maximum_instance_count = 7
     }
  }
}

resource "azapi_update_resource" "autoscaling" {
  type = "Microsoft.Web/serverfarms@2022-09-01"
  
  resource_id = azurerm_service_plan.example.id

  # https://learn.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms?pivots=deployment-language-terraform
  body = jsonencode({
    properties : {
      elasticScaleEnabled : var.configuration.autoscaling != null
      maximumElasticWorkerCount : try(var.configuration.autoscaling.service_plan_maximum_instance_count, 1)
    }
  })
}
```

error
> │ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azapi_update_resource.autoscaling, provider
│ "provider[\"registry.terraform.io/azure/azapi\"]" produced an unexpected new value: .resource_id: was
│ cty.StringVal("/subscriptions/b0fa95bd-adda-446a-8733-45ce9b1b1e34/resourceGroups/lk-auto-scale-out-test-rg/providers/Microsoft.Web/serverFarms/lk-auto-scale-out-test-asp-v4"),
│ but now
│ cty.StringVal("/subscriptions/b0fa95bd-adda-446a-8733-45ce9b1b1e34/resourceGroups/lk-auto-scale-out-test-rg/providers/Microsoft.Web/serverfarms/lk-auto-scale-out-test-asp-v4").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by ms-henglu** [comment]
Hi @lkurzyniec ,

Thank you for taking time to report this issue!

This is duplicated with: https://github.com/Azure/terraform-provider-azapi/issues/494, it has been fixed and will be released by the end of this month.

I'll close this issue but feel free to reopen it if there's any question.
