### ISSUE TITLE
Add Azure Load Test data plane resource support 

### ISSUE THREAD

**Issue by AndrewCi** [Azure/terraform-provider-azapi#547]
Hello -

This is a very similar request to https://github.com/Azure/terraform-provider-azapi/issues/439. Looking for data plane resource support for Azure Load Test.

The documentation is below:

https://learn.microsoft.com/en-us/rest/api/loadtesting/data-plane-uri?view=rest-loadtesting-dataplane-2022-11-01

Thank you in advance for the consideration. 

Best,
Andrew

**Comment by stemaMSFT** [comment]
@AndrewCi we do not have on our 2.0 roadmap plans to support data plane resources, as they would require manual implementation. We've looked into a few ideas so far but haven't liked any of the approaches we've come up with.
AzureRM would be a good place to gap-fill here imo.

**Comment by stemaMSFT** [comment]
@AndrewCi I think it would be best to see if you could get support from AzureRM, as they are where we expect data plane support to come from with Azure Terraform as of right now.

**Comment by ms-henglu** [comment]
I'll close this issue as it's out of azapi's support scope, but feel free to reopen if there's any question.
