### ISSUE TITLE
azapi_update_resource fails to update Microsoft.SecurityInsights/dataConnectors

### ISSUE THREAD

**Issue by shaken1901** [Azure/terraform-provider-azapi#548]
I'm not able to use azapi_update_resource to configure a Sentinel Data Connector.  A direct call to the API using the same url, method, and body works with an HTTP 201 Created response (powershell example provided).

Instead of succeeding, azapi_update_resource fails during apply with the error below.  The check for an existing resource may be unnecessary since the API call creates a new object if no other object of the same type exists.

Error encountered:
azapi_update_resource.upsert_dc: Creating...
╷
│ Error: Failed to retrieve resource
│
│   with azapi_update_resource.upsert_dc,
│   on main.tf line 58, in resource "azapi_update_resource" "upsert_dc":
│   58: resource "azapi_update_resource" "upsert_dc" {
│
│ checking for presence of existing Resource: (ResourceId
│ "/subscriptions/REDACTED/resourceGroups/example-rg/providers/Microsoft.OperationalInsights/workspaces/example-ws/providers/Microsoft.SecurityInsights/dataConnectors/<uuid>"
│ / Api Version "2021-10-01-preview"): GET
│ https://management.azure.com/subscriptions/REDACTED/resourceGroups/example-rg/providers/Microsoft.OperationalInsights/workspaces/example-ws/providers/Microsoft.SecurityInsights/dataConnectors/<uuid>
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE: NotFound

[sample-code.zip](https://github.com/user-attachments/files/16154843/sample-code.zip)

**Comment by ms-henglu** [comment]
Hi @shaken1901 ,

Thank you for taking time to report this issue and apologize for late response.

The `azapi_update_resource` is used to update some properties of an existing resource, so it will throw exceptions if the target resource doesn't exist. For this case, it's recommended to use `azapi_resource` to manage the resource if it doesn't exist before.

**Comment by ms-henglu** [comment]
I'll close this issue as there's no response. Feel free to reopen this issue if there're any questions.
