### ISSUE TITLE
Import state error with version 1.14

### ISSUE THREAD

**Issue by plk** [Azure/terraform-provider-azapi#555]
Since v1.14.0, trying to import into:

```
resource "azapi_resource" "somesubnet" {
  type      = "Microsoft.Network/virtualNetworks/subnets@2023-04-01"
```

```
Error: Missing Resource Import State
│
│ An unexpected error was encountered when importing the resource. This is always a problem with the provider. Please
│ give the following information to the provider developer:
│
│ Resource ImportState method returned no State in response. If import is intentionally not supported, remove the
│ Resource type ImportState method or return an error.
```

**Comment by stemaMSFT** [comment]
@plk thanks for the issue. Did this resource already exist? Did you run terraform import on it?
If it's existing, `aztfexport` may help: github.com/Azure/azfexport

**Comment by ms-henglu** [comment]
Hi @plk - I also failed to reproduce the issue, would you please try again with the latest terraform version? Thanks!

**Comment by plk** [comment]
I am on the latest TF (1.9.2) and azapi version - the issue arises when I try to import existing Azure subnets into a module containing the `azapi_resource` subnets e.g.:

```
import {
  to = module.spoke_vnet.azapi_resource.spokevnet_subnetmain
  id = "/subscriptions/${local.isub}/resourceGroups/rg-${local.suffix}-default/providers/Microsoft.Network/virtualNetworks/subnets/snet-${local.suffix}-1?api-version=2024-01-01"
}
```
```
module "spoke_vnet" {
  source = "../../../modules/spoke-vnet"
  providers = {
    azurerm.hub = azurerm.hub
  }
  rgname        = "rg-${local.suffix}-default"
  shortloc      = var.shortloc
  shortpurpose  = var.shortpurpose
  tid           = var.tid
  aks           = true
  address_space = local.address_space

```
where the module contains:

```
resource "azapi_resource" "spokevnet_subnetmain" {
  type      = "Microsoft.Network/virtualNetworks/subnets@2024-01-01"
  name      = "snet-${local.suffix}-1"
  parent_id = azurerm_virtual_network.spokevnet.id

  body = jsonencode({
    properties = {
      addressPrefixes                = [cidrsubnet(var.address_space[0], 27-local.pvnet[1], 0)]
      privateEndpointNetworkPolicies = "Enabled"
      networkSecurityGroup           = {
        id = azurerm_network_security_group.spokevnet_nsg1.id
      }
      routeTable                     = {
        id = azurerm_route_table.spokevnet_rt.id
      }
    }
  })
  lifecycle {
    ignore_changes = [tags]
  }
}

```

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
@plk 
I also failed to reproduce the issue. Here are the steps I took:

- Created the necessary resources (resource group, virtual network, security group, route table) using a Terraform file.
- Manually created a subnet resource on the Azure Portal.
- Updated the Terraform file to include the import block and module block, along with the module files.
Ran the Terraform script, and it worked as expected.

Let me know if you need further assistance or if there are any other details you can provide to help troubleshoot the issue.

**Comment by plk** [comment]
I am trying to import an entire VNET, route table, NSGs, subnets etc. from Azure. None of them currently managed by Terraform. I have a module to do this and it all works fine apart from the subnet imports into the module using azapi provider. It seems that the VNET import includes the subnets which might be the problem as I then try to import the subnets as stand-alone resources (required in our setup). Could that be the issue?

**Comment by weineran** [comment]
@plk FWIW, I was getting this error for `azapi_resource` with a different resource type, but it turned out I had an error in my `terraform import` command. In my case, I had the resource ID wrong.

So you might want to triple check that command for any mistakes.

I guess the feedback for Terraform is that the error message "This is always a problem with the provider" is not true, since in my case it was user error 😄

**Comment by ms-henglu** [comment]
Thanks @weineran for sharing this!

Hi @plk - in this comment: https://github.com/Azure/terraform-provider-azapi/issues/555#issuecomment-2247783808, I noticed in the below config, the subnet ID format is incorrect:

```
import {
  to = module.spoke_vnet.azapi_resource.spokevnet_subnetmain
  id = "/subscriptions/${local.isub}/resourceGroups/rg-${local.suffix}-default/providers/Microsoft.Network/virtualNetworks/subnets/snet-${local.suffix}-1?api-version=2024-01-01"
}
```

The virtual network name is missing: Microsoft.Network/virtualNetworks/subnets

**Comment by plk** [comment]
Ah, you are right, apologies - I was misled by the error messages from 1.13 and 1.14 which blamed token issues and the provider ...
