### ISSUE TITLE
Support data-plane resources

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#56]

**Comment by LaurentLesle** [comment]
Bumping on this request to the top of the pile. 

My use case is to call a keyvault backup operation of the an encryption key and execution a restore in another keyvault

<img width="856" alt="image" src="https://user-images.githubusercontent.com/4702224/230240255-8e25c8fe-78ec-46ce-b896-9442ec4a0d67.png">

**Comment by didayal-msft** [comment]
I am working on a module to build SQL MIs and need this feature to backup and restore keys from one key vault to other secondary key vaults.

**Comment by jorseng** [comment]
Currently I'm working key vault issuer module for a customer which requires to call the secrets from the vault via API, and without the data-plan support, I'm not able to read the secret and deploy the issuer.

**Comment by ms-henglu** [comment]
Related PR: https://github.com/Azure/terraform-provider-azapi/pull/298
