### ISSUE TITLE
New resource `azapi_resource_action` - manage any azure resource action

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#57]
This resource provides more flexibility, allows user to manage operations of an ARM resource, for example: list properties, or restart/stop a VM.

## v2 design
In the latest design, one `azapi_operation` can only manage one operation, this is simpler than previous design, and user can still toggle different status by using multiple operations with `count=0/1`. 

And there're other scenarios that this operation resource can help.
In short, azapi_operation enhanced azapi_resource/update_resource, user can add customized way to update azapi_resource, or a customized source for azapi_update_resource.
 
Example 1. The maria db only supports PATCH method to update some of its properties, so we use azapi_operation to manage the properties that needs to be updated by PATCH method.
This enables user to update resources which don’t support PUT update.
 
```
resource "azapi_resource" "server" {
  type      = "Microsoft.DBforMariaDB/servers@2018-06-01-preview"
  parent_id = azurerm_resource_group.test.id
  name      = "myServer"
  location  = "westus"
  body = jsonencode({
    properties = {
      administratorLogin = "adminuser"
      administratorLoginPassword = "<administratorLoginPassword>"
      createMode = "Default"
    }
  })
}
 
resource "azapi_operation" "server_configure" {
  type        = "Microsoft.DBforMariaDB/servers@2018-06-01-preview"
  resource_id = azapi_resource.server.id
  operation   = ""
  method      = "PATCH"
  body = jsonencode({
    properties = {
      administratorLoginPassword = "<administratorLoginPassword>"
      sslEnforcement             = "Disabled"
    }
  })
}
```
 
Example 2. This is used to address case like [azapi_update_resource - Put vs Patch · Issue #97 · Azure/terraform-provider-azapi (github.com)](https://github.com/Azure/terraform-provider-azapi/issues/97)
The problem is when user updates appsettings, appsettings can not be retrieved by GET because it contains credentials, it can only be retrieved by a POST request.
So, azapi_update_resource couldn’t work properly, because it can’t get the correct existing properties. But with azapi_operation, user can add a customized operation to get existing properties, and use hcl merge function to combine the existing properties and newly added ones.

```
resource "azapi_operation" "list_config" {
  type                   = "Microsoft.Web/sites/config@2021-02-01"
  resource_id            = "${azurerm_function_app.fnapp.id}/config/appsettings"
  operation              = "list"
  method                 = "POST"
  response_export_values = ["*"]
}
 

resource "azapi_update_resource" "fnapp_appsa_config" {
  type        = "Microsoft.Web/sites/config@2021-02-01"
  resource_id = "${azurerm_function_app.fnapp.id}/config/appsettings"
 
  body = jsonencode({
    properties = merge(
      jsondecode(azapi_operation.list_config.output).properties,
      {
        AzureWebJobsDashboard = "@Microsoft.KeyVault(***********)"
        AzureWebJobsStorage   = "@Microsoft.KeyVault(***********)"
    })
  })
}
```

## v1 design
This resource converts a set of operations to a manageable field, for example, if a service supports start/stop, this resource can convert them into a enabled/disabled state, like ex1.

The schema will look like the following, in each operation block, it defines an API operation by `opearion_name`, `body` and `method`, and adds an alias to it which can be used in `status`. This enables users to select one operation to execute.

```
resource "azapi_operation" "label" {
    type = "ResourceProvider@Api-version"
    resource_id = "the id of target resource"

    status = "name of the selected operation"

    // a list of available operations
    operation {
        name = "alias of this operation definition, like enabled, disabled"
        operation_name = "name of the API operation, like start, stop"
        body = "JSON data used in the operation"
        method = "Http Method, defaults to POST"
    }
}

```

Here're some examples :
ex1:
```
resource "azapi_operation" "example" {
  type        = "Microsoft.AppPlatform/Spring@2020-07-01"
  resource_id = azurerm_spring_cloud_service.example.id

  status = "enabled"
  operation {
    name           = "enabled"
    operation_name = "start"
    method          = "POST" // defaults to Post
    body = jsonencode({

    })
  }

  operation {
    name           = "disabled"
    operation_name = "stop"
    body = jsonencode({

    })
  }
}
```

ex2:
```
resource "azapi_operation" "another" {
  type        = "Microsoft.AppPlatform/Spring/buildServices/builds@2022-01-01-preview"
  resource_id = xxxxx.example.id

  status = "default"
  operation {
    name           = "default"
    operation_name = "getLogFileUrl"
  }

  response_export_values = ["property.blobUrl"]
}

output "blobUrl" {
  value = jsondecode(azapi_operation.another.output).property.blobUrl
}
```

**Comment by LaurentLesle** [comment]
Use case I have:
- pause / restart an azure firewall
- pause / restart an AKS cluster

**Comment by mlomat** [comment]
Waiting for it ! :)
This will also solve the below issues: 
- trigger sync of version control system to Automation Account 
- trigger start of run book on Automation Account
