### ISSUE TITLE
Call an Azure HTTP Api from Provider? (SpeechToText Webhook Create)

### ISSUE THREAD

**Issue by hongkongkiwi** [Azure/terraform-provider-azapi#570]
How can I call a simple Azure HTTP Rest API using this resource?

Specifically I would like to create a speechtotext webhook: https://learn.microsoft.com/en-us/rest/api/speechtotext/web-hooks/create?view=rest-speechtotext-2024-05-15-preview&tabs=HTTP

The says that it's a thin wrapper over the HTTP API, but I couldn't quite figure out how to make the call above. It seems to require a type which but I couldn't see how to map an HTTP Api above to a proper type, there seems to be nothing in the types that matches the above HTTP api.

Any help would be appreciated!

**Comment by ms-henglu** [comment]
Hi @hongkongkiwi ,

Thank you for taking time to report this issue!

This API is a data-plane API which is not supported by the `azapi` provider currently.

**Comment by ms-henglu** [comment]
I'll close this PR because it's out of azapi's data-plane support. But feel free to reopen it if there's any question.
