### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by ytimyno** [Azure/terraform-provider-azapi#576]
A comment seems to be unintentionally rendered into the documentation, towards the end of page https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/managed_service_identity

**Comment by ms-henglu** [comment]
Hi @ytimyno ,

Thank you for taking time to report this issue!

This is fixed by https://github.com/Azure/terraform-provider-azapi/pull/561 and the doc will be updated after the v1.15.0 release.

I'll close this issue as it's resolved, but feel free to reopen it if there's any question.
