### ISSUE TITLE
azapi_update_resource - remove vm from defender for cloud fails

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-provider-azapi#579]
Use case:
* we are adding a defender for cloud server workload protection plan to individual virtual machines 
* at some point we would like to remove some servers from the plan

Based on https://learn.microsoft.com/en-us/azure/defender-for-cloud/tutorial-enable-servers-plan#enable-defender-for-servers-at-the-resource-level-at-scale,
in order to add servers we use the following terraform code:

```hcl
resource "azapi_update_resource" "example" {
  type = "Microsoft.Security/pricings@2024-01-01"
  name = "VirtualMachines"
  parent_id = "/subscriptions/somesubscription/resourceGroups/someresourcegroup/providers/Microsoft.Compute/virtualMachines/somevm"

 body = {
     properties = {
       pricingTier = "Standard",
       subPlan     = "P1"
     }
  }
}
```

This works fine.

But as soon as we try to remove this server from the plan with the following code change:

```hcl
resource "azapi_update_resource" "example" {
  type = "Microsoft.Security/pricings@2024-01-01"
  name = "VirtualMachines"
  parent_id = "/subscriptions/somesubscription/resourceGroups/someresourcegroup/providers/Microsoft.Compute/virtualMachines/somevm"

 body = {
     properties = {
       pricingTier = "Free"
     }
  }
}
```

The azapi provider still submits the original property `subPlan` with value `P1` which results in the error:

```
{
│   "error": {
│     "code": "InvalidInputJson",
│     "message": "The 'SubPlan' property is not supported for pricing tier 'Free'."
│   }
│ }
```

We know that the azapi provider still includes the original `subPlan` property because we inspected the trace log:

```
"body":"{\"name\":\"VirtualMachines\",\"properties\":{\"extensions\":[{\"isEnabled\":\"False\",\"name\":\"MdeDesignatedSubscription\"}],\"pricingTier\":\"Free\",\"subPlan\":\"P1\"}}"
```

If we run `Free` freshly without any backing state, this runs fine.

**Comment by ms-henglu** [comment]
Hi @cveld ,

Thank you for taking time to report this issue!

The `azapi_update_resource` always fetch the latest state and combine with config, then send the request. So if there's no `subPlan` specified in the config, it will use the value from the remote.

Please try the below config:

```hcl

resource "azapi_update_resource" "example" {
  type      = "Microsoft.Security/pricings@2024-01-01"
  name      = "VirtualMachines"
  parent_id = azurerm_linux_virtual_machine.example.id

  body = {
    properties = {
      extensions = [
      ]
      pricingTier = "Free"
      subPlan     = null // explicitly specify to null here
    }
  }
}

```

**Comment by ms-henglu** [comment]
According to the document: https://learn.microsoft.com/en-us/azure/templates/microsoft.security/pricings?pivots=deployment-language-terraform#extension-2, the extensions are offered under a plan, my guess is the default instance already has some extensions enabled. If you want to use the Free plan, the extensions must be removed.
