### ISSUE TITLE
`azapi_resource` CreateUpdate method should handle 404 when GETing resource immediately after creation

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#587]
Hi @ms-henglu

After the `azapi_resource` creates a resource (`PUT`), it immediately issues a `GET` to read computed properties.

Given the short amount of time between the creation and the subsequent read, the provider should handle any 404 and retry. We now have the retry client in the provider so this could be used with a specific configuration, or we could use `utils.ResponseErrorWasNotFound` with a loop.

In any case I think we should try and retry this operation as without it, callers are subjected to the following type of error:

```
Γöé Error: Failed to create/update resource
Γöé 
Γöé   with module.foo_management_groups.module.policy_role_assignments["b942f318-7bfa-5f78-91a3-b0c3004fe7f0"].azapi_resource.this,
Γöé   on .terraform\modules\foo_management_groups\modules\azapi_helper\main.tf line 1, in resource "azapi_resource" "this":
Γöé    1: resource "azapi_resource" "this" {
Γöé 
Γöé creating/updating Resource: (ResourceId
Γöé "/providers/Microsoft.Management/managementGroups/foo/providers/Microsoft.Authorization/roleAssignments/b942f318-7bfa-5f78-91a3-b0c3004fe7f0"
Γöé / Api Version "2022-04-01"): GET
Γöé https://management.azure.com/providers/Microsoft.Management/managementGroups/foo/providers/Microsoft.Authorization/roleAssignments/b942f318-7bfa-5f78-91a3-b0c3004fe7f0
Γöé --------------------------------------------------------------------------------
Γöé RESPONSE 404: 404 Not Found
Γöé ERROR CODE: RoleAssignmentNotFound
Γöé --------------------------------------------------------------------------------
Γöé {
Γöé   "error": {
Γöé     "code": "RoleAssignmentNotFound",
Γöé     "message": "The role assignment 'b942f318-7bfa-5f78-91a3-b0c3004fe7f0' is not found."
Γöé   }
Γöé }
Γöé --------------------------------------------------------------------------------
```

Ref:

https://github.com/Azure/terraform-provider-azapi/blob/82cb8ace879ac1f47df63aec7aeeb9333517713b/internal/services/azapi_resource.go#L535

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thank you for taking time to report this issue!

Actually this seems to be an issue on the API side and we should report it to the service team and ask them to fix it.

For the workaround, is it possible to use `retry` field to mitigate it?

**Comment by matt-FFFFFF** [comment]
Hey @ms-henglu 

You are correct in that the RP should not return a 200 for a PUT if we cannot then successfully GET a resource. On the other hand the `AzureRM ` provider is full of these "workarounds" to ensure a good experience for the customer.

We certainly can use `retry`, though this would require specific configuration for each resource as the error code is unique.

For the GET operation: https://github.com/Azure/terraform-provider-azapi/blob/82cb8ace879ac1f47df63aec7aeeb9333517713b/internal/services/azapi_resource.go#L535

Perhaps we could add in a HTTP status code option that allows callers to specify any HTTP error code >=400 that would trigger a retry. I feel here we could add a 404 retry to the above to make customers lives easier. Perhaps not one for 2.0 but an improvement that could be made for 2.x?

**Comment by ms-henglu** [comment]
I'll close this issue as it's completed.
