### ISSUE TITLE
' azapi_resource ' resource does not support lifecycle meta argument

### ISSUE THREAD

**Issue by mukulkapoor01-new** [Azure/terraform-provider-azapi#601]
A terraform apply is trying to destroy and re-create an existing Webapp in Azure because it detects a change in location, which is not the case. A lifecycle meta argument to ignore then changes in ' location ' could be useful in this scenario but ' azapi_resource ' does not support it.

Azapi version used: 1.15.0

![image](https://github.com/user-attachments/assets/2e128723-f8fc-4001-9213-db2e90803fbd)

**Comment by matt-FFFFFF** [comment]
I use azapi and it supports lifecycle meta argument:

[see here](https://github.com/Azure/terraform-azurerm-lz-vending/blob/2a98d8fdad59056253fd8ce3f9f7992ade635571/modules/virtualnetwork/main.tf#L62-L64)

You should be able to ignore location changes like this:

```terraform
resource "azapi_resource" "foo" {
  # ... other attributes
  lifecycle {
    ignore_changes = [location]
  }
}
```

**Comment by ms-henglu** [comment]
I'll close this issue in favor of https://github.com/Azure/terraform-provider-azapi/issues/655 which also includes other resource types that have same issue.

Please subscribe to https://github.com/Azure/terraform-provider-azapi/issues/655 for any updates. Thanks.
