### ISSUE TITLE
Support request for containerapp runtime parameter

### ISSUE THREAD

**Issue by mapperCoderZ** [Azure/terraform-provider-azapi#603]
Is there a way to set the containerapp runtime to "Java" during containerapps creation ?
I am asking a support for this parameter: https://learn.microsoft.com/en-us/azure/container-apps/java-metrics?tabs=create&pivots=azure-portal#view-java-metrics

"Generic" is the default value. If we were able to set this parameter to "Java", we could activate JVM metrics.

**Comment by ms-henglu** [comment]
Hi @mapperCoderZ ,

Thank you for taking time to report this issue.

Yes, in the latest preview api-version, there's the following config which is used to configure the feature.

```hcl

 runtime = {
          dotnet = {
            autoConfigureDataProtection = bool
          }
          java = {
            enableMetrics = bool
            javaAgent = {
              enabled = bool
              logging = {
                loggerSettings = [
                  {
                    level = "string"
                    logger = "string"
                  }
                ]
              }
            }
          }
        }

```

More details see: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2024-02-02-preview/containerapps?pivots=deployment-language-terraform

**Comment by mapperCoderZ** [comment]
Thank you, I will try

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any questions.
