### ISSUE TITLE
Feature Request: `azapi_data_plane_resource` support for Purview Managed Virtual Networks

### ISSUE THREAD

**Issue by andyyensuin** [Azure/terraform-provider-azapi#614]
There is currently no way to deploy a Purview managed virtual network using `azapi_data_plane_resource`

[API - Data Plane reference](https://learn.microsoft.com/en-us/rest/api/purview/scanningdataplane/managed-virtual-networks/create-or-replace?view=rest-purview-scanningdataplane-2023-09-01&tabs=HTTP)

Tested with: 
```hcl
resource "azapi_data_plane_resource" "managed_vnet" {
  type      = "Microsoft.Purview/accounts/Scanning/managedvirtualnetworks@2023-09-01"
  parent_id = "${azurerm_purview_account.purview.name}.purview.azure.com/scan"
  name      = "defaultv2"

  body      = {
    properties = {}
  }
}
```

Error:
```
azapi_data_plane_resource.managed_vnet: Creating...
╷
│ Error: Failed to retrieve resource
│
│   with azapi_data_plane_resource.managed_vnet,
│   on purview.tf line 28, in resource "azapi_data_plane_resource" "managed_vnet":
│   28: resource "azapi_data_plane_resource" "managed_vnet" {
│
│ checking for presence of existing Resource: (ResourceId "" / Api Version "2023-09-01"): no Host in request URL
```

**Comment by ms-henglu** [comment]
Hi @andyyensuin ,

Thank you for taking time to report this issue.

The managed virtual network doesn't provide a API to delete the resource, so it could not be supported by the `azapi_data_plane_resource`.

**Comment by andyyensuin** [comment]
Hi @ms-henglu,

We can do a DELETE using az rest:

`az rest --method DELETE --uri "https://MyPurview.purview.azure.com/scan/managedvirtualnetworks/MyVnet?api-version=2023-09-01" --resource "https://purview.azure.net"`

Also, from the Purview Portal, deleting an Integration Runtime also does a DELETE on the managed vnet but with a `recursive=true` which deletes the: 
1. Managed Private Endpoints
2. Managed Integration Runtime
3. and finally the Managed Virtual Network

![image](https://github.com/user-attachments/assets/cf921211-80c3-46b1-b71e-1c58864e0032)

**Comment by ms-henglu** [comment]
Thanks @andyyensuin , I opened this PR to add support for this data plane resource type. https://github.com/Azure/terraform-provider-azapi/pull/622
