### ISSUE TITLE
v2.0.0-beta typo

### ISSUE THREAD

**Issue by FernandoMiguel** [Azure/terraform-provider-azapi#623]
https://github.com/Azure/terraform-provider-azapi/releases/tag/v2.0.0-beta
> The body field now only accepts an HCL object. Please remove the jsondecode function when using the body field.
it should be `jsonencode`

**Comment by ms-henglu** [comment]
Hi @FernandoMiguel ,

Thank you for taking time to report this issue.

I've fixed it in the release's description and opened a PR to fix it in the CHANGELOG. Thanks!
