### ISSUE TITLE
How to use azapi to create Azure storage account with PE and network acl && containers

### ISSUE THREAD

**Issue by RyanChen22** [Azure/terraform-provider-azapi#637]
As we noticed there might be a bug in using AzureRM module to create both storage accounts with PE and network acl && containers in GH https://github.com/hashicorp/terraform-provider-azurerm/issues/27607, my customers need further assistance to achieve the same scenario by using azapi. As of now, it keeps prompting the following exceptions:
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azapi: provider registry
registry.terraform.io
does not have
│ a provider named
registry.terraform.io/hashicorp/azapi
│
│ Did you intend to use azure/azapi? If so, you must specify that source address in each module which requires that provider. To see
│ which modules are currently depending on hashicorp/azapi, run the following command:
│ terraform providers

It will be appreciated if you could help to mitigate the issue above.

**Comment by ms-henglu** [comment]
Hi @RyanChen22 ,

Thank you for taking time to open the issue.

Please add the below config to your terraform configuration to specify the namespace of the azapi provider:

```hcl
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
      version = "2.0.0-beta" // version
    }
  }
}

provider "azapi" {
  # Configuration options
}
```

**Comment by RyanChen22** [comment]
@ms-henglu - The config has been used in the code but still caused the issue. Its just my customer is using v1.15.0. Is there any issue with 1.15.0? Cos 2.0.0 is currently in beta which is not allowed to be used in my customer environment.

**Comment by ms-henglu** [comment]
@RyanChen22 - v1.15.0 is fine. Please add the config to the workspace which uses the `azapi` provider too.

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any questions.
