### ISSUE TITLE
Bug: Latest Provider expecting different data types

### ISSUE THREAD

**Issue by ukhan262** [Azure/terraform-provider-azapi#645]
The code has not changed and the error is such.

![Image](https://github.com/user-attachments/assets/1e7f209a-9bfe-4c7c-b7f7-c8514806e5da)

When I use the provider version 1.15.0, then I do not see any of these issues.

Underlying, I have this module code where the azapi resource block is being used.
![Image](https://github.com/user-attachments/assets/45546e6a-b8fc-4774-8d2c-888da2ed385a)

The module is called like this
![Image](https://github.com/user-attachments/assets/d006a647-1be8-4dce-8fd7-1e3777288a70)

**Comment by cwe1ss** [comment]
v2 no longer supports jsonencode()/jsondecode() for body/output: 
* https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/2.0-upgrade-guide#dynamic-properties-support
* https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azapi-dynamic-properties/ba-p/4121855

**Comment by cwe1ss** [comment]
It might be good to link to some documentation in the given error message as I'm sure this will happen to many more people.

**Comment by ukhan262** [comment]
We will try to update the modules..

Typically, the module upgrades guides have this highlighted these type of things.

I have only seen a comment which does not clearly say that we can't use jsondecode/jsonencode going forward

**Comment by stemaMSFT** [comment]
@ms-henglu for just 2.0 versions can we perhaps implement a link to documentation like @cwe1ss mentioned?

**Comment by DillyBabu** [comment]
> v2 no longer supports jsonencode()/jsondecode() for body/output:
> 
> * https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/2.0-upgrade-guide#dynamic-properties-support
> * https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azapi-dynamic-properties/ba-p/4121855
@cwe1ss 
Thank you for the above links. Everything was fine until last Friday. From Monday (21/10/2024), Terraform validate started throwing error. After, removing jsonencode the properties block issues were solved.

**Comment by ms-henglu** [comment]
I'll close this issue as the document link is also included in the error message. Feel free to reopen it if there's any questions.
