### ISSUE TITLE
`azapi_update_resource` does not work with the latest provider version when for_each module is configured

### ISSUE THREAD

**Issue by shakaib-arif** [Azure/terraform-provider-azapi#656]
The latest provider is failing with the following error, **provider_version**: `2.0.1`
> Error: Invalid configuration
│
│   with module.azapi.azapi_update_resource.this,
│   on ..\azapi-update-resource\main.tf line 1, in resource "azapi_update_resource" "this":
│    1: resource "azapi_update_resource" "this" {
│
│ Only one of the arguments "name" or "resource_id" can be set

There are two options for this resource AFAIK to update the Azure resource.

- Option 1
  - name
  - parent_id
- Option 2
  - resource_id

In this [example-01](https://github.com/shakaib-arif/azapi-update-resource/tree/master/example-01), the `azapi_update_resource` resource is using the _option 2_ and explicitly [setting the other option 1 attributes](https://github.com/shakaib-arif/azapi-update-resource/blame/5b8e67e9a47610bf10df4616c056285d24eed2c6/example-01/main.tf#L19) to `null` which should be passed over to the module with for_each that's creating this the resource. It's not working as expected unless you explicitly set it in the module to `null`.

### Not Working

When `null` is passed over to the upstream resource via variable it is not working.

```
resource "azapi_update_resource" "this" {
  for_each                = var.update_resource_params
  name                    = each.value.name
  parent_id               = each.value.parent_id
  resource_id             = each.value.resource_id
  type                    = each.value.type 
  body                    = each.value.body 
  response_export_values  = each.value.response_export_values
  locks                   = each.value.locks
  ignore_casing           = each.value.ignore_casing
  ignore_missing_property = each.value.ignore_missing_property
}
```

### Working

When you set it explicitly to `null` in the resource then the validation and plan succeed but it kills the purpose of the for_each module.

```
resource "azapi_update_resource" "this" {
  for_each                = var.update_resource_params
  name                    = null
  parent_id               = null
  resource_id             = each.value.resource_id
  type                    = each.value.type # Required
  body                    = each.value.body # Required
  response_export_values  = each.value.response_export_values
  locks                   = each.value.locks
  ignore_casing           = each.value.ignore_casing
  ignore_missing_property = each.value.ignore_missing_property
}
```

This issue started appearing after the provider version `1.12.1` which is working perfectly fine in the [example-02](https://github.com/shakaib-arif/azapi-update-resource/tree/master/example-02)

Need assistance here as I'm out of ideas.

**Comment by ms-henglu** [comment]
Hi @shakaib-arif ,

Thank you for taking time to report this issue!

I think the root cause is on the Terraform Core side, that it doesn't validate the config based on the input variables.

I have a workaround which uses the provider function to build the resource ID from the parent ID and name, then we can set the resource ID field only.

```hcl

variable "update_list" {
  type = list(object({
    name        = optional(string)
    parent_id   = optional(string)
    resource_id = optional(string)
    type        = string
  }))
  default = [
    {
      name      = "test1"
      parent_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test1"
      type      = "Microsoft.Compute/virtualMachines@2024-07-01"
    },
    {
      name      = "test2"
      parent_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test2"
      type      = "Microsoft.Compute/virtualMachines@2024-07-01"
    },
    {
      resource_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test3/providers/Microsoft.Compute/virtualMachines/test3"
      type        = "Microsoft.Compute/virtualMachines@2024-07-01"
    }
  ]
}

resource "azapi_update_resource" "test" {
  for_each    = { for idx, value in var.update_list : idx => value }
  type        = each.value.type
  resource_id = each.value.resource_id != null ? each.value.resource_id : provider::azapi::build_resource_id(each.value.parent_id, each.value.type, each.value.name)
}

```

**Comment by shakaib-arif** [comment]
Hi @ms-henglu,

Thank you for the prompt response and for sharing the workaround.

I doubt that this could be a Terraform Core side issue because the same configuration of the module is working with the older version. 

I have tried this workaround on the underlying module and it resolved the issue. Thank you 😊
