### ISSUE TITLE
Not possible to create AzureArc Site manager resources

### ISSUE THREAD

**Issue by ankitatdnv** [Azure/terraform-provider-azapi#660]
Hi, 

I have a requirement to provision AzureArc site manager resources using AzAPI provider. But It seems like it's not possible to create it today, as it fails with following error:

```
embedded schema validation failed: the argument "type" is invalid.
│  resource type Microsoft.Edge/sites can't be found.
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
```

Please find below the terraform configurations:

```
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
      version = "2.0.1"
    }
  }
}

provider "azapi" {
  # Configuration options
}

resource "azapi_resource" "arc_site_manager" {
  name      = "test-osl"
  type      = "Microsoft.Edge/sites@2023-07-01-preview"
  parent_id = "/subscriptions/testSub/resourceGroups/testrg" 
  body      = {
    properties = {
      displayName = "testoslo"
      resourceGroupName   = "testrg"
      siteName = "site-osl"
      subscriptionId = "testSub"
    }
  }

  
}
```

**Comment by ms-henglu** [comment]
Hi @ankitatdnv ,

Thank you for taking time to report this issue.

The AzureArc Site manager's API spec is just merged two weeks ago, so it's not included in the azapi's latest release. Please skip the schema validation for now. It will be included in the next release.

refs: https://github.com/ms-henglu/bicep-types-az/blob/autogenerate/generated/edge/microsoft.edge/2024-02-01-preview/types.md#resource-microsoftedgesites2024-02-01-preview

**Comment by ankitatdnv** [comment]
Thanks @ms-henglu ,

It's working after disabling the schema validation, but now it's complaining on the next plan, about the various properties for AzureArc Site

```hcl
~ body                      = {
          - id         = "/subscriptions/testSub/resourceGroups/testrg/providers/microsoft.edge/sites/site-osl"
          - name       = "site-osl"
          ~ properties = {
              - provisioningState = "Succeeded"                
            }
          - systemData = {
              - createdAt          = "2024-11-06T08:03:47.7853751Z"
              - createdBy          = "User"
              - createdByType      = "User"
              - lastModifiedAt     = "2024-11-06T08:10:40.4240238Z"
              - lastModifiedBy     = "User"
              - lastModifiedByType = "User"
            }
          - type       = "microsoft.edge/sites"
        }        
      ~ output                    = {} -> (known after apply)
      ~ schema_validation_enabled = true -> false
```

Please find below the updated configurations:

```hcl
resource "azapi_resource" "arc_site_manager" {
  name      = "site-osl"
  type      = "Microsoft.Edge/sites@2024-02-01-preview"
  parent_id = "/subscriptions/testSub/resourceGroups/testrg" 
  schema_validation_enabled = false
  
  body      = {
    properties = {
      displayName = "Oslo"      
      addressResourceId = azapi_resource.arc_site_address.id

    }
    
  }

  
}
```

Is it due to schema validation disablement and will be fixed after the next release or it's due to some other issue?

**Comment by ms-henglu** [comment]
Hi @ankitatdnv , I believe that you imported the existing resource to the terraform state. Because of lacking embedded schema of this resource type, azapi imports everything to the state. So in the next terraform plan after importing the resource, you'll see above output to remove the undefined fields from the terraform state, it's the expected behavior. After applying this plan, you'll see no changes in the next terraform plan.

**Comment by ankitatdnv** [comment]
Thanks @ms-henglu, It worked after applying the plan. This case can be closed now
