### ISSUE TITLE
Feature request: support cross-providers resource move

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#664]
Terraform supports `moved` block which allows moving between two resources of different types. By supporting the new protocol, the resources from `azurerm` provider could be moved to `azapi` provider. 

Here's an example:

```hcl

resource "azurerm_resource_group" "test" {
  name     = "acctesthenglu1031"
  location = "East US"
}

# resource "azurerm_data_factory" "test" {
#   name                   = "heng"
#   location               = azurerm_resource_group.test.location
#   resource_group_name    = azurerm_resource_group.test.name
#   public_network_enabled = true
#   identity {
#     type = "SystemAssigned"
#   }
# }

moved {
  from = azurerm_data_factory.test
  to   = azapi_resource.factory
}

resource "azapi_resource" "factory" {
  type      = "Microsoft.DataFactory/factories@2018-06-01"
  parent_id = azurerm_resource_group.test.id
  name      = "heng"
  location  = "eastus"
  identity {
    type         = "SystemAssigned"
    identity_ids = []
  }

  body = {
    properties = {
      globalParameters    = {}
      publicNetworkAccess = "Enabled"
    }
  }
}


```

**Comment by stemaMSFT** [comment]
@ms-henglu does the end result behavior differ much from a `removed` and `import` block? Curious to see how this behaviors works across layers of modules as well.

**Comment by ms-henglu** [comment]
@stemaMSFT - Yes, there're some differences:

1. The major difference is the `moved` block could be used inside a module(it could also work across layers of modules), so for the module users, the migration could be transparent and without breaking changes. 
2. The plan output is different:
   1. The `removed` + `import` output: One resource will be imported and one resource will be no longer managed by Terraform.
   2. The `moved` output: The azurerm resource has been moved to azapi resource.

**Comment by ms-henglu** [comment]
Completed via https://github.com/Azure/terraform-provider-azapi/pull/668
