### ISSUE TITLE
bug: using multiple `locks` can result in a deadlock

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/terraform-provider-azapi#672]
If using multiple locks and the same locks are supplied to more than one resource, it can result in a deadlock due to the way the code handles the for loop for multiple locks. This only happens when timing is exact, but I have had it many times on a destroy run for vnet peering where I was attempting to lock both vnets for the forward and reverse peering.

For this code: 
https://github.com/Azure/terraform-provider-azapi/blob/0d963c24fd11d92345f410eed64af3fec6c22a58/internal/services/azapi_resource.go#L673

Here is an example:

- Resource 1
  - locks = [ “a”, “b” ]

- Resource 2
  - locks = [ “b”, “a” ]

1. Resource 1 locks “a”
1. Resource  2 locks “b”
1. Resource 1 tries to lock “b” and waits
1. Resource 2 tries to lock “a” and waits

This results in a deadlock, it waits forever and the apply never finishes. I left one running while I stepped away to sit an exam and it was still running after over 3 hours.

I can't immediately think of a solution to this, because adding a mutex before the `for` loop would block all resource with a lock and slow down the run.

Only other alternative is to support only one lock per resource or highlight this deadlock scenario in the docs to make people aware.

**Comment by ms-henglu** [comment]
Hello @jaredfholgate ,

Thank you for taking time to report this issue!

I think I can fix it by sorting the locks, I'll open a PR to fix it in the next release. For users who use old versions, they need to use a fixed order of the locked resource IDs to avoid deadlock.

For example, always set the locks to `[a, b]` instead of `[b, a]`.
