### ISSUE TITLE
Page missing

### ISSUE THREAD

**Issue by DeLeneMirouze** [Azure/terraform-provider-azapi#690]
This page does not exists:

https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_update_resource

**Comment by ms-henglu** [comment]
Hi @DeLeneMirouze ,

Thank you for taking time to report this issue!

Would you please share where you found the link? I think we need to update the docs.

The correct link is: https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/update_resource

**Comment by DeLeneMirouze** [comment]
Hello

Thank you for the Quick answer.

I found the link from a google séance.


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ms-henglu** [comment]
I've confirmed that MS Docs are updated with the latest link.

I'll close this issue as it's resolved but feel free to reopen it if you have any questions.
