### ISSUE TITLE
Incorrect `attributes.id` property stored in state when specifying `parent_id = "/"`

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#73]
Hi,

I am trying to test deploying resources at tenant scope `/`. In this case an empty ARM template.

This resource declaration actually creates the resource, but the `resourceAzApiResourceRead` func returns an error after creation, and subsequent `terraform plan` commands also fail.

## Error

```
azapi_resource.tenant_arm_deployment: Refreshing state... [id=//providers/Microsoft.Resources/deployments/tenantdeployment1234]
╷
│ Error: `resource_id` and `type` are not matched
│
│   with azapi_resource.tenant_arm_deployment,
│   on main.tf line 13, in resource "azapi_resource" "tenant_arm_deployment":
│   13: resource "azapi_resource" "tenant_arm_deployment" {
│
```

You can see the issue in that the resource id begins with two slashes - `//`, instead of one. If I manually edit the state to remove the extra `/` then it works as expected.

## Problematic resource declaration

```terraform
resource "azapi_resource" "tenant_arm_deployment" {
  type      = "Microsoft.Resources/deployments@2021-04-01"
  name      = "tenantdeployment1234"
  location  = "northeurope"
  parent_id = "/"

  body = jsonencode({
    properties = {
      mode = "Incremental"
      template = {
        "$schema"      = "https://schema.management.azure.com/schemas/2019-08-01/tenantDeploymentTemplate.json#"
        contentVersion = "1.0.0.0"
        outputs        = {}
        resources      = []
        variables      = {}
        parameters     = {}
      }
    }
  })
}
```

## Other information

This only happens if `parent_id = "/"`, if I set `parent_id = ""` then it works.

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thank you so much for taking your time to report this issue!!

I would suggest use empty string "" as `parent_id` for these tenant scope resources. And I'll raise a PR to prevent users setting `/` as the `parent_id`.

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thank you so much for taking your time to report this issue!!

I've raised a PR to fix this issue, and will add a validation to prevent user set `parent_id = ""`, which means "/" is the only allowed value.

**Comment by matt-FFFFFF** [comment]
Thanks @ms-henglu for the quick fix!

Confirmed working 🥳
