### ISSUE TITLE
Replace resource id parsing logic with azure SDK track2

### ISSUE THREAD

**Issue by ms-henglu** [Azure/terraform-provider-azapi#75]
ref: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azcore/arm

**Comment by teowa** [comment]
Seems in version `0.5.0`, the resource ID parsing is not compatible for Management Group ID(e.g., `/providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000`):  ​

use `azapi_resource_action` to perform POST https://management.azure.com/providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/register?api-version=2021-04-01:
```
provider "azapi" {}

provider "azurerm" {}

data "azurerm_subscription" "current" {}

resource "azurerm_management_group" "example" {
  display_name = "ExampleGroup"

  subscription_ids = [
    data.azurerm_subscription.current.subscription_id,
  ]
}

resource "azapi_resource_action" "registerNetwork" {
  type        = "Microsoft.Management/managementGroups@2021-04-01"
  resource_id = azurerm_management_group.example.id
  action      = "providers/Microsoft.Network/register"
  method      = "POST"
}
```
output:
```
╷
│ Error: No subscription ID found in: "providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000"
│
│   with azapi_resource_action.registerNetwork,
│   on main.tf line 117, in resource "azapi_resource_action" "registerNetwork":
│  117:   resource_id = azurerm_management_group.example.id
│
╵
```

and using parsing logic with azure SDK track2 can cover resource ID without subscription ID: 
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/arm/resource_identifier_test.go#L49
