### ISSUE TITLE
Links to docs are broken (404)

### ISSUE THREAD

**Issue by mattcowen** [Azure/terraform-provider-azapi#78]
On https://github.com/Azure/terraform-provider-azapi the links for docs e.g. https://registry.terraform.io/providers/Azure/azapi/latest/docs are broken (404)

**Comment by ms-henglu** [comment]
Hi @mattcowen ,

Thanks for taking time to report this issue!

This provider hasn't been published to Terraform registry, but soon. A workaround to check the docs is from here: https://github.com/Azure/terraform-provider-azapi/tree/main/docs

**Comment by ms-henglu** [comment]
Hi @mattcowen , 

This link works now, so I'll close this issue.
https://registry.terraform.io/providers/Azure/azapi/latest/docs
