### ISSUE TITLE
Automate registration process for providers

### ISSUE THREAD

**Issue by grayzu** [Azure/terraform-provider-azapi#82]
Register providers that are in the configuration before attempting to apply the configuration.

https://docs.microsoft.com/en-us/rest/api/resources/providers/register

**Comment by grayzu** [comment]
@ms-henglu not required for preview but we should look into this to streamline the process of using resources that are not registerred in a subscription. The current work around is to use the azurerm_resource_provider_registration resource but this is less than optimal.

**Comment by ms-henglu** [comment]
Hi @grayzu , 

Thanks for opening this issue.

This feature has been supported, and it uses track2 sdk built-in solution to register RP. And this feature is enabled by default, but can be disabled by configuring `skip_provider_registration=false` under provider block.

refs: The bottom of https://github.com/Azure/terraform-provider-azapi/blob/main/docs/index.md

**Comment by grayzu** [comment]
My understanding is that the registration logic that you are referring to above is based on a fixed list of known Azure providers. This will not be helpful for AzAPI, especially when it comes to preview services. As an example, I believe the fixed list is defined here in the AzureRM provider: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/provider/services.go 

What I believe this does is register ALL of these providers when AzAPI runs in a subscription. Ideally, we should not do this for the AzAPI provider because we do not have a known list. 

As an example, I created a configuration to manage an Azure Lab Services Account and Lab which failed because the "Microsoft.LabServices" provider is not in that list. I ended up manually registering the provider using the `azurerm_resource_provider_registration` resource which works well but would be good if we could streamline this process. 

What I am asking for in this issues is to just register providers that are included in the configuration.  Can you dig into this a bit more to see if we can be smarter about registering providers?

**Comment by ms-henglu** [comment]
Sorry that I forgot to add more context about the track2 built-in solution.

Please correct me if I was wrong @magodo , thanks!

The track2 lib will register the resource provider automatically if it sees a resource provider not registered error, then it will try the api request again.

 > As an example, I created a configuration to manage an Azure Lab Services Account and Lab which failed because the "Microsoft.LabServices" provider is not in that list. I ended up manually registering the provider using the azurerm_resource_provider_registration resource which works well but would be good if we could streamline this process.

But it seems not working? Any idea? @magodo

**Comment by ms-henglu** [comment]
@grayzu , did you add `ARM_SKIP_PROVIDER_REGISTRATION=true` to environment variables to skip provider registration of azurerm provider? It will skip provider registration of azapi provider as well.

**Comment by magodo** [comment]
The [RPRegistrationPolicy](https://github.com/Azure/terraform-provider-azapi/blob/bef63bbdf09032051b9e88e712f5c071bbb1bc5c/vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime/policy_register_rp.go#L49-L66) in track2 should try to register the RP if a prior call failed with `MissingSubscriptionRegistration` error code.

@grayzu Would you please share the config here for your use case if you confirmed that `ARM_SKIP_PROVIDER_REGISTRATION` is unset and the error remains.

**Comment by grayzu** [comment]
Thanks! I did have ARM_SKIP_PROVIDER_REGISTRATION set to true from another session. I have removed that and it seems to be working as expected. So good. 

Thanks @magodo & @ms-henglu! I will close this issue.
