### ISSUE TITLE
`use_msi` does not work

### ISSUE THREAD

**Issue by SudoSpartanDan** [Azure/terraform-provider-azapi#87]
The documentation states that using an MSI works with the provider. https://registry.terraform.io/providers/azure/azapi/latest/docs/guides/managed_service_identity#configuring-with-the-provider-block

But, in practice, it is not implemented in the provider configuration. https://github.com/Azure/terraform-provider-azapi/blob/159d8060e4fde94259200c6b1acffcc310fd4a7b/internal/provider/provider.go#L116-L129

Is this a feature we can expect to have? The azurerm provider supports this option.

**Comment by ms-henglu** [comment]
Hi @SudoSpartanDan ,

Thank you so much for taking time to report this issue.

Yes, using an MSI works with azapi provider, and this feature: managed identity authentication is enabled in authentication chain by default, no need to configure `use_msi=true` like azurerm provider, I've raised a PR to update the document.
