### ISSUE TITLE
The attribute `output` on `azapi_resource` is being recalculated with each terraform plan

### ISSUE THREAD

**Issue by SudoSpartanDan** [Azure/terraform-provider-azapi#88]
The resource `azapi_resource` has a computed value `output` that is being re-calculated with each Terraform plan, even when `response_export_values` is not set. This causes issues when detecting infrastructure drift in the plan after a successful apply.

```terraform
# azapi_resource.test will be updated in-place
  ~ resource "azapi_resource" "test" {
        body                      = (sensitive)
        id                        = "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxxxxxx/
        name                      = "xxxxxxxxxxxx"
      ~ output                    = jsonencode({}) -> (known after apply)
        # (6 unchanged attributes hidden)
    }
```

**Comment by SudoSpartanDan** [comment]
After digging a bit, it seems this is because the body has a sensitive value that is not returned on READ. When `ignore_missing_property`, this is resolved. Is there a way to get some more documentation around this behavior? When to expect it, how to handle, etc?

**Comment by ms-henglu** [comment]
Hi @SudoSpartanDan ,

Thank you so much for taking time to report this issue!

There's a troubleshoot document in progressing, I'll keep this issue open to keep track of document improvement.
https://github.com/Azure/terraform-provider-azapi/blob/main/documents/troubleshooting.md#q1-after-apply-plan-found-theres-still-a-change

When there's a property not returned on READ, terraform can show the diff of the body, however when body has sensitive value, the body diff is hidden, it's difficult for users to diagnose, we'll investigate how to improve it.

Thanks!

**Comment by SudoSpartanDan** [comment]
Awesome! Thanks for the update! Let me know if you need help developing any of that documentation/proof-reading.

**Comment by ms-henglu** [comment]
I've published a frequently asked question page to help users with these issues. https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/frequently_asked_questions
