### ISSUE TITLE
Using Filters In The URI

### ISSUE THREAD

**Issue by darren-johnson** [Azure/terraform-provider-azapi#98]
I am trying to use the provider to configure PIM for a resource and before I can configure a policy I need to retrieve the 'roleManagementPolicyId' which is unique for each policy. The [API Documentation](https://docs.microsoft.com/en-us/rest/api/authorization/privileged-role-policy-rest-sample) shows an example URL (see below) which appends a filter at the end to retrieve only the desired Role Management Policy.

GET https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter={filter}

There doesn't seem to be a way to handle this in the provider meaning I cannot retrieve the unique policy ID in order to perform the update.  I have tried various options to get this to work but with no luck. Is this capability missing or do the docs need updating?

**Comment by ms-henglu** [comment]
Hi @darren-johnson ,

Thank you for taking time to report this issue!

Yes, this is not supported by `azapi` provider. 
>There doesn't seem to be a way to handle this in the provider meaning I cannot retrieve the unique policy ID 

I'm not sure whether this can be done via other cli tools, but most importantly, `azapi` resource doesn't support `PATCH` method to update a resource.

**Comment by darren-johnson** [comment]
Thanks for getting back to me. I understand that azapi doesn't current support the PATCH method. Will support be added in future?  

Also it would be great if there is a way to add the filter for the GET request (data source). I would have thought this could be appended by having an optional argument.

**Comment by kvakulo** [comment]
The `PATCH` issue has been solved with the `azapi_resource_action`.

However, as I'm also interested in utilizing `azapi` for configuring PIM. Would it be possible to add the `filter` argument to the data sources?

**Comment by ms-henglu** [comment]
Hi @kvakulo,

Thanks for the feedback! Yes, I'll think about supporting query parameters in `azapi_resource_action` resource/data source.

**Comment by kvakulo** [comment]
It looks like it's actually possible by inserting the query parameters in the `name` property of the `azapi_resource` data source:

```terraform
data "azapi_resource" "example" {
  type                   = "Microsoft.Authorization/roleManagementPolicyAssignments@2020-10-01-preview"
  parent_id              = "/subscriptions/${var.subscription_id}"
  name                   = "?$filter=roleDefinitionId%20eq%20%27/subscriptions/${var.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/${var.role_definition_id}%27"
  response_export_values = ["*"]
}

output "policy_name" {
  value = jsondecode(data.azapi_resource.example.output).value.0.properties.policyId
}

// OUTPUT
policy_id = "/subscriptions/<subid>/providers/Microsoft.Authorization/roleManagementPolicies/<policyid>"
```

Guess it's a bit of a hack 😅

**Comment by ms-henglu** [comment]
Hi all,

Apologize for late update, in the v2.0.0-beta release, the azapi resources support the query parameters, please give it a try.

```

data "azapi_client_config" "current" {}

data "azapi_resource_list" "listPolicyDefinitionsBySubscription" {
  type      = "Microsoft.Authorization/policyDefinitions@2021-06-01"
  parent_id = "/subscriptions/${data.azapi_client_config.current.subscription_id}"
  query_parameters = {
    "$filter" = ["policyType eq 'BuiltIn'"]
  }
  response_export_values = ["*"]
}

output "o1" {
  value = data.azapi_resource_list.listPolicyDefinitionsBySubscription.output
}
```
