### ISSUE TITLE
response_export_values wildcard not working

### ISSUE THREAD

**Issue by darren-johnson** [Azure/terraform-provider-azapi#99]
According to the [docs](https://github.com/Azure/terraform-provider-azapi/blob/main/docs/data-sources/azapi_resource.md) I should be able to set to response_export_values ["*"] on a datasource and it will export the full response body. However this is not working for me as nothing is returned.  When looking at the state file all I see is the below snippet:

```hcl
            "response_export_values": [
              "*"
            ],
```

If I specify the values to return it works as expected but I want to understand what the api returns before refining the output to specified values.

I am running the below:

Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/azure/azapi v0.1.1
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v3.4.0

**Comment by ms-henglu** [comment]
Hi @darren-johnson ,

Thank you for taking time to report this issue!

This feature is just implemented and not released yet. There's a workaround for this, you can set values' prefix into `response_export_values`, for example, `response_export_values=["properties"]` can export most of the values.

**Comment by darren-johnson** [comment]
Thanks that is what I had been doing. Because it was in the docs already I didn't realise it hadn't been implemented.

**Comment by ms-henglu** [comment]
Hi @darren-johnson , this feature has been released in https://github.com/Azure/terraform-provider-azapi/releases/tag/v0.2.0
